# Generated by Django 5.1.7 on 2025-03-07 20:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя клиента')),
            ],
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название линии')),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название склада')),
            ],
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True, verbose_name='Номер контейнера')),
                ('status', models.CharField(choices=[('FLOATING', 'Плывет'), ('IN_PORT', 'В порту'), ('UNLOADED', 'Разгружен')], default='FLOATING', max_length=20, verbose_name='Статус')),
                ('eta', models.DateField(blank=True, null=True, verbose_name='ETA')),
                ('customs_procedure', models.CharField(blank=True, choices=[('TRANSIT', 'Транзит'), ('IMPORT', 'Импорт'), ('REEXPORT', 'Реэкспорт'), ('EXPORT', 'Экспорт')], max_length=20, null=True, verbose_name='Таможенная процедура')),
                ('ths', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='THS')),
                ('sklad', models.DecimalField(decimal_places=2, default=160, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='SKLAD')),
                ('days', models.PositiveIntegerField(default=0, verbose_name='DAYS')),
                ('dekl', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='DEKL')),
                ('prof', models.DecimalField(decimal_places=2, default=20, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='PROF')),
                ('unload_date', models.DateField(blank=True, null=True, verbose_name='Дата разгрузки')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.client', verbose_name='Клиент')),
                ('line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.line', verbose_name='Морская линия')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.warehouse', verbose_name='Склад')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Год выпуска')),
                ('brand', models.CharField(max_length=50, verbose_name='Марка')),
                ('vin', models.CharField(max_length=17, unique=True, verbose_name='VIN')),
                ('status', models.CharField(choices=[('FLOATING', 'Плывет'), ('IN_PORT', 'В порту'), ('UNLOADED', 'Разгружен')], max_length=20, verbose_name='Статус')),
                ('unload_date', models.DateField(blank=True, null=True, verbose_name='Дата разгрузки')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Итоговая цена')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.client', verbose_name='Клиент')),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='core.container', verbose_name='Контейнер')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.warehouse', verbose_name='Склад')),
            ],
        ),
        migrations.CreateModel(
            name='Declaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True, verbose_name='Номер декларации')),
                ('customs_procedure', models.CharField(choices=[('TRANSIT', 'Транзит'), ('IMPORT', 'Импорт'), ('REEXPORT', 'Реэкспорт'), ('EXPORT', 'Экспорт')], max_length=20, verbose_name='Таможенная процедура')),
                ('date', models.DateField(verbose_name='Дата оформления')),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.container', verbose_name='Контейнер')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True, verbose_name='Номер инвойса')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('issue_date', models.DateField(auto_now_add=True, verbose_name='Дата выпуска')),
                ('paid', models.BooleanField(default=False, verbose_name='Оплачен')),
                ('cars', models.ManyToManyField(to='core.car', verbose_name='Автомобили')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.client', verbose_name='Клиент')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('payment_type', models.CharField(choices=[('CASH', 'Наличные'), ('CARD', 'Безналичные')], max_length=20, verbose_name='Тип платежа')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('recipient', models.CharField(max_length=100, verbose_name='Получатель')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.invoice', verbose_name='Инвойс')),
                ('payer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.client', verbose_name='Плательщик')),
            ],
        ),
        migrations.CreateModel(
            name='Accounting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_status', models.CharField(default='PENDING', max_length=20, verbose_name='Статус синхронизации')),
                ('sync_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата синхронизации')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.invoice', verbose_name='Инвойс')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.payment', verbose_name='Платеж')),
            ],
        ),
    ]
