# Generated by Django 5.2.15 on 2026-06-12 13:52

import django.db.models.deletion
from django.db import migrations, models


def backfill_task_origin(apps, schema_editor):
    """Существующие авто-дела (из чекбокса «Важное») получают origin=AUTO_CAR."""
    Task = apps.get_model("core", "Task")
    Task.objects.filter(auto_created=True).update(origin="AUTO_CAR")


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_squashed_baseline'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('RULE', 'Правило (как действовать)'), ('FACT', 'Факт о бизнесе'), ('CONTACT', 'Контакт / отправитель')], default='RULE', max_length=10, verbose_name='Тип')),
                ('content', models.TextField(help_text='Само правило/факт в 1-3 предложениях. Попадает в промпт агента.', verbose_name='Содержание')),
                ('source', models.CharField(choices=[('QUESTION', 'Из ответа на вопрос'), ('MANUAL', 'Добавлено вручную'), ('REJECTION', 'Из отклонения предложения')], default='MANUAL', max_length=10, verbose_name='Источник')),
                ('embedding', models.JSONField(blank=True, null=True, verbose_name='Embedding')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активно')),
                ('times_used', models.IntegerField(default=0, verbose_name='Использований')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='Последнее использование')),
                ('created_by', models.CharField(blank=True, default='', max_length=100, verbose_name='Создал')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Память агента',
                'verbose_name_plural': 'Память агента',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('CREATE_TASK', 'Создать дело'), ('DRAFT_EMAIL_REPLY', 'Черновик ответа на письмо'), ('COMPLETE_TASK', 'Закрыть дело'), ('UPDATE_OBJECT', 'Изменить объект'), ('SEND_EMAIL', 'Отправить письмо'), ('OTHER', 'Другое')], max_length=30, unique=True, verbose_name='Тип действия')),
                ('mode', models.CharField(choices=[('ASK', 'Спрашивать подтверждение'), ('AUTO', 'Выполнять автоматически'), ('DISABLED', 'Запрещено')], default='ASK', max_length=10, verbose_name='Режим')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Комментарий')),
                ('updated_by', models.CharField(blank=True, default='', max_length=100, verbose_name='Изменил')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Политика автономии',
                'verbose_name_plural': 'Политики автономии',
                'ordering': ['action_type'],
            },
        ),
        migrations.AddField(
            model_name='containeremail',
            name='agent_analyzed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Разобрано агентом'),
        ),
        migrations.AddField(
            model_name='task',
            name='ai_summary',
            field=models.TextField(blank=True, default='', help_text='Краткое объяснение агента: кто пишет, зачем, что нужно сделать.', verbose_name='Резюме ИИ'),
        ),
        migrations.AddField(
            model_name='task',
            name='origin',
            field=models.CharField(choices=[('MANUAL', 'Вручную'), ('AUTO_CAR', 'Из чекбокса «Важное»'), ('AI', 'Создано ИИ')], db_index=True, default='MANUAL', help_text='Кто создал дело: пользователь, сигнал «Важное» или AI-агент.', max_length=10, verbose_name='Происхождение'),
        ),
        migrations.AddField(
            model_name='task',
            name='source_email',
            field=models.ForeignKey(blank=True, help_text='Письмо, из которого AI-агент создал это дело.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='core.containeremail', verbose_name='Письмо-источник'),
        ),
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('EMAIL_ANALYSIS', 'Анализ письма'), ('PLANNER', 'Планировщик'), ('EXECUTOR', 'Исполнение дела'), ('MEMORY_DISTILL', 'Дистилляция памяти')], max_length=20, verbose_name='Тип запуска')),
                ('status', models.CharField(choices=[('RUNNING', 'Выполняется'), ('SUCCESS', 'Успешно'), ('ERROR', 'Ошибка')], default='RUNNING', max_length=10, verbose_name='Статус')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Начало')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Конец')),
                ('input_ref', models.CharField(blank=True, default='', max_length=100, verbose_name='Вход')),
                ('model', models.CharField(blank=True, default='', max_length=100, verbose_name='LLM-модель')),
                ('input_tokens', models.IntegerField(default=0, verbose_name='Токены (вход)')),
                ('output_tokens', models.IntegerField(default=0, verbose_name='Токены (выход)')),
                ('cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10, verbose_name='Стоимость, $')),
                ('result_json', models.JSONField(blank=True, default=dict, verbose_name='Результат')),
                ('error', models.TextField(blank=True, default='', verbose_name='Ошибка')),
            ],
            options={
                'verbose_name': 'Запуск агента',
                'verbose_name_plural': 'Запуски агента',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['kind', '-started_at'], name='core_agentr_kind_940039_idx'), models.Index(fields=['status'], name='core_agentr_status_a2dcc4_idx')],
            },
        ),
        migrations.CreateModel(
            name='AgentQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OPEN', 'Открыт'), ('ANSWERED', 'Отвечен'), ('DISMISSED', 'Закрыт без ответа')], db_index=True, default='OPEN', max_length=10, verbose_name='Статус')),
                ('question', models.TextField(verbose_name='Вопрос агента')),
                ('context_json', models.JSONField(blank=True, default=dict, verbose_name='Контекст')),
                ('answer', models.TextField(blank=True, default='', verbose_name='Ответ владельца')),
                ('answered_by', models.CharField(blank=True, default='', max_length=100, verbose_name='Ответил')),
                ('answered_at', models.DateTimeField(blank=True, null=True, verbose_name='Отвечено в')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('memory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_questions', to='core.agentmemory', verbose_name='Созданное правило')),
                ('source_email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_questions', to='core.containeremail', verbose_name='Письмо-источник')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='core.agentrun', verbose_name='Запуск')),
            ],
            options={
                'verbose_name': 'Вопрос агента',
                'verbose_name_plural': 'Вопросы агента',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('CREATE_TASK', 'Создать дело'), ('DRAFT_EMAIL_REPLY', 'Черновик ответа на письмо'), ('COMPLETE_TASK', 'Закрыть дело'), ('UPDATE_OBJECT', 'Изменить объект'), ('SEND_EMAIL', 'Отправить письмо'), ('OTHER', 'Другое')], max_length=30, verbose_name='Тип действия')),
                ('risk_level', models.CharField(choices=[('READ', 'Только чтение'), ('LOW', 'Низкий'), ('MEDIUM', 'Средний'), ('HIGH', 'Высокий (деньги/удаление)')], default='LOW', max_length=10, verbose_name='Уровень риска')),
                ('status', models.CharField(choices=[('PROPOSED', 'Предложено'), ('APPROVED', 'Одобрено'), ('REJECTED', 'Отклонено'), ('EXECUTED', 'Выполнено'), ('AUTO_EXECUTED', 'Выполнено автоматически'), ('FAILED', 'Ошибка исполнения')], db_index=True, default='PROPOSED', max_length=15, verbose_name='Статус')),
                ('title', models.CharField(max_length=300, verbose_name='Краткое описание')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Параметры')),
                ('reasoning', models.TextField(blank=True, default='', verbose_name='Обоснование агента')),
                ('confidence', models.FloatField(blank=True, null=True, verbose_name='Уверенность (0-1)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='Решение принято')),
                ('decided_by', models.CharField(blank=True, default='', max_length=100, verbose_name='Решил')),
                ('reject_reason', models.TextField(blank=True, default='', verbose_name='Причина отклонения')),
                ('executed_at', models.DateTimeField(blank=True, null=True, verbose_name='Выполнено в')),
                ('result_json', models.JSONField(blank=True, default=dict, verbose_name='Результат исполнения')),
                ('error', models.TextField(blank=True, default='', verbose_name='Ошибка')),
                ('source_email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_actions', to='core.containeremail', verbose_name='Письмо-источник')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_actions', to='core.task', verbose_name='Связанное дело')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='core.agentrun', verbose_name='Запуск')),
            ],
            options={
                'verbose_name': 'Действие агента',
                'verbose_name_plural': 'Действия агента',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='core_agenta_status_99709e_idx'), models.Index(fields=['action_type', 'status'], name='core_agenta_action__2f5b09_idx')],
            },
        ),
        migrations.RunPython(backfill_task_origin, noop),
    ]
