# Generated by Django 5.1.7 on 2025-03-11 13:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='dekl',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='DEKL'),
        ),
        migrations.AddField(
            model_name='car',
            name='prof',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='PROF'),
        ),
        migrations.AddField(
            model_name='car',
            name='sklad',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='SKLAD'),
        ),
        migrations.AddField(
            model_name='car',
            name='ths',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='THS'),
        ),
    ]
