# Generated by Django 5.2.15 on 2026-06-12 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_agentmemory_agentpolicy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentaction',
            name='action_type',
            field=models.CharField(choices=[('CREATE_TASK', 'Создать дело'), ('DRAFT_EMAIL_REPLY', 'Черновик ответа на письмо'), ('COMPLETE_TASK', 'Закрыть дело'), ('CREATE_CONTAINER', 'Создать контейнер'), ('UPDATE_OBJECT', 'Изменить объект'), ('SEND_EMAIL', 'Отправить письмо'), ('OTHER', 'Другое')], max_length=30, verbose_name='Тип действия'),
        ),
        migrations.AlterField(
            model_name='agentpolicy',
            name='action_type',
            field=models.CharField(choices=[('CREATE_TASK', 'Создать дело'), ('DRAFT_EMAIL_REPLY', 'Черновик ответа на письмо'), ('COMPLETE_TASK', 'Закрыть дело'), ('CREATE_CONTAINER', 'Создать контейнер'), ('UPDATE_OBJECT', 'Изменить объект'), ('SEND_EMAIL', 'Отправить письмо'), ('OTHER', 'Другое')], max_length=30, unique=True, verbose_name='Тип действия'),
        ),
    ]
