# Generated by Django 5.1.7 on 2025-03-11 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_car_dekl_car_prof_car_sklad_car_ths'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='days',
            field=models.PositiveIntegerField(default=0, verbose_name='DAYS'),
        ),
    ]
