# Generated by Django 5.1.7 on 2025-03-11 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_car_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='free_days',
            field=models.PositiveIntegerField(default=0, verbose_name='Бесплатные дни'),
        ),
        migrations.AddField(
            model_name='container',
            name='free_days',
            field=models.PositiveIntegerField(default=0, verbose_name='Бесплатные дни'),
        ),
    ]
