# Generated by Django 5.2.15 on 2026-06-12 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_agentaction_action_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='containeremail',
            name='hidden_reason',
            field=models.CharField(blank=True, choices=[('', 'Не скрыто'), ('DUPLICATE', 'Контентный дубль'), ('FILTERED', 'Отсечено фильтром ингеста')], default='', max_length=10, verbose_name='Скрыто при ингесте'),
        ),
    ]
