# Generated by Django 5.2.15 on 2026-07-20 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_containeremail_hidden_reason'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autotransport',
            options={'ordering': ['-created_at'], 'verbose_name': 'Автовоз', 'verbose_name_plural': 'Автовозы'},
        ),
        migrations.AlterModelOptions(
            name='clientuser',
            options={'verbose_name': 'Доступ клиента в портал', 'verbose_name_plural': 'Доступы клиентов в портал'},
        ),
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Сообщение с сайта', 'verbose_name_plural': 'Сообщения с сайта'},
        ),
    ]
