# Generated by Django 5.1.7 on 2025-03-11 16:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_car_free_days_container_free_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ставка'),
        ),
        migrations.AddField(
            model_name='container',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ставка'),
        ),
    ]
