# Generated by Django 5.1.7 on 2025-03-11 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_car_rate_container_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='storage_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Складирование'),
        ),
        migrations.AddField(
            model_name='container',
            name='storage_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Складирование'),
        ),
    ]
