# Generated by Django 5.2.16 on 2026-07-21 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0005_rename_verbose_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrier',
            name='imones_kodas',
            field=models.CharField(blank=True, default='', help_text='Įmonės kodas — регистрационный код юрлица.', max_length=50, verbose_name='Įm. k. (код предприятия)'),
        ),
        migrations.AddField(
            model_name='carrier',
            name='physical_address',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Физический адрес'),
        ),
        migrations.AddField(
            model_name='carrier',
            name='registration_country',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Страна регистрации'),
        ),
        migrations.AddField(
            model_name='carrier',
            name='vat_code',
            field=models.CharField(blank=True, default='', help_text='PVM mokėtojo kodas, например LT100012345678.', max_length=50, verbose_name='Код НДС плательщика'),
        ),
        migrations.AddField(
            model_name='carrier',
            name='website',
            field=models.URLField(blank=True, default='', verbose_name='Сайт'),
        ),
        migrations.AddField(
            model_name='client',
            name='eori_code',
            field=models.CharField(blank=True, default='', help_text='Код EORI для таможенного оформления.', max_length=50, verbose_name='EORI код'),
        ),
        migrations.AddField(
            model_name='client',
            name='general_email',
            field=models.EmailField(blank=True, default='', help_text='Общий email компании — автоматически попадает в «Контакты».', max_length=254, verbose_name='Общая почта'),
        ),
        migrations.AddField(
            model_name='client',
            name='imones_kodas',
            field=models.CharField(blank=True, default='', help_text='Įmonės kodas — регистрационный код юрлица.', max_length=50, verbose_name='Įm. k. (код предприятия)'),
        ),
        migrations.AddField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='client',
            name='physical_address',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Физический адрес'),
        ),
        migrations.AddField(
            model_name='client',
            name='registration_country',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Страна регистрации'),
        ),
        migrations.AddField(
            model_name='client',
            name='vat_code',
            field=models.CharField(blank=True, default='', help_text='PVM mokėtojo kodas, например LT100012345678.', max_length=50, verbose_name='Код НДС плательщика'),
        ),
        migrations.AddField(
            model_name='client',
            name='website',
            field=models.URLField(blank=True, default='', verbose_name='Сайт'),
        ),
        migrations.AddField(
            model_name='company',
            name='eori_code',
            field=models.CharField(blank=True, default='', help_text='Код EORI для таможенного оформления.', max_length=50, verbose_name='EORI код'),
        ),
        migrations.AddField(
            model_name='company',
            name='general_email',
            field=models.EmailField(blank=True, default='', help_text='Общий email компании — автоматически попадает в «Контакты».', max_length=254, verbose_name='Общая почта'),
        ),
        migrations.AddField(
            model_name='company',
            name='imones_kodas',
            field=models.CharField(blank=True, default='', help_text='Įmonės kodas — регистрационный код юрлица.', max_length=50, verbose_name='Įm. k. (код предприятия)'),
        ),
        migrations.AddField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='company',
            name='physical_address',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Физический адрес'),
        ),
        migrations.AddField(
            model_name='company',
            name='registration_country',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Страна регистрации'),
        ),
        migrations.AddField(
            model_name='company',
            name='vat_code',
            field=models.CharField(blank=True, default='', help_text='PVM mokėtojo kodas, например LT100012345678.', max_length=50, verbose_name='Код НДС плательщика'),
        ),
        migrations.AddField(
            model_name='company',
            name='website',
            field=models.URLField(blank=True, default='', verbose_name='Сайт'),
        ),
        migrations.AddField(
            model_name='line',
            name='eori_code',
            field=models.CharField(blank=True, default='', help_text='Код EORI для таможенного оформления.', max_length=50, verbose_name='EORI код'),
        ),
        migrations.AddField(
            model_name='line',
            name='general_email',
            field=models.EmailField(blank=True, default='', help_text='Общий email компании — автоматически попадает в «Контакты».', max_length=254, verbose_name='Общая почта'),
        ),
        migrations.AddField(
            model_name='line',
            name='imones_kodas',
            field=models.CharField(blank=True, default='', help_text='Įmonės kodas — регистрационный код юрлица.', max_length=50, verbose_name='Įm. k. (код предприятия)'),
        ),
        migrations.AddField(
            model_name='line',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='line',
            name='physical_address',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Физический адрес'),
        ),
        migrations.AddField(
            model_name='line',
            name='registration_country',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Страна регистрации'),
        ),
        migrations.AddField(
            model_name='line',
            name='vat_code',
            field=models.CharField(blank=True, default='', help_text='PVM mokėtojo kodas, например LT100012345678.', max_length=50, verbose_name='Код НДС плательщика'),
        ),
        migrations.AddField(
            model_name='line',
            name='website',
            field=models.URLField(blank=True, default='', verbose_name='Сайт'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='eori_code',
            field=models.CharField(blank=True, default='', help_text='Код EORI для таможенного оформления.', max_length=50, verbose_name='EORI код'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='general_email',
            field=models.EmailField(blank=True, default='', help_text='Общий email компании — автоматически попадает в «Контакты».', max_length=254, verbose_name='Общая почта'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='imones_kodas',
            field=models.CharField(blank=True, default='', help_text='Įmonės kodas — регистрационный код юрлица.', max_length=50, verbose_name='Įm. k. (код предприятия)'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='physical_address',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Физический адрес'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='registration_country',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Страна регистрации'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='vat_code',
            field=models.CharField(blank=True, default='', help_text='PVM mokėtojo kodas, например LT100012345678.', max_length=50, verbose_name='Код НДС плательщика'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='website',
            field=models.URLField(blank=True, default='', verbose_name='Сайт'),
        ),
        migrations.CreateModel(
            name='CounterpartyBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='ID контрагента')),
                ('bank_name', models.CharField(blank=True, default='', max_length=150, verbose_name='Банк')),
                ('iban', models.CharField(max_length=50, verbose_name='IBAN / номер счёта')),
                ('swift', models.CharField(blank=True, default='', max_length=20, verbose_name='SWIFT / BIC')),
                ('currency', models.CharField(default='EUR', max_length=3, verbose_name='Валюта')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Основной')),
                ('notes', models.CharField(blank=True, default='', max_length=300, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Тип контрагента')),
            ],
            options={
                'verbose_name': 'Счёт контрагента',
                'verbose_name_plural': 'Счета контрагента',
                'ordering': ['-is_primary', 'bank_name', 'iban'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='core_counte_content_e78b0e_idx')],
            },
        ),
    ]
