# Generated by Django 5.2.16 on 2026-07-21 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_carrier_imones_kodas_carrier_physical_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrier',
            name='eori_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='EORI код'),
        ),
        migrations.AlterField(
            model_name='carrier',
            name='imones_kodas',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Im.k.'),
        ),
        migrations.AlterField(
            model_name='carrier',
            name='physical_address',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='carrier',
            name='registration_country',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='carrier',
            name='vat_code',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Код НДС'),
        ),
        migrations.AlterField(
            model_name='client',
            name='eori_code',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='EORI код'),
        ),
        migrations.AlterField(
            model_name='client',
            name='general_email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Общая почта'),
        ),
        migrations.AlterField(
            model_name='client',
            name='imones_kodas',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Im.k.'),
        ),
        migrations.AlterField(
            model_name='client',
            name='physical_address',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='client',
            name='registration_country',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='client',
            name='vat_code',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Код НДС'),
        ),
        migrations.AlterField(
            model_name='company',
            name='eori_code',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='EORI код'),
        ),
        migrations.AlterField(
            model_name='company',
            name='general_email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Общая почта'),
        ),
        migrations.AlterField(
            model_name='company',
            name='imones_kodas',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Im.k.'),
        ),
        migrations.AlterField(
            model_name='company',
            name='physical_address',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='company',
            name='registration_country',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='company',
            name='vat_code',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Код НДС'),
        ),
        migrations.AlterField(
            model_name='line',
            name='eori_code',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='EORI код'),
        ),
        migrations.AlterField(
            model_name='line',
            name='general_email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Общая почта'),
        ),
        migrations.AlterField(
            model_name='line',
            name='imones_kodas',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Im.k.'),
        ),
        migrations.AlterField(
            model_name='line',
            name='physical_address',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='line',
            name='registration_country',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='line',
            name='vat_code',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Код НДС'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='eori_code',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='EORI код'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='general_email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Общая почта'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='imones_kodas',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Im.k.'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='physical_address',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='registration_country',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='vat_code',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Код НДС'),
        ),
    ]
