# Generated by Django 5.2.16 on 2026-07-21 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_carrier_eori_code_alter_carrier_imones_kodas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='brand_color',
            field=models.CharField(blank=True, default='', help_text='HEX-цвет контейнера линии, напр. #F47920. Пусто — подбирается автоматически по названию.', max_length=7, verbose_name='Цвет бренда'),
        ),
    ]
