# Generated by Django 5.1.7 on 2025-03-11 17:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_car_prof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='prof',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='PROF'),
        ),
    ]
