# Generated by Django 5.2.16 on 2026-07-28 15:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_line_brand_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="warehouse",
            name="address4",
            field=models.CharField(blank=True, max_length=300, verbose_name="Адрес площадки 4"),
        ),
        migrations.AddField(
            model_name="warehouse",
            name="address4_name",
            field=models.CharField(blank=True, max_length=100, verbose_name="Название площадки 4"),
        ),
        migrations.AddField(
            model_name="warehouse",
            name="address5",
            field=models.CharField(blank=True, max_length=300, verbose_name="Адрес площадки 5"),
        ),
        migrations.AddField(
            model_name="warehouse",
            name="address5_name",
            field=models.CharField(blank=True, max_length=100, verbose_name="Название площадки 5"),
        ),
        migrations.AlterField(
            model_name="car",
            name="unload_site",
            field=models.SmallIntegerField(
                choices=[(1, "Площадка 1"), (2, "Площадка 2"), (3, "Площадка 3"), (4, "Площадка 4"), (5, "Площадка 5")],
                default=1,
                verbose_name="Адрес",
            ),
        ),
        migrations.AlterField(
            model_name="container",
            name="unload_site",
            field=models.SmallIntegerField(
                choices=[(1, "Площадка 1"), (2, "Площадка 2"), (3, "Площадка 3"), (4, "Площадка 4"), (5, "Площадка 5")],
                default=1,
                verbose_name="Адрес",
            ),
        ),
    ]
