# Generated by Django 5.1.7 on 2025-03-11 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_car_prof'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_outgoing',
            field=models.BooleanField(default=False, verbose_name='Исходящий счёт'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.warehouse', verbose_name='Получатель'),
        ),
    ]
