# Generated by Django 5.2.16 on 2026-08-09 09:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_warehouse_address4_warehouse_address4_name_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientDocument",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("PURCHASE_INVOICE", "Инвойс покупки (Bill of Sale)"),
                            ("TITLE", "Тайтл"),
                            ("BILL_OF_LADING", "Коносамент (Bill of Lading)"),
                            ("EXPORT_DECLARATION", "Экспортная декларация"),
                            ("POWER_OF_ATTORNEY", "Доверенность"),
                            ("OTHER", "Другой документ"),
                        ],
                        default="OTHER",
                        max_length=30,
                        verbose_name="Тип документа",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="client_documents/%Y/%m/",
                        validators=[django.core.validators.FileExtensionValidator(["pdf", "jpg", "jpeg", "png"])],
                        verbose_name="Файл",
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Комментарий клиента")),
                (
                    "status",
                    models.CharField(
                        choices=[("NEW", "Новый"), ("ACCEPTED", "Принят"), ("REJECTED", "Отклонён")],
                        default="NEW",
                        max_length=10,
                        verbose_name="Статус",
                    ),
                ),
                ("staff_comment", models.TextField(blank=True, verbose_name="Комментарий сотрудника")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата загрузки")),
                (
                    "car",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_documents",
                        to="core.car",
                        verbose_name="Автомобиль",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portal_documents",
                        to="core.client",
                        verbose_name="Клиент",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Загрузил",
                    ),
                ),
            ],
            options={
                "verbose_name": "Документ клиента",
                "verbose_name_plural": "Документы клиентов",
                "ordering": ["-uploaded_at"],
                "indexes": [models.Index(fields=["client", "-uploaded_at"], name="clientdoc_client_idx")],
            },
        ),
        migrations.CreateModel(
            name="DeclarationRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("number", models.CharField(blank=True, max_length=50, unique=True, verbose_name="Номер заявки")),
                (
                    "declaration_type",
                    models.CharField(
                        choices=[
                            ("TRANSIT", "Транзитная (T1)"),
                            ("EXPORT", "Экспортная"),
                            ("IMPORT", "Импортная"),
                            ("REEXPORT", "Реэкспорт"),
                        ],
                        default="TRANSIT",
                        max_length=10,
                        verbose_name="Тип декларации",
                    ),
                ),
                ("buyer_name", models.CharField(max_length=255, verbose_name="Получатель (имя / компания)")),
                (
                    "buyer_code",
                    models.CharField(
                        blank=True,
                        help_text="Регистрационный или личный код",
                        max_length=50,
                        verbose_name="Код получателя",
                    ),
                ),
                ("buyer_country", models.CharField(max_length=100, verbose_name="Страна получателя")),
                ("buyer_address", models.CharField(blank=True, max_length=255, verbose_name="Адрес получателя")),
                ("destination_country", models.CharField(max_length=100, verbose_name="Страна назначения")),
                ("destination_city", models.CharField(blank=True, max_length=100, verbose_name="Город назначения")),
                (
                    "invoice_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True, verbose_name="Стоимость по инвойсу"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[("USD", "USD"), ("EUR", "EUR")], default="USD", max_length=3, verbose_name="Валюта"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Примечания клиента")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "Новая"),
                            ("IN_PROGRESS", "В работе"),
                            ("READY", "Готова"),
                            ("REJECTED", "Отклонена"),
                        ],
                        default="NEW",
                        max_length=15,
                        verbose_name="Статус",
                    ),
                ),
                ("staff_comment", models.TextField(blank=True, verbose_name="Комментарий сотрудника")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="declaration_requests",
                        to="core.car",
                        verbose_name="Автомобиль",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="declaration_requests",
                        to="core.client",
                        verbose_name="Клиент",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создал",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка на декларацию",
                "verbose_name_plural": "Заявки на декларации",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["client", "-created_at"], name="declreq_client_idx"),
                    models.Index(fields=["status"], name="declreq_status_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="TransportRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("number", models.CharField(blank=True, max_length=50, unique=True, verbose_name="Номер заявки")),
                ("carrier_name", models.CharField(blank=True, max_length=255, verbose_name="Перевозчик (название)")),
                ("truck_number", models.CharField(max_length=20, verbose_name="Номер тягача")),
                ("trailer_number", models.CharField(blank=True, max_length=20, verbose_name="Номер прицепа")),
                ("driver_name", models.CharField(max_length=100, verbose_name="ФИО водителя")),
                ("driver_phone", models.CharField(blank=True, max_length=20, verbose_name="Телефон водителя")),
                ("border_crossing", models.CharField(blank=True, max_length=100, verbose_name="Граница пересечения")),
                (
                    "planned_loading_date",
                    models.DateField(blank=True, null=True, verbose_name="Планируемая дата загрузки"),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Комментарий клиента")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "Новая"),
                            ("IN_PROGRESS", "В обработке"),
                            ("ACCEPTED", "Принята"),
                            ("REJECTED", "Отклонена"),
                            ("COMPLETED", "Выполнена"),
                        ],
                        default="NEW",
                        max_length=15,
                        verbose_name="Статус",
                    ),
                ),
                ("staff_comment", models.TextField(blank=True, verbose_name="Комментарий сотрудника")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                (
                    "auto_transport",
                    models.ForeignKey(
                        blank=True,
                        help_text="Автовоз, созданный по этой заявке",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="client_requests",
                        to="core.autotransport",
                        verbose_name="Автовоз",
                    ),
                ),
                (
                    "cars",
                    models.ManyToManyField(related_name="transport_requests", to="core.car", verbose_name="Автомобили"),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transport_requests",
                        to="core.client",
                        verbose_name="Клиент",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создал",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка на автовоз",
                "verbose_name_plural": "Заявки на автовоз",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["client", "-created_at"], name="transreq_client_idx"),
                    models.Index(fields=["status"], name="transreq_status_idx"),
                ],
            },
        ),
    ]
