# Generated by Django 5.1.7 on 2025-03-15 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_invoice_warehouse_alter_invoice_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='is_outgoing',
            field=models.BooleanField(default=False, verbose_name='Нужно оплатить'),
        ),
    ]
