# Generated by Django 5.2.16 on 2026-08-09 10:23

from django.db import migrations, models


def migrate_old_statuses(apps, schema_editor):
    """Старые статусы → новая схема (NEW было дефолтом до редизайна флоу)."""
    TransportRequest = apps.get_model("core", "TransportRequest")
    TransportRequest.objects.filter(status="NEW").update(status="SUBMITTED")


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_clientdocument_declarationrequest_transportrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="transportrequest",
            name="carrier_eori",
            field=models.CharField(blank=True, max_length=50, verbose_name="EORI код перевозчика"),
        ),
        migrations.AlterField(
            model_name="transportrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Черновик"),
                    ("SUBMITTED", "Подана"),
                    ("ACCEPTED", "Принята"),
                    ("IN_PROGRESS", "В процессе"),
                    ("COMPLETED", "Оформлена"),
                ],
                default="DRAFT",
                max_length=15,
                verbose_name="Статус",
            ),
        ),
        migrations.RunPython(migrate_old_statuses, migrations.RunPython.noop),
    ]
