# Generated by Django 5.1.7 on 2025-03-28 14:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_invoice_is_outgoing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='prof',
        ),
        migrations.RemoveField(
            model_name='container',
            name='prof',
        ),
        migrations.AddField(
            model_name='car',
            name='proft',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='PROFT'),
        ),
        migrations.AddField(
            model_name='container',
            name='proft',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='PROFT'),
        ),
    ]
