# Generated by Django 5.2.16 on 2026-08-09 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_transportrequest_carrier_eori_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodelimage',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Создаётся автоматически (для списков, ~2–4 КБ).', null=True, upload_to='car_model_images/thumbs/', verbose_name='Миниатюра'),
        ),
    ]
