# Generated by Django 5.1.7 on 2025-04-21 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_car_prof_remove_container_prof_car_proft_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='from_balance',
            field=models.BooleanField(default=False, verbose_name='Оплачено с баланса'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('CASH', 'Наличные'), ('CARD', 'Безналичные'), ('BALANCE', 'С баланса')], max_length=20, verbose_name='Тип платежа'),
        ),
    ]
