# Generated by Django 5.2.16 on 2026-08-09 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_carmodelimage_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportrequest',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Черновик'), ('SUBMITTED', 'Подана'), ('ACCEPTED', 'Принята'), ('IN_PROGRESS', 'В процессе'), ('COMPLETED', 'Оформлена'), ('CANCELLED', 'Отменена')], default='DRAFT', max_length=15, verbose_name='Статус'),
        ),
    ]
