# Generated by Django 5.1.7 on 2025-04-22 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_payment_from_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='from_cash_balance',
            field=models.BooleanField(default=False, verbose_name='Оплачено с наличного баланса'),
        ),
    ]
