# Generated by Django 5.2.16 on 2026-08-09 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_transportrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanprocessingjob',
            name='target_container',
            field=models.ForeignKey(blank=True, help_text='Заполняется при загрузке скана из карточки контейнера.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_jobs_targeted', to='core.container', verbose_name='Контейнер (контекст загрузки)'),
        ),
        migrations.AlterField(
            model_name='scanprocessingjob',
            name='original_file',
            field=models.FileField(help_text='PDF/JPG/PNG, загруженный пользователем (один документ = одна задача).', upload_to='scan_jobs/%Y/%m/', verbose_name='Исходный скан'),
        ),
    ]
