# Generated by Django 5.2.16 on 2026-08-10 10:47

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_scanprocessingjob_target_container_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportDocumentPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='Данные пакета')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_doc_packages', to='core.car', verbose_name='Автомобиль')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doc_packages', to='core.transportrequest', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Пакет документов автовоза',
                'verbose_name_plural': 'Пакеты документов автовоза',
                'constraints': [models.UniqueConstraint(fields=('request', 'car'), name='uniq_docpackage_request_car')],
            },
        ),
        migrations.CreateModel(
            name='TransportRequestDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('PASSPORT', 'Паспорт'), ('INVOICE', 'Инвойс'), ('SIGNATURE', 'Подпись'), ('PAYMENT_ORDER', 'Платёжка'), ('LETTER_USA', 'Письмо USA'), ('OBLIGATION', 'Обязательство клиента'), ('CONTRACT', 'Договор на перевозку'), ('OTHER', 'Остальное')], default='OTHER', max_length=20, verbose_name='Тип документа')),
                ('file', models.FileField(upload_to='transport_docs/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='Файл')),
                ('is_generated', models.BooleanField(default=False, verbose_name='Сгенерирован системой')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_documents', to='core.car', verbose_name='Автомобиль')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.transportrequest', verbose_name='Заявка')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Загрузил')),
            ],
            options={
                'verbose_name': 'Документ заявки на автовоз',
                'verbose_name_plural': 'Документы заявок на автовоз',
                'ordering': ['doc_type', '-created_at'],
                'indexes': [models.Index(fields=['request', 'car'], name='transdoc_request_car_idx')],
            },
        ),
    ]
