# Generated by Django 5.1.7 on 2025-04-22 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_payment_from_cash_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='final_storage_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Финальная стоимость складирования'),
        ),
        migrations.AddField(
            model_name='car',
            name='transfer_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата передачи'),
        ),
        migrations.AddField(
            model_name='car',
            name='warehouse_days',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Дней на складе'),
        ),
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.CharField(choices=[('FLOATING', 'Плывет'), ('IN_PORT', 'В порту'), ('UNLOADED', 'Разгружен'), ('TRANSFERRED', 'Передан')], max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='container',
            name='status',
            field=models.CharField(choices=[('FLOATING', 'Плывет'), ('IN_PORT', 'В порту'), ('UNLOADED', 'Разгружен'), ('TRANSFERRED', 'Передан')], default='FLOATING', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='cars',
            field=models.ManyToManyField(blank=True, to='core.car', verbose_name='Автомобили'),
        ),
    ]
