# Generated by Django 5.1.7 on 2025-05-14 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_car_final_storage_cost_car_transfer_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Общий баланс'),
        ),
        migrations.AddField(
            model_name='client',
            name='card_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Безналичный баланс'),
        ),
        migrations.AddField(
            model_name='client',
            name='cash_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Наличный баланс'),
        ),
    ]
