# Generated by Django 5.2.16 on 2026-08-19 16:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_transportdocumentpackage_transportrequestdocument'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='declarationrequest',
            name='transport_request',
            field=models.ForeignKey(blank=True, help_text='Заявка, из которой создана декларация (когда оформляем сами).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='declaration_requests', to='core.transportrequest', verbose_name='Заявка на автовоз'),
        ),
        migrations.AddField(
            model_name='transportdocumentpackage',
            name='declaration_type',
            field=models.CharField(blank=True, choices=[('TRANSIT', 'Транзитная (T1)'), ('EXPORT', 'Экспортная'), ('IMPORT', 'Импортная'), ('REEXPORT', 'Реэкспорт')], help_text='Пусто — используется тип, указанный в заявке.', max_length=10, verbose_name='Тип декларации (по этому авто)'),
        ),
        migrations.AddField(
            model_name='transportrequest',
            name='awaiting_client_docs',
            field=models.BooleanField(default=False, verbose_name='Ожидаем документы от клиента'),
        ),
        migrations.AddField(
            model_name='transportrequest',
            name='declaration_type',
            field=models.CharField(blank=True, choices=[('TRANSIT', 'Транзитная (T1)'), ('EXPORT', 'Экспортная'), ('IMPORT', 'Импортная'), ('REEXPORT', 'Реэкспорт')], help_text='Тип декларации, который должен оформить склад по этой заявке.', max_length=10, verbose_name='Требуемая декларация'),
        ),
        migrations.AddField(
            model_name='transportrequest',
            name='sent_to_warehouse_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Отправлена складу'),
        ),
        migrations.AddField(
            model_name='transportrequest',
            name='warehouse',
            field=models.ForeignKey(blank=True, help_text='Склад, которому отправлена заявка на загрузку автовоза.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transport_requests', to='core.warehouse', verbose_name='Склад-получатель'),
        ),
        migrations.AddField(
            model_name='transportrequest',
            name='warehouse_confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Подтверждена складом'),
        ),
        migrations.AddField(
            model_name='transportrequest',
            name='warehouse_state',
            field=models.CharField(choices=[('NOT_SENT', 'Не отправлена складу'), ('SENT', 'Отправлена складу'), ('CONFIRMED', 'Подтверждена складом'), ('REJECTED', 'Отклонена складом')], default='NOT_SENT', max_length=10, verbose_name='Состояние по складу'),
        ),
        migrations.AlterField(
            model_name='caremaillink',
            name='matched_by',
            field=models.CharField(choices=[('CONTAINER_NUMBER', 'По номеру контейнера'), ('BOOKING_NUMBER', 'По номеру букинга'), ('THREAD', 'По треду'), ('MANUAL', 'Привязано вручную'), ('UNMATCHED', 'Не привязано'), ('VIN', 'По VIN машины'), ('REQUEST_NUMBER', 'По номеру заявки на автовоз')], default='UNMATCHED', help_text='Обычно VIN; MANUAL — если пришло из карточки Car.', max_length=20, verbose_name='Как сопоставлено'),
        ),
        migrations.AlterField(
            model_name='containeremail',
            name='matched_by',
            field=models.CharField(choices=[('CONTAINER_NUMBER', 'По номеру контейнера'), ('BOOKING_NUMBER', 'По номеру букинга'), ('THREAD', 'По треду'), ('MANUAL', 'Привязано вручную'), ('UNMATCHED', 'Не привязано'), ('VIN', 'По VIN машины'), ('REQUEST_NUMBER', 'По номеру заявки на автовоз')], default='UNMATCHED', max_length=20, verbose_name='Как сопоставлено'),
        ),
        migrations.AlterField(
            model_name='containeremaillink',
            name='matched_by',
            field=models.CharField(choices=[('CONTAINER_NUMBER', 'По номеру контейнера'), ('BOOKING_NUMBER', 'По номеру букинга'), ('THREAD', 'По треду'), ('MANUAL', 'Привязано вручную'), ('UNMATCHED', 'Не привязано'), ('VIN', 'По VIN машины'), ('REQUEST_NUMBER', 'По номеру заявки на автовоз')], default='UNMATCHED', help_text='Причина связи именно с этим контейнером. Может отличаться от ContainerEmail.matched_by (первичная причина).', max_length=20, verbose_name='Как сопоставлено'),
        ),
        migrations.CreateModel(
            name='TransportRequestEmailLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matched_by', models.CharField(choices=[('CONTAINER_NUMBER', 'По номеру контейнера'), ('BOOKING_NUMBER', 'По номеру букинга'), ('THREAD', 'По треду'), ('MANUAL', 'Привязано вручную'), ('UNMATCHED', 'Не привязано'), ('VIN', 'По VIN машины'), ('REQUEST_NUMBER', 'По номеру заявки на автовоз')], default='UNMATCHED', help_text='THREAD — ответ склада в треде; MANUAL — отправлено из карточки заявки.', max_length=20, verbose_name='Как сопоставлено')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано в карточке заявки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_request_links', to='core.containeremail')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_links', to='core.transportrequest')),
            ],
            options={
                'verbose_name': 'Связь письма с заявкой на автовоз',
                'verbose_name_plural': 'Связи писем с заявками на автовоз',
            },
        ),
        migrations.AddField(
            model_name='containeremail',
            name='transport_requests',
            field=models.ManyToManyField(blank=True, related_name='emails', through='core.TransportRequestEmailLink', through_fields=('email', 'request'), to='core.transportrequest', verbose_name='Заявки на автовоз'),
        ),
        migrations.CreateModel(
            name='TransportRequestMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_kind', models.CharField(choices=[('STAFF', 'От нас клиенту'), ('CLIENT', 'От клиента')], default='STAFF', max_length=10, verbose_name='Автор (сторона)')),
                ('kind', models.CharField(choices=[('MESSAGE', 'Сообщение'), ('DOC_REQUEST', 'Запрос документов')], default='MESSAGE', max_length=15, verbose_name='Тип')),
                ('body', models.TextField(blank=True, verbose_name='Текст')),
                ('requested_doc_types', models.JSONField(blank=True, default=list, help_text='Коды типов документов пакета.', verbose_name='Запрошенные документы')),
                ('attachment', models.FileField(blank=True, upload_to='transport_messages/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='Вложение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('read_by_staff_at', models.DateTimeField(blank=True, null=True, verbose_name='Прочитано сотрудником')),
                ('read_by_client_at', models.DateTimeField(blank=True, null=True, verbose_name='Прочитано клиентом')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('car', models.ForeignKey(blank=True, help_text='Если замечание относится к конкретному авто заявки.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transport_request_messages', to='core.car', verbose_name='Автомобиль')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.transportrequest', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Сообщение по заявке на автовоз',
                'verbose_name_plural': 'Сообщения по заявкам на автовоз',
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.AddIndex(
            model_name='transportrequestemaillink',
            index=models.Index(fields=['request', 'is_read'], name='core_transp_request_9371de_idx'),
        ),
        migrations.AddConstraint(
            model_name='transportrequestemaillink',
            constraint=models.UniqueConstraint(fields=('email', 'request'), name='trreqemaillink_unique_email_request'),
        ),
        migrations.AddIndex(
            model_name='transportrequestmessage',
            index=models.Index(fields=['request', 'created_at'], name='trmsg_request_idx'),
        ),
        migrations.AddIndex(
            model_name='transportrequestmessage',
            index=models.Index(fields=['request', 'read_by_staff_at'], name='trmsg_unread_staff_idx'),
        ),
        migrations.AddIndex(
            model_name='transportrequestmessage',
            index=models.Index(fields=['request', 'read_by_client_at'], name='trmsg_unread_client_idx'),
        ),
    ]
