# Generated by Django 5.2.16 on 2026-08-19 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_declarationrequest_transport_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationlog',
            name='transport_request',
            field=models.ForeignKey(blank=True, help_text='Для уведомлений по переписке в заявке на автовоз', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.transportrequest', verbose_name='Заявка на автовоз'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='notification_type',
            field=models.CharField(choices=[('PLANNED', 'Планируемая разгрузка'), ('UNLOADED', 'Разгрузка выполнена'), ('CAR_UNLOADED', 'Разгрузка ТС (без контейнера)'), ('REQUEST_MESSAGE', 'Сообщение по заявке на автовоз'), ('REQUEST_DOCS', 'Запрос документов по заявке')], max_length=20, verbose_name='Тип уведомления'),
        ),
    ]
