# Generated by Django 5.1.7 on 2025-05-19 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_client_balance_client_card_balance_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'verbose_name': 'Инвойс', 'verbose_name_plural': 'Инвойсы'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Платеж', 'verbose_name_plural': 'Платежи'},
        ),
        migrations.AddField(
            model_name='payment',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
    ]
