# Generated by Django 5.2.16 on 2026-08-19 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_notificationlog_transport_request_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transportdocumentpackage',
            name='declaration_type',
        ),
        migrations.AlterField(
            model_name='transportrequest',
            name='declaration_type',
            field=models.CharField(blank=True, choices=[('TRANSIT', 'Транзитная (T1)'), ('EXPORT', 'Экспортная'), ('IMPORT', 'Импортная'), ('REEXPORT', 'Реэкспорт')], help_text='Тип по умолчанию: одна декларация на все авто заявки. Отдельные декларации на часть машин задаются в карточке заявки.', max_length=10, verbose_name='Требуемая декларация'),
        ),
        migrations.CreateModel(
            name='TransportDeclarationGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('declaration_type', models.CharField(choices=[('TRANSIT', 'Транзитная (T1)'), ('EXPORT', 'Экспортная'), ('IMPORT', 'Импортная'), ('REEXPORT', 'Реэкспорт')], max_length=10, verbose_name='Тип декларации')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Примечание')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('cars', models.ManyToManyField(blank=True, related_name='transport_declaration_groups', to='core.car', verbose_name='Автомобили')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='declaration_groups', to='core.transportrequest', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Декларация заявки',
                'verbose_name_plural': 'Декларации заявки',
                'ordering': ['position', 'pk'],
            },
        ),
    ]
