# Generated by Django 5.1.7 on 2025-05-19 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_client_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Общий баланс'),
        ),
    ]
