# Generated by Django 5.2.16 on 2026-08-20 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_transportdeclarationgroup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transportrequest',
            name='destination_country',
            field=models.CharField(blank=True, choices=[('BY', 'Беларусь'), ('MD', 'Молдова'), ('UA', 'Украина')], help_text='Куда идут автомобили — от страны зависят требования таможни к пакету документов.', max_length=2, verbose_name='Страна назначения'),
        ),
        migrations.CreateModel(
            name='TransportDocumentRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(choices=[('BY', 'Беларусь'), ('MD', 'Молдова'), ('UA', 'Украина')], max_length=2, verbose_name='Страна назначения')),
                ('procedure', models.CharField(choices=[('TRANSIT', 'Транзитная (T1)'), ('EXPORT', 'Экспортная'), ('IMPORT', 'Импортная'), ('REEXPORT', 'Реэкспорт')], max_length=10, verbose_name='Таможенная процедура')),
                ('required_doc_types', models.JSONField(blank=True, default=list, help_text='Типы документов, без которых пакет по авто считается неполным.', verbose_name='Обязательные документы')),
                ('is_active', models.BooleanField(default=True, help_text='Выключено — для этой пары берётся набор по умолчанию.', verbose_name='Действует')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Примечание')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
            ],
            options={
                'verbose_name': 'Требования к документам',
                'verbose_name_plural': 'Требования к документам (страна + процедура)',
                'ordering': ['country', 'procedure'],
                'constraints': [models.UniqueConstraint(fields=('country', 'procedure'), name='uniq_docrule_country_procedure')],
            },
        ),
    ]
