# Generated by Django 5.1.7 on 2025-05-20 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_client_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='balance',
        ),
        migrations.AddField(
            model_name='client',
            name='debt',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Долг'),
        ),
        migrations.AlterField(
            model_name='client',
            name='card_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Безналичные'),
        ),
        migrations.AlterField(
            model_name='client',
            name='cash_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Наличные'),
        ),
    ]
