# Generated by Django 5.1.7 on 2025-05-22 21:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_client_balance_client_debt_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='container',
            options={'verbose_name': 'Контейнер', 'verbose_name_plural': 'Контейнеры'},
        ),
        migrations.AddField(
            model_name='container',
            name='notes',
            field=models.CharField(blank=True, max_length=200, verbose_name='Примечания'),
        ),
        migrations.AlterField(
            model_name='car',
            name='days',
            field=models.PositiveIntegerField(default=0, verbose_name='Платные дни'),
        ),
        migrations.AlterField(
            model_name='car',
            name='dekl',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Декларация'),
        ),
        migrations.AlterField(
            model_name='car',
            name='final_storage_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Итоговая цена'),
        ),
        migrations.AlterField(
            model_name='car',
            name='proft',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Наценка'),
        ),
        migrations.AlterField(
            model_name='car',
            name='sklad',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Оплата складу'),
        ),
        migrations.AlterField(
            model_name='car',
            name='ths',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Оплата линиям'),
        ),
        migrations.AlterField(
            model_name='car',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Текущая цена'),
        ),
        migrations.AlterField(
            model_name='container',
            name='days',
            field=models.PositiveIntegerField(default=0, verbose_name='Платные дни'),
        ),
        migrations.AlterField(
            model_name='container',
            name='dekl',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Декларация'),
        ),
        migrations.AlterField(
            model_name='container',
            name='proft',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Наценка'),
        ),
        migrations.AlterField(
            model_name='container',
            name='sklad',
            field=models.DecimalField(decimal_places=2, default=160, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Оплата складу'),
        ),
        migrations.AlterField(
            model_name='container',
            name='ths',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Оплата линиям'),
        ),
    ]
