# Generated by Django 5.2.16 on 2026-08-20 08:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_seed_document_rules'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportBulkUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='transport_docs/bulk/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='Исходный файл')),
                ('status', models.CharField(choices=[('PENDING', 'В очереди'), ('PROCESSING', 'Обрабатывается'), ('DONE', 'Разобран'), ('ERROR', 'Ошибка')], default='PENDING', max_length=12, verbose_name='Статус')),
                ('pages_total', models.PositiveSmallIntegerField(default=0, verbose_name='Страниц в файле')),
                ('result', models.JSONField(blank=True, default=dict, verbose_name='Результат разбора')),
                ('error_message', models.TextField(blank=True, verbose_name='Ошибка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата разбора')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_bulk_uploads', to='core.car', verbose_name='Автомобиль')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_uploads', to='core.transportrequest', verbose_name='Заявка')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Загрузил')),
            ],
            options={
                'verbose_name': 'Пакет одним файлом',
                'verbose_name_plural': 'Пакеты одним файлом',
                'ordering': ['-created_at'],
            },
        ),
    ]
