# Generated by Django 5.1.7 on 2025-05-31 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_container_options_container_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='has_title',
            field=models.BooleanField(default=False, verbose_name='Тайтл у нас'),
        ),
        migrations.AddField(
            model_name='car',
            name='title_notes',
            field=models.TextField(blank=True, verbose_name='Примечания к тайтлу'),
        ),
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.CharField(choices=[('FLOATING', 'В пути'), ('IN_PORT', 'В порту'), ('UNLOADED', 'Разгружен'), ('TRANSFERRED', 'Передан')], max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='container',
            name='number',
            field=models.CharField(max_length=100, unique=True, verbose_name='Номер контейнера'),
        ),
        migrations.AlterField(
            model_name='container',
            name='status',
            field=models.CharField(choices=[('FLOATING', 'В пути'), ('IN_PORT', 'В порту'), ('UNLOADED', 'Разгружен'), ('TRANSFERRED', 'Передан')], default='FLOATING', max_length=50, verbose_name='Статус'),
        ),
    ]
