# Generated by Django 5.2.16 on 2026-08-20 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_transportbulkupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportrequestdocument',
            name='doc_type',
            field=models.CharField(choices=[('TITLE', 'Тайтл'), ('PASSPORT', 'Паспорт'), ('INVOICE', 'Инвойс'), ('SIGNATURE', 'Подпись'), ('PAYMENT_ORDER', 'Платёжка'), ('LETTER_USA', 'Письмо USA'), ('OBLIGATION', 'Обязательство клиента'), ('CONTRACT', 'Договор на перевозку'), ('OTHER', 'Остальное')], default='OTHER', max_length=20, verbose_name='Тип документа'),
        ),
    ]
