# Generated by Django 5.1.7 on 2025-05-31 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_car_has_title_car_title_notes_alter_car_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='title_notes',
            field=models.CharField(blank=True, max_length=200, verbose_name='Примечания к тайтлу'),
        ),
    ]
