# Generated by Django 5.1.7 on 2025-08-07 08:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_car_title_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='default_free_days',
            field=models.PositiveIntegerField(default=0, verbose_name='Бесплатные дни'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='default_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ставка хранения'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='default_storage_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена за склад'),
        ),
        migrations.AlterField(
            model_name='car',
            name='has_title',
            field=models.BooleanField(default=False, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='car',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ставка за сутки'),
        ),
    ]
