# Generated by Django 5.2.16 on 2026-08-20 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_document_rules_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declarationrequest',
            name='declaration_type',
            field=models.CharField(choices=[('TRANSIT', 'Транзит (T1)'), ('EXPORT', 'Экспорт'), ('IMPORT', 'Импорт'), ('REEXPORT', 'Реэкспорт')], default='TRANSIT', max_length=10, verbose_name='Тип декларации'),
        ),
        migrations.AlterField(
            model_name='transportdeclarationgroup',
            name='declaration_type',
            field=models.CharField(choices=[('TRANSIT', 'Транзит (T1)'), ('EXPORT', 'Экспорт'), ('IMPORT', 'Импорт'), ('REEXPORT', 'Реэкспорт')], max_length=10, verbose_name='Тип декларации'),
        ),
        migrations.AlterField(
            model_name='transportdocumentrule',
            name='procedure',
            field=models.CharField(choices=[('TRANSIT', 'Транзит (T1)'), ('EXPORT', 'Экспорт'), ('IMPORT', 'Импорт'), ('REEXPORT', 'Реэкспорт')], max_length=10, verbose_name='Таможенная процедура'),
        ),
        migrations.AlterField(
            model_name='transportrequest',
            name='declaration_type',
            field=models.CharField(blank=True, choices=[('TRANSIT', 'Транзит (T1)'), ('EXPORT', 'Экспорт'), ('IMPORT', 'Импорт'), ('REEXPORT', 'Реэкспорт')], help_text='Тип по умолчанию: одна декларация на все авто заявки. Отдельные декларации на часть машин задаются в карточке заявки.', max_length=10, verbose_name='Требуемая декларация'),
        ),
    ]
