# Generated by Django 5.2.16 on 2026-08-20 16:59

from collections import Counter

from django.db import migrations, models


def fill_country_from_requests(apps, schema_editor):
    """Проставляет страну клиента по странам назначения его прошлых заявок.

    Поле новое, поэтому у всех клиентов оно пустое, а от него зависит
    видимость раздела «Проверка на санкции». Куда клиент реально везёт
    машины, уже известно из ``TransportRequest.destination_country`` —
    берём самое частое значение. Спорные случаи менеджер поправит в админке.
    """
    TransportRequest = apps.get_model("core", "TransportRequest")
    Client = apps.get_model("core", "Client")

    by_client: dict[int, Counter] = {}
    rows = TransportRequest.objects.exclude(destination_country="").values_list("client_id", "destination_country")
    for client_id, country in rows:
        if client_id:
            by_client.setdefault(client_id, Counter())[country] += 1

    for client_id, counter in by_client.items():
        country, _ = counter.most_common(1)[0]
        Client.objects.filter(pk=client_id, country="").update(country=country)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_declaration_type_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='country',
            field=models.CharField(blank=True, choices=[('BY', 'Беларусь'), ('MD', 'Молдова'), ('UA', 'Украина'), ('KZ', 'Казахстан'), ('KG', 'Киргизия'), ('UZ', 'Узбекистан'), ('AM', 'Армения'), ('AZ', 'Азербайджан'), ('GE', 'Грузия'), ('LT', 'Литва'), ('LV', 'Латвия'), ('PL', 'Польша'), ('OTHER', 'Другая')], default='', help_text='Определяет разделы кабинета: «Проверка на санкции» видна клиентам из Беларуси.', max_length=5, verbose_name='Страна клиента'),
        ),
        migrations.RunPython(fill_country_from_requests, migrations.RunPython.noop),
    ]
