# Generated by Django 5.1.7 on 2025-08-07 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_warehouse_default_free_days_warehouse_default_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='default_free_days',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='default_rate',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='default_storage_fee',
        ),
        migrations.AddField(
            model_name='warehouse',
            name='additional_expenses',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Доп.расходы'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='default_unloading_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена за разгрузку'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='delivery_to_warehouse',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Доставка до склада'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='documents_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Документы'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='export_declaration',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Экспортная декл.'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='loading_on_trawl',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Погрузка на трал'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='transfer_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Плата за передачу'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='transit_declaration',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Транзитная декл.'),
        ),
    ]
