# Generated by Django 5.2.16 on 2026-08-24 06:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0025_client_country"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="transportrequest",
            index=models.Index(fields=["warehouse_state", "-created_at"], name="transreq_whstate_idx"),
        ),
    ]
