# Generated by Django 5.2.16 on 2026-08-24 19:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_transportrequest_transreq_whstate_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='VinCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(db_index=True, max_length=17, unique=True, verbose_name='VIN')),
                ('length_ok', models.BooleanField(default=False, verbose_name='17 символов')),
                ('checksum_ok', models.BooleanField(default=False, verbose_name='Контрольная цифра сходится')),
                ('is_north_american', models.BooleanField(default=False, help_text='Начинается с 1-5 — для таких контрольная цифра обязана сходиться.', verbose_name='Североамериканский VIN')),
                ('nhtsa_ok', models.BooleanField(default=False, verbose_name='NHTSA распознал VIN')),
                ('nhtsa_make', models.CharField(blank=True, default='', max_length=100, verbose_name='Марка (NHTSA)')),
                ('nhtsa_model', models.CharField(blank=True, default='', max_length=100, verbose_name='Модель (NHTSA)')),
                ('nhtsa_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Год (NHTSA)')),
                ('error_text', models.CharField(blank=True, default='', max_length=255, verbose_name='Ответ NHTSA')),
                ('checked_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Проверено')),
            ],
            options={
                'verbose_name': 'Проверка VIN',
                'verbose_name_plural': 'Проверки VIN',
                'ordering': ('-checked_at',),
            },
        ),
        migrations.AddField(
            model_name='container',
            name='data_audit_checked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Сверка выполнена'),
        ),
        migrations.AddField(
            model_name='container',
            name='data_audit_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Находок сверки'),
        ),
        migrations.AddField(
            model_name='container',
            name='data_audit_level',
            field=models.CharField(choices=[('ok', 'Расхождений нет'), ('warn', 'Есть замечания'), ('error', 'Есть расхождения')], db_index=True, default='ok', max_length=10, verbose_name='Сверка данных'),
        ),
    ]
