# Generated by Django 5.1.7 on 2025-08-07 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_remove_car_sklad_car_delivery_fee_car_docs_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='complex_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Комплекс'),
        ),
    ]
