# Generated by Django 5.2.16 on 2026-08-26 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_vin_check_and_container_audit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportCmr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='Графы CMR')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cmr_documents', to='core.car', verbose_name='Автомобиль')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cmr_documents', to='core.transportrequest', verbose_name='Заявка')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кто правил')),
            ],
            options={
                'verbose_name': 'CMR заявки',
                'verbose_name_plural': 'CMR заявок',
                'indexes': [models.Index(fields=['request'], name='cmr_request_idx')],
                'constraints': [models.UniqueConstraint(fields=('request', 'car'), name='uniq_cmr_request_car')],
            },
        ),
    ]
