# Generated by Django 5.1.7 on 2025-08-07 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_warehouse_complex_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='default_free_days',
            field=models.PositiveIntegerField(default=0, verbose_name='Бесплатные дни'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='default_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ставка за сутки'),
        ),
    ]
