# Generated by Django 5.1.7 on 2025-08-07 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_warehouse_default_free_days_warehouse_default_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='dekl',
        ),
        migrations.RemoveField(
            model_name='car',
            name='delivery_fee',
        ),
        migrations.RemoveField(
            model_name='car',
            name='docs_fee',
        ),
        migrations.RemoveField(
            model_name='car',
            name='extra_costs',
        ),
        migrations.RemoveField(
            model_name='car',
            name='loading_fee',
        ),
        migrations.RemoveField(
            model_name='car',
            name='proft',
        ),
        migrations.RemoveField(
            model_name='car',
            name='ths',
        ),
        migrations.RemoveField(
            model_name='car',
            name='unload_fee',
        ),
        migrations.AddField(
            model_name='car',
            name='additional_expenses',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Доп.расходы'),
        ),
        migrations.AddField(
            model_name='car',
            name='delivery_to_warehouse',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Доставка до склада'),
        ),
        migrations.AddField(
            model_name='car',
            name='documents_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Документы'),
        ),
        migrations.AddField(
            model_name='car',
            name='loading_on_trawl',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Погрузка на трал'),
        ),
        migrations.AddField(
            model_name='car',
            name='unloading_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена за разгрузку'),
        ),
        migrations.AlterField(
            model_name='car',
            name='export_declaration',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Экспортная декл.'),
        ),
        migrations.AlterField(
            model_name='car',
            name='has_title',
            field=models.BooleanField(default=False, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='car',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=10, verbose_name='Ставка за сутки'),
        ),
        migrations.AlterField(
            model_name='car',
            name='transfer_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Плата за передачу'),
        ),
        migrations.AlterField(
            model_name='car',
            name='transit_declaration',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Транзитная декл.'),
        ),
    ]
