# Generated by Django 5.2.16 on 2026-09-07 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_vincheck_nhtsa_vehicle_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodelimage',
            name='year',
            field=models.PositiveIntegerField(blank=True, help_text='Год поколения: картинка для авто этой марки с этим и более поздним годом, пока нет фото новее. Пусто = любой год.', null=True, verbose_name='Год'),
        ),
    ]
