# Generated by Django 5.1.7 on 2025-08-07 14:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_remove_car_dekl_remove_car_delivery_fee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='additional_expenses',
        ),
        migrations.RemoveField(
            model_name='car',
            name='delivery_to_warehouse',
        ),
        migrations.RemoveField(
            model_name='car',
            name='documents_fee',
        ),
        migrations.RemoveField(
            model_name='car',
            name='loading_on_trawl',
        ),
        migrations.RemoveField(
            model_name='car',
            name='unloading_fee',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='complex_price',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='default_free_days',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='default_rate',
        ),
        migrations.AddField(
            model_name='car',
            name='dekl',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Декларация'),
        ),
        migrations.AddField(
            model_name='car',
            name='delivery_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Доставка до склада'),
        ),
        migrations.AddField(
            model_name='car',
            name='docs_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Документы'),
        ),
        migrations.AddField(
            model_name='car',
            name='extra_costs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Доп.расходы'),
        ),
        migrations.AddField(
            model_name='car',
            name='loading_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Погрузка на трал'),
        ),
        migrations.AddField(
            model_name='car',
            name='proft',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Наценка'),
        ),
        migrations.AddField(
            model_name='car',
            name='ths',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Оплата линиям'),
        ),
        migrations.AddField(
            model_name='car',
            name='unload_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена за разгрузку'),
        ),
        migrations.AlterField(
            model_name='car',
            name='export_declaration',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Экспортная декл.'),
        ),
        migrations.AlterField(
            model_name='car',
            name='has_title',
            field=models.BooleanField(default=False, verbose_name='Тайтл у нас'),
        ),
        migrations.AlterField(
            model_name='car',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ставка за сутки'),
        ),
        migrations.AlterField(
            model_name='car',
            name='transfer_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Плата за передачу'),
        ),
        migrations.AlterField(
            model_name='car',
            name='transit_declaration',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Транзитная декл.'),
        ),
    ]
