# Generated by Django 5.2.16 on 2026-09-28 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_carmodelimage_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='vehicle_type',
            field=models.CharField(choices=[('SEDAN', 'Легковой'), ('CROSSOVER', 'Кроссовер'), ('SUV', 'Джип'), ('PICKUP', 'Пикап'), ('NEW_CAR', 'Новая машина'), ('MOTO', 'Мотоцикл'), ('BIG_MOTO', 'Большой мотоцикл'), ('ATV', 'Квадроцикл/Багги'), ('BOAT', 'Лодка'), ('JETSKI', 'Гидроцикл'), ('SNOWMOBILE', 'Снегоход'), ('RV', 'Автодом (RV)'), ('CONSTRUCTION', 'Стр. техника')], default='SEDAN', max_length=20, verbose_name='Тип ТС'),
        ),
        migrations.AlterField(
            model_name='clienttariffrate',
            name='vehicle_type',
            field=models.CharField(choices=[('SEDAN', 'Легковой'), ('CROSSOVER', 'Кроссовер'), ('SUV', 'Джип'), ('PICKUP', 'Пикап'), ('NEW_CAR', 'Новая машина'), ('MOTO', 'Мотоцикл'), ('BIG_MOTO', 'Большой мотоцикл'), ('ATV', 'Квадроцикл/Багги'), ('BOAT', 'Лодка'), ('JETSKI', 'Гидроцикл'), ('SNOWMOBILE', 'Снегоход'), ('RV', 'Автодом (RV)'), ('CONSTRUCTION', 'Стр. техника')], max_length=20, verbose_name='Тип ТС'),
        ),
        migrations.AlterField(
            model_name='linethscoefficient',
            name='vehicle_type',
            field=models.CharField(choices=[('SEDAN', 'Легковой'), ('CROSSOVER', 'Кроссовер'), ('SUV', 'Джип'), ('PICKUP', 'Пикап'), ('NEW_CAR', 'Новая машина'), ('MOTO', 'Мотоцикл'), ('BIG_MOTO', 'Большой мотоцикл'), ('ATV', 'Квадроцикл/Багги'), ('BOAT', 'Лодка'), ('JETSKI', 'Гидроцикл'), ('SNOWMOBILE', 'Снегоход'), ('RV', 'Автодом (RV)'), ('CONSTRUCTION', 'Стр. техника')], max_length=20, verbose_name='Тип ТС'),
        ),
    ]
