# Generated by Django 5.1.7 on 2025-08-07 14:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_remove_car_additional_expenses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='additional_expenses',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Дополнительные расходы'),
        ),
        migrations.AddField(
            model_name='car',
            name='auction_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Аукционный сбор'),
        ),
        migrations.AddField(
            model_name='car',
            name='broker_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Брокерский сбор'),
        ),
        migrations.AddField(
            model_name='car',
            name='ocean_freight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Океанский фрахт'),
        ),
        migrations.AddField(
            model_name='car',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='car',
            name='transport_kz',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Транспорт КЗ'),
        ),
        migrations.AddField(
            model_name='car',
            name='transport_usa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Транспорт США'),
        ),
    ]
