# Generated by Django 5.1.7 on 2025-08-07 16:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_car_additional_expenses_car_auction_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='free_days',
            field=models.PositiveIntegerField(default=0, verbose_name='Бесплатные дни'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ставка за сутки'),
        ),
    ]
