# Generated by Django 5.1.7 on 2025-08-07 16:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_warehouse_free_days_warehouse_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='complex_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Комплекс'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='complex_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Комплекс'),
        ),
    ]
