# Generated by Django 5.2.16 on 2026-10-02 13:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0033_alter_transportrequestdocument_doc_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CarStatusHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(max_length=20, verbose_name="Статус")),
                (
                    "previous_status",
                    models.CharField(blank=True, default="", max_length=20, verbose_name="Предыдущий статус"),
                ),
                ("changed_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Когда")),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Админка / пользователь"),
                            ("SIGNAL", "Автоматически (сигнал)"),
                            ("IMPORT", "Импорт / миграция данных"),
                        ],
                        default="SIGNAL",
                        max_length=10,
                        verbose_name="Источник",
                    ),
                ),
                ("note", models.CharField(blank=True, default="", max_length=255, verbose_name="Примечание")),
            ],
            options={
                "verbose_name": "История статуса авто",
                "verbose_name_plural": "История статусов авто",
                "ordering": ["-changed_at", "-id"],
            },
        ),
        migrations.AddField(
            model_name="clientuser",
            name="notification_prefs",
            field=models.JSONField(blank=True, default=dict, verbose_name="Настройки уведомлений"),
        ),
        migrations.AddField(
            model_name="warehouse",
            name="storage_day_policy",
            field=models.CharField(
                choices=[
                    ("CALENDAR", "Календарные дни"),
                    ("BUSINESS", "Рабочие дни (пн–пт)"),
                    ("BUSINESS_LT", "Рабочие дни без праздников Литвы"),
                ],
                default="CALENDAR",
                help_text="Календарные дни — как раньше. Рабочие дни — суббота/воскресенье (и праздники Литвы, если выбрано) не считаются днями хранения. Применяется ко всем авто склада при пересчёте.",
                max_length=15,
                verbose_name="Учёт дней хранения",
            ),
        ),
        migrations.AlterField(
            model_name="notificationlog",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("PLANNED", "Планируемая разгрузка"),
                    ("UNLOADED", "Разгрузка выполнена"),
                    ("CAR_UNLOADED", "Разгрузка ТС (без контейнера)"),
                    ("REQUEST_MESSAGE", "Сообщение по заявке на автовоз"),
                    ("REQUEST_DOCS", "Запрос документов по заявке"),
                    ("PHOTOS_READY", "Фото готовы"),
                    ("INVOICE_ISSUED", "Инвойс выставлен"),
                    ("REQUEST_STATUS", "Заявка сменила статус"),
                    ("CAR_TRANSFERRED", "Авто передано"),
                    ("INVOICE_DUE_SOON", "Напоминание о сроке оплаты"),
                    ("INVOICE_OVERDUE", "Инвойс просрочен"),
                ],
                max_length=20,
                verbose_name="Тип уведомления",
            ),
        ),
        migrations.AddIndex(
            model_name="banktransaction",
            index=models.Index(
                condition=models.Q(
                    ("matched_invoice__isnull", True),
                    ("matched_transaction__isnull", True),
                    ("reconciliation_skipped", False),
                ),
                fields=["created_at"],
                name="bt_unreconciled_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="car",
            index=models.Index(fields=["status", "unload_date"], name="car_status_unload_idx"),
        ),
        migrations.AddIndex(
            model_name="car",
            index=models.Index(fields=["client", "unload_date"], name="car_client_unload_idx"),
        ),
        migrations.AddIndex(
            model_name="transportrequest",
            index=models.Index(fields=["client", "status", "-created_at"], name="transreq_client_status_idx"),
        ),
        migrations.AddField(
            model_name="carstatushistory",
            name="car",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="status_history",
                to="core.car",
                verbose_name="Авто",
            ),
        ),
        migrations.AddIndex(
            model_name="carstatushistory",
            index=models.Index(fields=["car", "changed_at"], name="car_status_hist_car_at_idx"),
        ),
    ]
