# Generated by Django 5.1.7 on 2025-08-08 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_car_complex_fee_warehouse_complex_fee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': 'Автомобиль', 'verbose_name_plural': 'Автомобили'},
        ),
        migrations.RemoveField(
            model_name='car',
            name='final_storage_cost',
        ),
        migrations.RemoveField(
            model_name='car',
            name='warehouse_days',
        ),
        migrations.AlterField(
            model_name='car',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Общая цена'),
        ),
    ]
