# Generated by Django 5.2.16 on 2026-10-02 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_improvement_plan_2026_10'),
    ]

    operations = [
        migrations.AddField(
            model_name='newinvoice',
            name='credited_invoice',
            field=models.ForeignKey(blank=True, help_text='Исходный счёт, долг по которому уменьшает эта кредит-нота', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='core.newinvoice', verbose_name='Счёт кредит-ноты'),
        ),
    ]
