# Generated by Django 5.1.7 on 2025-08-08 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_alter_car_options_remove_car_final_storage_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='current_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Текущая цена'),
        ),
        migrations.AlterField(
            model_name='car',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Итоговая цена'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['vin'], name='core_car_vin_60390e_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['status'], name='core_car_status_f5096f_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['unload_date', 'transfer_date'], name='core_car_unload__0b4c2c_idx'),
        ),
    ]
