# Generated by Django 5.2.16 on 2026-10-02 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_credit_note_invoice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banktransaction',
            options={'ordering': ['-created_at'], 'verbose_name': 'Банковская транзакция', 'verbose_name_plural': 'Банк. транзакции'},
        ),
    ]
