# Generated by Django 5.1.7 on 2025-08-08 14:33

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_car_current_price_alter_car_total_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='proft',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('20.00'), max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Наценка'),
        ),
    ]
