# Generated by Django 5.1.7 on 2025-08-09 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_alter_car_proft'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['is_outgoing', 'paid'], name='core_invoic_is_outg_4c44cf_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['invoice', 'payer', 'date'], name='core_paymen_invoice_bdb046_idx'),
        ),
    ]
