# Generated by Django 5.1.7 on 2025-08-10 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_invoice_core_invoic_is_outg_4c44cf_idx_and_more'),
    ]

    operations = [
        # Поле 'invoice' уже было удалено ранее
        # Эта миграция оставлена пустой для совместимости
    ]

