# Generated by Django 5.1.7 on 2025-08-10 22:52
#
# ВАЖНО: на Postgres эта миграция ДАВНО применена в production.
# На SQLite (локальные/CI-тесты) она становится no-op, потому что
# `DROP COLUMN IF EXISTS` не поддерживается SQLite, а колонки уже отсутствуют
# в model state (они удалены ещё в ранних миграциях).

from django.db import migrations


def drop_legacy_payment_columns(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return
    schema_editor.execute(
        """
        ALTER TABLE core_payment DROP COLUMN IF EXISTS payer_id;
        ALTER TABLE core_payment DROP COLUMN IF EXISTS recipient;
        ALTER TABLE core_payment DROP COLUMN IF EXISTS from_balance;
        ALTER TABLE core_payment DROP COLUMN IF EXISTS from_cash_balance;
        """
    )


def restore_legacy_payment_columns(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return
    schema_editor.execute(
        """
        ALTER TABLE core_payment ADD COLUMN IF NOT EXISTS payer_id bigint NULL;
        ALTER TABLE core_payment ADD COLUMN IF NOT EXISTS recipient character varying(100) NULL;
        ALTER TABLE core_payment ADD COLUMN IF NOT EXISTS from_balance boolean NOT NULL DEFAULT false;
        ALTER TABLE core_payment ADD COLUMN IF NOT EXISTS from_cash_balance boolean NOT NULL DEFAULT false;
        """
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_add_missing_old_balance_fields'),
    ]

    operations = [
        migrations.RunPython(
            drop_legacy_payment_columns,
            reverse_code=restore_legacy_payment_columns,
        ),
    ]
