# Generated by Django 5.1.7 on 2025-08-10 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_add_missing_old_balance_fields'),
    ]

    operations = [
        # Удаляем старые поля напрямую через SQL
        migrations.RunSQL(
            sql="""
                ALTER TABLE core_payment DROP COLUMN IF EXISTS payer_id;
                ALTER TABLE core_payment DROP COLUMN IF EXISTS recipient;
                ALTER TABLE core_payment DROP COLUMN IF EXISTS from_balance;
                ALTER TABLE core_payment DROP COLUMN IF EXISTS from_cash_balance;
            """,
            reverse_sql="""
                ALTER TABLE core_payment ADD COLUMN payer_id bigint NULL;
                ALTER TABLE core_payment ADD COLUMN recipient character varying(100) NULL;
                ALTER TABLE core_payment ADD COLUMN from_balance boolean NOT NULL DEFAULT false;
                ALTER TABLE core_payment ADD COLUMN from_cash_balance boolean NOT NULL DEFAULT false;
            """
        ),
    ]
