# Generated by Django 5.1.7 on 2025-08-12 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0041_remove_old_payment_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='balance',
            options={'verbose_name': 'Баланс', 'verbose_name_plural': 'Балансы'},
        ),
        migrations.AlterModelOptions(
            name='balancetransaction',
            options={'verbose_name': 'Транзакция баланса', 'verbose_name_plural': 'Транзакции балансов'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Компания', 'verbose_name_plural': 'Компании'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-date'], 'verbose_name': 'Платеж', 'verbose_name_plural': 'Платежи'},
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='core_paymen_invoice_bdb046_idx',
        ),
        migrations.RenameIndex(
            model_name='balance',
            new_name='core_balanc_content_a59033_idx',
            old_name='core_balanc_content_8c8c8c_idx',
        ),
        migrations.RenameIndex(
            model_name='balance',
            new_name='core_balanc_balance_2a7888_idx',
            old_name='core_balanc_balance_8c8c8c_idx',
        ),
        migrations.RenameIndex(
            model_name='balancetransaction',
            new_name='core_balanc_sender__eea668_idx',
            old_name='core_balanc_sender__8c8c8c_idx',
        ),
        migrations.RenameIndex(
            model_name='balancetransaction',
            new_name='core_balanc_recipie_cd552f_idx',
            old_name='core_balanc_recipie_8c8c8c_idx',
        ),
        migrations.RenameIndex(
            model_name='balancetransaction',
            new_name='core_balanc_transac_e9d1b9_idx',
            old_name='core_balanc_transac_8c8c8c_idx',
        ),
        migrations.RenameIndex(
            model_name='balancetransaction',
            new_name='core_balanc_created_d20839_idx',
            old_name='core_balanc_created_8c8c8c_idx',
        ),
    ]
