# Generated by Django 5.1.7 on 2025-08-12 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0042_alter_balance_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='from_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments_sent', to='core.client'),
        ),
        migrations.AddField(
            model_name='payment',
            name='from_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments_sent', to='core.company'),
        ),
        migrations.AddField(
            model_name='payment',
            name='from_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments_sent', to='core.line'),
        ),
        migrations.AddField(
            model_name='payment',
            name='from_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments_sent', to='core.warehouse'),
        ),
        migrations.AddField(
            model_name='payment',
            name='to_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments_received', to='core.client'),
        ),
        migrations.AddField(
            model_name='payment',
            name='to_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments_received', to='core.company'),
        ),
        migrations.AddField(
            model_name='payment',
            name='to_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments_received', to='core.line'),
        ),
        migrations.AddField(
            model_name='payment',
            name='to_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments_received', to='core.warehouse'),
        ),
    ]
