# Generated by Django 5.1.7 on 2025-08-12 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_add_new_payment_fields'),
    ]

    operations = [
        # Убираем все операции удаления полей, так как они могут не существовать
        # migrations.RemoveField(...) - все эти операции убираем
        
        # Убираем все операции добавления полей в другие модели, так как они уже существуют
        # Убираем все операции AlterField и CreateIndex
    ]
