# Generated by Django 5.1.7 on 2025-08-27 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_remove_balance_type_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='from_entity_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ID отправителя'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='from_entity_type',
            field=models.CharField(choices=[('CLIENT', 'Клиент'), ('WAREHOUSE', 'Склад'), ('LINE', 'Линия'), ('COMPANY', 'Компания')], default='COMPANY', max_length=20, verbose_name='Тип отправителя'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='to_entity_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ID получателя'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='to_entity_type',
            field=models.CharField(choices=[('CLIENT', 'Клиент'), ('WAREHOUSE', 'Склад'), ('LINE', 'Линия'), ('COMPANY', 'Компания')], default='CLIENT', max_length=20, verbose_name='Тип получателя'),
        ),
    ]
