# Generated by Django 5.1.7 on 2025-09-16 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_add_services_and_carriers'),
        ('core', '0057_fix_migration_state'),
    ]

    operations = [
    ]
