# Generated by Django 5.1.7 on 2025-09-30 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_add_deleted_car_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarrierService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название услуги')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('default_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена по умолчанию')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Услуга перевозчика',
                'verbose_name_plural': 'Услуги перевозчиков',
            },
        ),
        migrations.CreateModel(
            name='CarService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('LINE', 'Линия'), ('CARRIER', 'Перевозчик'), ('WAREHOUSE', 'Склад')], max_length=20, verbose_name='Тип поставщика')),
                ('service_id', models.PositiveIntegerField(verbose_name='ID услуги')),
                ('custom_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Индивидуальная цена')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Услуга автомобиля',
                'verbose_name_plural': 'Услуги автомобилей',
            },
        ),
        migrations.CreateModel(
            name='LineService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название услуги')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('default_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена по умолчанию')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Услуга линии',
                'verbose_name_plural': 'Услуги линий',
            },
        ),
        migrations.CreateModel(
            name='WarehouseService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название услуги')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('default_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена по умолчанию')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Услуга склада',
                'verbose_name_plural': 'Услуги складов',
            },
        ),
        migrations.AlterUniqueTogether(
            name='balance',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='balance',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='balancetransaction',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='balancetransaction',
            name='recipient_content_type',
        ),
        migrations.RemoveField(
            model_name='balancetransaction',
            name='sender_content_type',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='balance_transaction',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='from_balance',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='from_cash_balance',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payer',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='recipient_balance_type',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='recipient_content_type',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='recipient_object_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='sender_balance_type',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='sender_content_type',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='sender_object_id',
        ),
        migrations.AddField(
            model_name='car',
            name='carrier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.carrier', verbose_name='Перевозчик'),
        ),
        migrations.AddField(
            model_name='car',
            name='line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.line', verbose_name='Линия'),
        ),
        migrations.AddField(
            model_name='client',
            name='invoice_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Инвойс-баланс'),
        ),
        migrations.AddField(
            model_name='line',
            name='card_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Безнал'),
        ),
        migrations.AddField(
            model_name='line',
            name='cash_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Наличные'),
        ),
        migrations.AddField(
            model_name='line',
            name='invoice_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Инвойс-баланс'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='card_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Безнал'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='cash_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Наличные'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='invoice_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Инвойс-баланс'),
        ),
        migrations.AlterField(
            model_name='car',
            name='container',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='container_cars', to='core.container', verbose_name='Контейнер'),
        ),
        migrations.AlterField(
            model_name='client',
            name='card_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Безнал'),
        ),
        migrations.AlterField(
            model_name='client',
            name='cash_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Наличные'),
        ),
        migrations.AlterField(
            model_name='client',
            name='debt',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Долг/Переплата (устарело)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(default='Caromoto Lithuania', max_length=100, verbose_name='Название компании'),
        ),
        migrations.AlterField(
            model_name='company',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.client', verbose_name='Клиент (устарело)'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='from_entity_type',
            field=models.CharField(choices=[('CLIENT', 'Клиент'), ('WAREHOUSE', 'Склад'), ('LINE', 'Линия'), ('CARRIER', 'Перевозчик'), ('COMPANY', 'Компания')], default='COMPANY', max_length=20, verbose_name='Тип отправителя'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='service_type',
            field=models.CharField(choices=[('WAREHOUSE_SERVICES', 'Услуги склада'), ('LINE_SERVICES', 'Услуги линий'), ('CARRIER_SERVICES', 'Услуги перевозчиков'), ('TRANSPORT_SERVICES', 'Транспортные услуги'), ('OTHER_SERVICES', 'Прочие услуги')], default='WAREHOUSE_SERVICES', max_length=20, verbose_name='Тип услуг'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='to_entity_type',
            field=models.CharField(choices=[('CLIENT', 'Клиент'), ('WAREHOUSE', 'Склад'), ('LINE', 'Линия'), ('CARRIER', 'Перевозчик'), ('COMPANY', 'Компания')], default='CLIENT', max_length=20, verbose_name='Тип получателя'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.warehouse', verbose_name='Склад (устарело)'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, verbose_name='Создано пользователем'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='description',
            field=models.TextField(blank=True, help_text="Например: 'Пополнение баланса', 'Оплата инвойса №123', 'Перевод средств'", verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.invoice', verbose_name='Инвойс'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('CASH', 'Наличные (пополнение/списание наличного баланса)'), ('CARD', 'Безналичные (пополнение/списание безналичного баланса)'), ('INVOICE', 'Инвойс (оплата счета)')], max_length=20, verbose_name='Тип платежа'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['client', 'status'], name='core_car_client__4e569e_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['warehouse', 'status'], name='core_car_warehou_58311a_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['line'], name='core_car_line_id_a34876_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['carrier'], name='core_car_carrier_226c9f_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['container'], name='core_car_contain_651d23_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['unload_date'], name='core_car_unload__7c8908_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['transfer_date'], name='core_car_transfe_540531_idx'),
        ),
        migrations.AddIndex(
            model_name='container',
            index=models.Index(fields=['status'], name='core_contai_status_d75646_idx'),
        ),
        migrations.AddIndex(
            model_name='container',
            index=models.Index(fields=['client', 'status'], name='core_contai_client__23c254_idx'),
        ),
        migrations.AddIndex(
            model_name='container',
            index=models.Index(fields=['warehouse', 'status'], name='core_contai_warehou_1c61fc_idx'),
        ),
        migrations.AddIndex(
            model_name='container',
            index=models.Index(fields=['line'], name='core_contai_line_id_45f9b3_idx'),
        ),
        migrations.AddIndex(
            model_name='container',
            index=models.Index(fields=['eta'], name='core_contai_eta_da7db0_idx'),
        ),
        migrations.AddIndex(
            model_name='container',
            index=models.Index(fields=['unload_date'], name='core_contai_unload__2b7208_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['from_entity_type', 'from_entity_id'], name='core_invoic_from_en_0a3e5a_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['to_entity_type', 'to_entity_id'], name='core_invoic_to_enti_daa6f0_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['issue_date', 'paid'], name='core_invoic_issue_d_014398_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['service_type'], name='core_invoic_service_bd1cd6_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['client'], name='core_invoic_client__f81038_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['warehouse'], name='core_invoic_warehou_63be2c_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['invoice', 'date'], name='core_paymen_invoice_2af4e6_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['from_client'], name='core_paymen_from_cl_36fe25_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['from_warehouse'], name='core_paymen_from_wa_707ee8_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['from_line'], name='core_paymen_from_li_fc9261_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['from_company'], name='core_paymen_from_co_65332b_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['to_client'], name='core_paymen_to_clie_4fd779_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['to_warehouse'], name='core_paymen_to_ware_7b6336_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['to_line'], name='core_paymen_to_line_1b9990_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['to_company'], name='core_paymen_to_comp_e64372_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_type'], name='core_paymen_payment_7da942_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['date', 'payment_type'], name='core_paymen_date_ef504c_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['from_client', 'date'], name='core_paymen_from_cl_601fa1_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['to_client', 'date'], name='core_paymen_to_clie_ccc585_idx'),
        ),
        migrations.AddField(
            model_name='carrierservice',
            name='carrier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='core.carrier', verbose_name='Перевозчик'),
        ),
        migrations.AddField(
            model_name='carservice',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_services', to='core.car', verbose_name='Автомобиль'),
        ),
        migrations.AddField(
            model_name='lineservice',
            name='line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='core.line', verbose_name='Линия'),
        ),
        migrations.AddField(
            model_name='warehouseservice',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='core.warehouse', verbose_name='Склад'),
        ),
        migrations.DeleteModel(
            name='Balance',
        ),
        migrations.DeleteModel(
            name='BalanceTransaction',
        ),
        migrations.AddIndex(
            model_name='carservice',
            index=models.Index(fields=['car', 'service_type'], name='core_carser_car_id_f57985_idx'),
        ),
        migrations.AddIndex(
            model_name='carservice',
            index=models.Index(fields=['service_type', 'service_id'], name='core_carser_service_d56ee5_idx'),
        ),
        migrations.AddIndex(
            model_name='carservice',
            index=models.Index(fields=['car'], name='core_carser_car_id_c6d390_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='carservice',
            unique_together={('car', 'service_type', 'service_id')},
        ),
    ]
