# Generated by Django 5.1.7 on 2025-09-30 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_newinvoice_invoiceitem_transaction_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Invoice',
            new_name='InvoiceOLD',
        ),
        migrations.RenameModel(
            old_name='Payment',
            new_name='PaymentOLD',
        ),
        migrations.AlterModelOptions(
            name='invoiceold',
            options={'verbose_name': 'Инвойс (старая система)', 'verbose_name_plural': 'Инвойсы (старая система)'},
        ),
        migrations.AlterModelOptions(
            name='paymentold',
            options={'ordering': ['-date'], 'verbose_name': 'Платеж (старая система)', 'verbose_name_plural': 'Платежи (старая система)'},
        ),
        migrations.AlterModelTable(
            name='invoiceold',
            table='core_invoice',
        ),
        migrations.AlterModelTable(
            name='paymentold',
            table='core_payment',
        ),
    ]
