# Generated by Django 5.1.7 on 2025-09-30 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_rename_invoice_invoiceold_rename_payment_paymentold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Положительный = переплата, отрицательный = долг', max_digits=15, verbose_name='Баланс'),
        ),
        migrations.AddField(
            model_name='client',
            name='balance_updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлен'),
        ),
        migrations.AlterField(
            model_name='client',
            name='card_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Безнал (старая)'),
        ),
        migrations.AlterField(
            model_name='client',
            name='cash_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Наличные (старая)'),
        ),
        migrations.AlterField(
            model_name='client',
            name='debt',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Долг (старая)'),
        ),
        migrations.AlterField(
            model_name='client',
            name='invoice_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Инвойс-баланс (старая)'),
        ),
    ]
