# Generated by Django 5.1.7 on 2025-09-30 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_client_balance_client_balance_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newinvoice',
            name='due_date',
            field=models.DateField(blank=True, help_text='Дата, до которой должен быть оплачен инвойс (автоматически +14 дней)', null=True, verbose_name='Срок оплаты'),
        ),
    ]
