# Generated by Django 5.1.7 on 2025-09-30 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_alter_newinvoice_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newinvoice',
            name='issuer',
        ),
        migrations.AddField(
            model_name='newinvoice',
            name='issuer_carrier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issued_invoices_new', to='core.carrier', verbose_name='Перевозчик-выставитель'),
        ),
        migrations.AddField(
            model_name='newinvoice',
            name='issuer_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issued_invoices_new', to='core.company', verbose_name='Компания-выставитель'),
        ),
        migrations.AddField(
            model_name='newinvoice',
            name='issuer_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issued_invoices_new', to='core.line', verbose_name='Линия-выставитель'),
        ),
        migrations.AddField(
            model_name='newinvoice',
            name='issuer_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issued_invoices_new', to='core.warehouse', verbose_name='Склад-выставитель'),
        ),
    ]
