# Generated by Django 5.1.7 on 2025-09-30 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_remove_newinvoice_issuer_newinvoice_issuer_carrier_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='newinvoice',
            name='recipient_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='received_invoices_new', to='core.company', verbose_name='Компания-получатель'),
        ),
        migrations.AddIndex(
            model_name='newinvoice',
            index=models.Index(fields=['recipient_company', 'status'], name='core_newinv_recipie_9a9bdf_idx'),
        ),
        migrations.AddIndex(
            model_name='newinvoice',
            index=models.Index(fields=['issuer_company', 'status'], name='core_newinv_issuer__291c4d_idx'),
        ),
        migrations.AddIndex(
            model_name='newinvoice',
            index=models.Index(fields=['issuer_warehouse', 'status'], name='core_newinv_issuer__97c7c2_idx'),
        ),
        migrations.AddIndex(
            model_name='newinvoice',
            index=models.Index(fields=['issuer_line', 'status'], name='core_newinv_issuer__463320_idx'),
        ),
        migrations.AddIndex(
            model_name='newinvoice',
            index=models.Index(fields=['issuer_carrier', 'status'], name='core_newinv_issuer__9581ab_idx'),
        ),
    ]
