# Generated by Django 5.1.7 on 2025-09-30 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_newinvoice_recipient_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newinvoice',
            name='cars',
            field=models.ManyToManyField(blank=True, help_text='Выберите автомобили - позиции создадутся автоматически из их услуг', related_name='invoices_new', to='core.car', verbose_name='Автомобили'),
        ),
    ]
