# Generated by Django 5.1.7 on 2025-09-30 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_newinvoice_cars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newinvoice',
            name='cars',
            field=models.ManyToManyField(blank=True, help_text='Выберите автомобили - позиции создадутся автоматически из их услуг', related_name='invoices_new', to='core.car', verbose_name='Выбранные автомобили'),
        ),
    ]
