# Generated by Django 5.1.7 on 2025-09-30 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_alter_newinvoice_issuer_carrier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newinvoice',
            name='issuer_carrier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issued_invoices_new', to='core.carrier', verbose_name='Перевозчик-выставитель'),
        ),
        migrations.AlterField(
            model_name='newinvoice',
            name='issuer_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issued_invoices_new', to='core.company', verbose_name='Компания-выставитель'),
        ),
        migrations.AlterField(
            model_name='newinvoice',
            name='issuer_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issued_invoices_new', to='core.line', verbose_name='Линия-выставитель'),
        ),
        migrations.AlterField(
            model_name='newinvoice',
            name='issuer_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issued_invoices_new', to='core.warehouse', verbose_name='Склад-выставитель'),
        ),
        migrations.AlterField(
            model_name='newinvoice',
            name='recipient_carrier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='received_invoices_new', to='core.carrier', verbose_name='Перевозчик-получатель'),
        ),
        migrations.AlterField(
            model_name='newinvoice',
            name='recipient_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='received_invoices_new', to='core.client', verbose_name='Клиент-получатель'),
        ),
        migrations.AlterField(
            model_name='newinvoice',
            name='recipient_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='received_invoices_new', to='core.company', verbose_name='Компания-получатель'),
        ),
        migrations.AlterField(
            model_name='newinvoice',
            name='recipient_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='received_invoices_new', to='core.line', verbose_name='Линия-получатель'),
        ),
        migrations.AlterField(
            model_name='newinvoice',
            name='recipient_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='received_invoices_new', to='core.warehouse', verbose_name='Склад-получатель'),
        ),
    ]
