# Generated by Django 5.1.7 on 2025-10-08 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_contactmessage_aichat_carphoto_clientuser_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContainerPhotoArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archive_file', models.FileField(upload_to='container_archives/%Y/%m/%d/', verbose_name='Архивный файл')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Обработан')),
                ('photos_count', models.PositiveIntegerField(default=0, verbose_name='Количество фотографий')),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_archives', to='core.container', verbose_name='Контейнер')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Загрузил')),
            ],
            options={
                'verbose_name': 'Архив фотографий контейнера',
                'verbose_name_plural': 'Архивы фотографий контейнеров',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
