# Generated by Django 5.1.7 on 2025-10-09 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_containerphotoarchive'),
    ]

    operations = [
        migrations.AddField(
            model_name='containerphoto',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='container_photos/thumbnails/%Y/%m/%d/', verbose_name='Миниатюра'),
        ),
    ]
