# Generated by Django 5.1.7 on 2025-10-09 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_containerphoto_thumbnail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='containerphoto',
            options={'ordering': ['photo'], 'verbose_name': 'Фотография контейнера', 'verbose_name_plural': 'Фотографии контейнеров'},
        ),
    ]
