# Generated by Django 5.1.7 on 2025-10-09 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_alter_containerphoto_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='address',
            field=models.CharField(blank=True, max_length=300, verbose_name='Адрес склада'),
        ),
    ]
