# Generated by Django 5.1.7 on 2025-10-19 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_warehouse_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accounting',
            options={'verbose_name': 'Бухгалтерская запись', 'verbose_name_plural': 'Бухгалтерия'},
        ),
        migrations.AlterModelOptions(
            name='declaration',
            options={'verbose_name': 'Декларация', 'verbose_name_plural': 'Декларации'},
        ),
        migrations.AlterModelOptions(
            name='line',
            options={'verbose_name': 'Линия', 'verbose_name_plural': 'Линии'},
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={'verbose_name': 'Склад', 'verbose_name_plural': 'Склады'},
        ),
    ]
