# Generated by Django 5.1.7 on 2025-10-19 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0078_alter_accounting_options_alter_declaration_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='google_drive_folder_url',
            field=models.URLField(blank=True, help_text='Прямая ссылка на папку с фотографиями контейнера в Google Drive', max_length=500, verbose_name='Google Drive папка'),
        ),
    ]
