# Generated by Django 5.1.7 on 2025-10-20 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_container_google_drive_folder_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='container',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='container_cars', to='core.container', verbose_name='Контейнер'),
        ),
    ]
