# Generated by Django 5.1.7 on 2025-12-04 11:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_alter_car_container'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newinvoice',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'Инвойс', 'verbose_name_plural': 'Инвойсы'},
        ),
        migrations.RemoveIndex(
            model_name='invoiceitem',
            name='core_invoic_invoice_68a42e_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoiceitem',
            name='core_invoic_car_id_2f43e2_idx',
        ),
        migrations.RemoveIndex(
            model_name='newinvoice',
            name='core_newinv_due_dat_c36d64_idx',
        ),
        migrations.RemoveIndex(
            model_name='newinvoice',
            name='core_newinv_recipie_0231c4_idx',
        ),
        migrations.RemoveIndex(
            model_name='newinvoice',
            name='core_newinv_recipie_45b40f_idx',
        ),
        migrations.RemoveIndex(
            model_name='newinvoice',
            name='core_newinv_recipie_60cdd7_idx',
        ),
        migrations.RemoveIndex(
            model_name='newinvoice',
            name='core_newinv_recipie_9a9bdf_idx',
        ),
        migrations.RemoveIndex(
            model_name='newinvoice',
            name='core_newinv_issuer__291c4d_idx',
        ),
        migrations.RemoveIndex(
            model_name='newinvoice',
            name='core_newinv_issuer__97c7c2_idx',
        ),
        migrations.RemoveIndex(
            model_name='newinvoice',
            name='core_newinv_issuer__463320_idx',
        ),
        migrations.RemoveIndex(
            model_name='newinvoice',
            name='core_newinv_issuer__9581ab_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='core_transa_number_698fab_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='core_transa_date_39873f_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='core_transa_invoice_dc6218_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='core_transa_from_cl_8cb51c_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='core_transa_to_clie_05ccba_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='core_transa_from_wa_80e10a_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='core_transa_to_ware_67ff77_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='core_transa_from_li_637047_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='core_transa_to_line_3edecb_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='core_transa_from_ca_b606db_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='core_transa_to_carr_ba8fd6_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='core_transa_from_co_3383ac_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='core_transa_to_comp_d5aa4b_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='core_transa_status_a0d663_idx',
        ),
        migrations.AddField(
            model_name='carrier',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Положительный = переплата, отрицательный = долг', max_digits=15, verbose_name='Баланс'),
        ),
        migrations.AddField(
            model_name='company',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Положительный = переплата, отрицательный = долг', max_digits=15, verbose_name='Баланс'),
        ),
        migrations.AddField(
            model_name='line',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Положительный = переплата, отрицательный = долг', max_digits=15, verbose_name='Баланс'),
        ),
        migrations.AddField(
            model_name='newinvoice',
            name='_balance_updated',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='carrier',
            name='card_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Безнал (старая)'),
        ),
        migrations.AlterField(
            model_name='carrier',
            name='cash_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Наличные (старая)'),
        ),
        migrations.AlterField(
            model_name='carrier',
            name='invoice_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Инвойс-баланс (старая)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='card_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Безнал (старая)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='cash_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Наличные (старая)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='invoice_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Инвойс-баланс (старая)'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='description',
            field=models.CharField(max_length=500, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='line',
            name='card_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Безнал (старая)'),
        ),
        migrations.AlterField(
            model_name='line',
            name='cash_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Наличные (старая)'),
        ),
        migrations.AlterField(
            model_name='line',
            name='invoice_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Инвойс-баланс (старая)'),
        ),
        migrations.AlterField(
            model_name='newinvoice',
            name='cars',
            field=models.ManyToManyField(blank=True, related_name='invoices_new', to='core.car', verbose_name='Автомобили'),
        ),
        migrations.AlterField(
            model_name='newinvoice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='newinvoice',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Срок оплаты'),
        ),
        migrations.AlterField(
            model_name='newinvoice',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Примечания'),
        ),
        migrations.AlterField(
            model_name='newinvoice',
            name='number',
            field=models.CharField(help_text='Генерируется автоматически', max_length=50, unique=True, verbose_name='Номер инвойса'),
        ),
        migrations.AlterField(
            model_name='newinvoice',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Оплачено'),
        ),
        migrations.AlterField(
            model_name='newinvoice',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Подытог'),
        ),
        migrations.AlterField(
            model_name='newinvoice',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Итого к оплате'),
        ),
        migrations.AlterField(
            model_name='newinvoice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлён'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='core.newinvoice', verbose_name='Инвойс'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='method',
            field=models.CharField(choices=[('CASH', 'Наличные'), ('CARD', 'Карта/Перевод'), ('BALANCE', 'С баланса')], default='CASH', max_length=20, verbose_name='Способ'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='number',
            field=models.CharField(max_length=50, unique=True, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('COMPLETED', 'Проведена'), ('CANCELLED', 'Отменена')], default='COMPLETED', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('PAYMENT', 'Оплата инвойса'), ('TOPUP', 'Пополнение баланса'), ('REFUND', 'Возврат'), ('ADJUSTMENT', 'Корректировка'), ('TRANSFER', 'Перевод')], max_length=20, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='cash_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Наличные (старая)'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='invoice_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Инвойс-баланс (старая)'),
        ),
    ]
