# Generated by Django 5.1.7 on 2025-12-04 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_add_unified_balance_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Положительный = переплата, отрицательный = долг', max_digits=15, verbose_name='Баланс'),
        ),
    ]
