# Generated by Django 5.1.7 on 2025-12-10 11:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0082_add_balance_to_warehouse'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounting',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='accounting',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='declaration',
            name='container',
        ),
        migrations.RemoveField(
            model_name='invoiceold',
            name='cars',
        ),
        migrations.RemoveField(
            model_name='invoiceold',
            name='client',
        ),
        migrations.RemoveField(
            model_name='invoiceold',
            name='warehouse',
        ),
        migrations.RemoveField(
            model_name='paymentold',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='paymentold',
            name='from_client',
        ),
        migrations.RemoveField(
            model_name='paymentold',
            name='from_company',
        ),
        migrations.RemoveField(
            model_name='paymentold',
            name='from_line',
        ),
        migrations.RemoveField(
            model_name='paymentold',
            name='from_warehouse',
        ),
        migrations.RemoveField(
            model_name='paymentold',
            name='to_client',
        ),
        migrations.RemoveField(
            model_name='paymentold',
            name='to_company',
        ),
        migrations.RemoveField(
            model_name='paymentold',
            name='to_line',
        ),
        migrations.RemoveField(
            model_name='paymentold',
            name='to_warehouse',
        ),
        migrations.AlterModelOptions(
            name='newinvoice',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'Инвойс (новая система)', 'verbose_name_plural': 'Инвойсы (новая система)'},
        ),
        migrations.RemoveField(
            model_name='carrier',
            name='card_balance',
        ),
        migrations.RemoveField(
            model_name='carrier',
            name='cash_balance',
        ),
        migrations.RemoveField(
            model_name='carrier',
            name='invoice_balance',
        ),
        migrations.RemoveField(
            model_name='client',
            name='card_balance',
        ),
        migrations.RemoveField(
            model_name='client',
            name='cash_balance',
        ),
        migrations.RemoveField(
            model_name='client',
            name='debt',
        ),
        migrations.RemoveField(
            model_name='client',
            name='invoice_balance',
        ),
        migrations.RemoveField(
            model_name='company',
            name='card_balance',
        ),
        migrations.RemoveField(
            model_name='company',
            name='cash_balance',
        ),
        migrations.RemoveField(
            model_name='company',
            name='invoice_balance',
        ),
        migrations.RemoveField(
            model_name='line',
            name='card_balance',
        ),
        migrations.RemoveField(
            model_name='line',
            name='cash_balance',
        ),
        migrations.RemoveField(
            model_name='line',
            name='invoice_balance',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='card_balance',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='cash_balance',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='invoice_balance',
        ),
        migrations.AddField(
            model_name='carrier',
            name='balance_updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Баланс обновлен'),
        ),
        migrations.AddField(
            model_name='company',
            name='balance_updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Баланс обновлен'),
        ),
        migrations.AddField(
            model_name='line',
            name='balance_updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Баланс обновлен'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='balance_updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Баланс обновлен'),
        ),
        migrations.AlterField(
            model_name='carrier',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Положительный = нам должны, отрицательный = мы должны', max_digits=15, verbose_name='Баланс'),
        ),
        migrations.AlterField(
            model_name='client',
            name='balance_updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Баланс обновлен'),
        ),
        migrations.AlterField(
            model_name='company',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Положительный = нам должны, отрицательный = мы должны', max_digits=15, verbose_name='Баланс'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='description',
            field=models.CharField(help_text="Например: 'Хранение авто VIN12345 (10 дней)'", max_length=500, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, help_text='Автоматически рассчитывается: количество × цена', max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='line',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Положительный = нам должны, отрицательный = мы должны', max_digits=15, verbose_name='Баланс'),
        ),
        migrations.AlterField(
            model_name='newinvoice',
            name='cars',
            field=models.ManyToManyField(blank=True, help_text='Выберите автомобили - позиции создадутся автоматически из их услуг', related_name='invoices_new', to='core.car', verbose_name='Выбранные автомобили'),
        ),
        migrations.AlterField(
            model_name='newinvoice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='newinvoice',
            name='due_date',
            field=models.DateField(blank=True, help_text='Дата, до которой должен быть оплачен инвойс (автоматически +14 дней)', null=True, verbose_name='Срок оплаты'),
        ),
        migrations.AlterField(
            model_name='newinvoice',
            name='notes',
            field=models.TextField(blank=True, help_text='Дополнительная информация об инвойсе', verbose_name='Примечания'),
        ),
        migrations.AlterField(
            model_name='newinvoice',
            name='number',
            field=models.CharField(help_text='Уникальный номер инвойса (генерируется автоматически)', max_length=50, unique=True, verbose_name='Номер инвойса'),
        ),
        migrations.AlterField(
            model_name='newinvoice',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Сумма, которая уже оплачена', max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Оплачено'),
        ),
        migrations.AlterField(
            model_name='newinvoice',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Сумма всех позиций без дополнительных сборов', max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Подытог'),
        ),
        migrations.AlterField(
            model_name='newinvoice',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Итоговая сумма инвойса', max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Итого к оплате'),
        ),
        migrations.AlterField(
            model_name='newinvoice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.TextField(help_text='Подробное описание операции', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='invoice',
            field=models.ForeignKey(blank=True, help_text='Если это оплата инвойса, указываем его здесь', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='core.newinvoice', verbose_name='Инвойс'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='method',
            field=models.CharField(choices=[('CASH', 'Наличные'), ('CARD', 'Банковская карта'), ('TRANSFER', 'Банковский перевод'), ('BALANCE', 'Списание с баланса'), ('OTHER', 'Другое')], max_length=20, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='number',
            field=models.CharField(max_length=50, unique=True, verbose_name='Номер транзакции'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'В ожидании'), ('COMPLETED', 'Завершена'), ('FAILED', 'Ошибка'), ('CANCELLED', 'Отменена')], default='COMPLETED', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('PAYMENT', 'Платеж'), ('REFUND', 'Возврат'), ('ADJUSTMENT', 'Корректировка'), ('TRANSFER', 'Перевод'), ('BALANCE_TOPUP', 'Пополнение баланса')], max_length=20, verbose_name='Тип операции'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Положительный = нам должны, отрицательный = мы должны', max_digits=15, verbose_name='Баланс'),
        ),
        migrations.AddIndex(
            model_name='invoiceitem',
            index=models.Index(fields=['invoice', 'order'], name='core_invoic_invoice_68a42e_idx'),
        ),
        migrations.AddIndex(
            model_name='invoiceitem',
            index=models.Index(fields=['car'], name='core_invoic_car_id_2f43e2_idx'),
        ),
        migrations.AddIndex(
            model_name='newinvoice',
            index=models.Index(fields=['due_date', 'status'], name='core_newinv_due_dat_c36d64_idx'),
        ),
        migrations.AddIndex(
            model_name='newinvoice',
            index=models.Index(fields=['recipient_warehouse', 'status'], name='core_newinv_recipie_0231c4_idx'),
        ),
        migrations.AddIndex(
            model_name='newinvoice',
            index=models.Index(fields=['recipient_line', 'status'], name='core_newinv_recipie_45b40f_idx'),
        ),
        migrations.AddIndex(
            model_name='newinvoice',
            index=models.Index(fields=['recipient_carrier', 'status'], name='core_newinv_recipie_60cdd7_idx'),
        ),
        migrations.AddIndex(
            model_name='newinvoice',
            index=models.Index(fields=['recipient_company', 'status'], name='core_newinv_recipie_9a9bdf_idx'),
        ),
        migrations.AddIndex(
            model_name='newinvoice',
            index=models.Index(fields=['issuer_company', 'status'], name='core_newinv_issuer__291c4d_idx'),
        ),
        migrations.AddIndex(
            model_name='newinvoice',
            index=models.Index(fields=['issuer_warehouse', 'status'], name='core_newinv_issuer__97c7c2_idx'),
        ),
        migrations.AddIndex(
            model_name='newinvoice',
            index=models.Index(fields=['issuer_line', 'status'], name='core_newinv_issuer__463320_idx'),
        ),
        migrations.AddIndex(
            model_name='newinvoice',
            index=models.Index(fields=['issuer_carrier', 'status'], name='core_newinv_issuer__9581ab_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['number'], name='core_transa_number_698fab_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['date', 'type'], name='core_transa_date_39873f_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['invoice'], name='core_transa_invoice_dc6218_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['from_client', 'date'], name='core_transa_from_cl_8cb51c_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['to_client', 'date'], name='core_transa_to_clie_05ccba_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['from_warehouse', 'date'], name='core_transa_from_wa_80e10a_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['to_warehouse', 'date'], name='core_transa_to_ware_67ff77_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['from_line', 'date'], name='core_transa_from_li_637047_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['to_line', 'date'], name='core_transa_to_line_3edecb_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['from_carrier', 'date'], name='core_transa_from_ca_b606db_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['to_carrier', 'date'], name='core_transa_to_carr_ba8fd6_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['from_company', 'date'], name='core_transa_from_co_3383ac_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['to_company', 'date'], name='core_transa_to_comp_d5aa4b_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status', 'date'], name='core_transa_status_a0d663_idx'),
        ),
        migrations.DeleteModel(
            name='Accounting',
        ),
        migrations.DeleteModel(
            name='Declaration',
        ),
        migrations.DeleteModel(
            name='InvoiceOLD',
        ),
        migrations.DeleteModel(
            name='PaymentOLD',
        ),
    ]
