# Generated by Django 5.1.7 on 2025-12-10 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0083_remove_accounting_invoice_remove_accounting_payment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newinvoice',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'Инвойс', 'verbose_name_plural': 'Инвойсы'},
        ),
        migrations.AddField(
            model_name='car',
            name='vehicle_type',
            field=models.CharField(choices=[('CAR', 'Автомобиль'), ('MOTO', 'Мотоцикл')], default='CAR', max_length=10, verbose_name='Тип ТС'),
        ),
    ]
