# Generated by Django 5.1.7 on 2025-12-13 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0084_add_vehicle_type_to_car'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, help_text='Email для отправки уведомлений о разгрузке контейнеров', max_length=254, null=True, verbose_name='Email для уведомлений'),
        ),
        migrations.AddField(
            model_name='client',
            name='notification_enabled',
            field=models.BooleanField(default=True, help_text='Отправлять email-уведомления о контейнерах', verbose_name='Получать уведомления'),
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('ETA', 'Планируемая разгрузка (ETA)'), ('UNLOADED', 'Разгрузка выполнена')], max_length=20, verbose_name='Тип уведомления')),
                ('email_to', models.EmailField(max_length=254, verbose_name='Email получателя')),
                ('subject', models.CharField(max_length=255, verbose_name='Тема письма')),
                ('cars_info', models.TextField(blank=True, help_text='JSON со списком VIN и марок авто в уведомлении', verbose_name='Информация об авто')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки')),
                ('success', models.BooleanField(default=True, verbose_name='Успешно отправлено')),
                ('error_message', models.TextField(blank=True, verbose_name='Сообщение об ошибке')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.client', verbose_name='Клиент')),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.container', verbose_name='Контейнер')),
                ('created_by', models.ForeignKey(blank=True, help_text='Кто инициировал отправку', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Отправил')),
            ],
            options={
                'verbose_name': 'Лог уведомлений',
                'verbose_name_plural': 'Логи уведомлений',
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['container', 'notification_type'], name='core_notifi_contain_39d5fd_idx'), models.Index(fields=['client', 'sent_at'], name='core_notifi_client__84ffb6_idx')],
            },
        ),
    ]
