# Generated by Django 5.1.7 on 2025-12-13 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0085_add_email_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='planned_unload_date',
            field=models.DateField(blank=True, help_text='Укажите когда планируете разгружать контейнер (клиенты получат уведомление)', null=True, verbose_name='Планируемая дата разгрузки'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='notification_type',
            field=models.CharField(choices=[('PLANNED', 'Планируемая разгрузка'), ('UNLOADED', 'Разгрузка выполнена')], max_length=20, verbose_name='Тип уведомления'),
        ),
    ]
