# Generated by Django 5.1.7 on 2025-12-14 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0086_add_planned_unload_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouseservice',
            name='add_by_default',
            field=models.BooleanField(default=False, help_text='Автоматически добавлять эту услугу при создании автомобиля на этом складе', verbose_name='Добавлять по умолчанию'),
        ),
        migrations.AlterField(
            model_name='container',
            name='planned_unload_date',
            field=models.DateField(blank=True, help_text='Укажите когда планируете разгружать контейнер (клиенты получат уведомление)', null=True, verbose_name='Будем разгружать'),
        ),
    ]
