# Generated by Django 5.1.7 on 2025-12-15 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0087_add_warehouse_service_add_by_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='email2',
            field=models.EmailField(blank=True, help_text='Дополнительный email для уведомлений', max_length=254, null=True, verbose_name='Email 2'),
        ),
        migrations.AddField(
            model_name='client',
            name='email3',
            field=models.EmailField(blank=True, help_text='Дополнительный email для уведомлений', max_length=254, null=True, verbose_name='Email 3'),
        ),
        migrations.AddField(
            model_name='client',
            name='email4',
            field=models.EmailField(blank=True, help_text='Дополнительный email для уведомлений', max_length=254, null=True, verbose_name='Email 4'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, help_text='Основной email для уведомлений о разгрузке контейнеров', max_length=254, null=True, verbose_name='Email 1'),
        ),
    ]
