# Generated by Django 5.1.7 on 2026-01-13 22:39

import django.db.models.deletion
from django.db import migrations, models


def convert_car_to_sedan(apps, schema_editor):
    """Конвертирует старый тип CAR в новый SEDAN"""
    Car = apps.get_model('core', 'Car')
    updated = Car.objects.filter(vehicle_type='CAR').update(vehicle_type='SEDAN')
    if updated:
        print(f"  Конвертировано {updated} записей CAR -> SEDAN")


def reverse_sedan_to_car(apps, schema_editor):
    """Обратная конвертация SEDAN -> CAR"""
    Car = apps.get_model('core', 'Car')
    Car.objects.filter(vehicle_type='SEDAN').update(vehicle_type='CAR')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0088_add_multiple_client_emails'),
    ]

    operations = [
        # Сначала меняем тип поля чтобы принимало новые значения
        migrations.AlterField(
            model_name='car',
            name='vehicle_type',
            field=models.CharField(choices=[('SEDAN', 'Легковой'), ('CROSSOVER', 'Кроссовер'), ('SUV', 'Джип'), ('PICKUP', 'Пикап'), ('NEW_CAR', 'Новая машина'), ('MOTO', 'Мотоцикл'), ('BIG_MOTO', 'Большой мотоцикл'), ('ATV', 'Квадроцикл/Багги'), ('BOAT', 'Лодка'), ('RV', 'Автодом (RV)'), ('CONSTRUCTION', 'Стр. техника')], default='SEDAN', max_length=20, verbose_name='Тип ТС'),
        ),
        # Затем конвертируем данные CAR -> SEDAN
        migrations.RunPython(convert_car_to_sedan, reverse_sedan_to_car),
        # Добавляем поле ths_payer в Container
        migrations.AddField(
            model_name='container',
            name='ths_payer',
            field=models.CharField(choices=[('LINE', 'Линия'), ('WAREHOUSE', 'Склад')], default='LINE', help_text='Кому будет начислена услуга THS: линии или складу', max_length=20, verbose_name='Кто платит THS'),
        ),
        migrations.CreateModel(
            name='LineTHSPercent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('SEDAN', 'Легковой'), ('CROSSOVER', 'Кроссовер'), ('SUV', 'Джип'), ('PICKUP', 'Пикап'), ('NEW_CAR', 'Новая машина'), ('MOTO', 'Мотоцикл'), ('BIG_MOTO', 'Большой мотоцикл'), ('ATV', 'Квадроцикл/Багги'), ('BOAT', 'Лодка'), ('RV', 'Автодом (RV)'), ('CONSTRUCTION', 'Стр. техника')], max_length=20, verbose_name='Тип ТС')),
                ('percent', models.DecimalField(decimal_places=2, default=25.0, help_text='Процент от общей суммы THS для данного типа ТС', max_digits=5, verbose_name='Процент от THS')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ths_percents', to='core.line', verbose_name='Линия')),
            ],
            options={
                'verbose_name': 'Процент THS для типа ТС',
                'verbose_name_plural': 'Проценты THS для типов ТС',
                'unique_together': {('line', 'vehicle_type')},
            },
        ),
    ]
