# Generated by Django 5.1.7 on 2026-01-13 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0089_expand_vehicle_types_and_ths_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='ths_payer',
            field=models.CharField(choices=[('LINE', 'Напрямую линии'), ('WAREHOUSE', 'Через склад')], default='LINE', help_text='От чьего имени записать расход THS в карточках ТС: напрямую линии или через склад', max_length=20, verbose_name='Оплата THS через'),
        ),
    ]
