# Generated by Django 5.1.7 on 2026-01-16 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0090_update_ths_payer_labels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='rate',
        ),
    ]
