# Generated by Django 5.1.7 on 2026-01-16 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0091_remove_warehouse_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='current_price',
        ),
        migrations.AlterField(
            model_name='car',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Цена'),
        ),
    ]
