# Generated by Django 5.1.7 on 2026-01-16

from decimal import Decimal
from django.db import migrations, models


def convert_percent_to_coefficient(apps, schema_editor):
    """Конвертируем проценты в коэффициенты.
    
    Логика: процент 25% (по умолчанию) -> коэффициент 1.0
    То есть коэффициент = процент / 25
    
    Примеры:
    - 25% -> 1.0 (стандарт)
    - 50% -> 2.0 (двойной)
    - 12.5% -> 0.5 (половина)
    """
    LineTHSPercent = apps.get_model('core', 'LineTHSPercent')
    for obj in LineTHSPercent.objects.all():
        # Конвертируем: коэффициент = процент / 25
        obj.percent = Decimal(str(obj.percent)) / Decimal('25')
        obj.save()


def convert_coefficient_to_percent(apps, schema_editor):
    """Обратная конвертация для отката миграции."""
    LineTHSPercent = apps.get_model('core', 'LineTHSPercent')
    for obj in LineTHSPercent.objects.all():
        # Обратная конвертация: процент = коэффициент * 25
        obj.percent = Decimal(str(obj.percent)) * Decimal('25')
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0092_remove_current_price'),
    ]

    operations = [
        # 1. Конвертируем значения процентов в коэффициенты
        migrations.RunPython(convert_percent_to_coefficient, convert_coefficient_to_percent),
        
        # 2. Переименовываем поле percent -> coefficient
        migrations.RenameField(
            model_name='linethspercent',
            old_name='percent',
            new_name='coefficient',
        ),
        
        # 3. Изменяем параметры поля
        migrations.AlterField(
            model_name='linethspercent',
            name='coefficient',
            field=models.DecimalField(
                decimal_places=2,
                default=1.0,
                help_text='Вес типа ТС при распределении THS (1.0 = стандарт, 2.0 = двойной, 0.5 = половина)',
                max_digits=5,
                verbose_name='Коэффициент'
            ),
        ),
        
        # 4. Переименовываем модель
        migrations.RenameModel(
            old_name='LineTHSPercent',
            new_name='LineTHSCoefficient',
        ),
        
        # 5. Обновляем related_name
        migrations.AlterField(
            model_name='linethscoefficient',
            name='line',
            field=models.ForeignKey(
                on_delete=models.CASCADE,
                related_name='ths_coefficients',
                to='core.line',
                verbose_name='Линия'
            ),
        ),
        
        # 6. Обновляем Meta
        migrations.AlterModelOptions(
            name='linethscoefficient',
            options={
                'verbose_name': 'Коэффициент THS для типа ТС',
                'verbose_name_plural': 'Коэффициенты THS для типов ТС',
            },
        ),
    ]
