# Generated by Django 5.1.7 on 2026-01-17 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0093_rename_ths_percent_to_coefficient'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='hide_markup_in',
            field=models.ForeignKey(blank=True, help_text='Выберите услугу, в которую добавить наценку (вместо отдельной строки в инвойсе)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars_with_hidden_markup', to='core.carservice', verbose_name='Скрыть наценку в услуге'),
        ),
        migrations.AlterField(
            model_name='car',
            name='has_title',
            field=models.BooleanField(default=False, verbose_name='Т'),
        ),
    ]
