# Generated by Django 5.1.7 on 2026-01-17 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0094_add_hide_markup_in_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='carservice',
            name='markup_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Сумма наценки, которая будет добавлена к цене услуги в инвойсе (скрыто от клиента)', max_digits=10, verbose_name='Скрытая наценка'),
        ),
    ]
