# Generated by Django 5.1.7 on 2026-01-17 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0095_add_markup_distribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrierservice',
            name='default_markup',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Скрытая наценка, которая будет автоматически добавлена при создании услуги для авто', max_digits=10, verbose_name='Наценка по умолчанию'),
        ),
        migrations.AddField(
            model_name='lineservice',
            name='default_markup',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Скрытая наценка, которая будет автоматически добавлена при создании услуги для авто', max_digits=10, verbose_name='Наценка по умолчанию'),
        ),
        migrations.AddField(
            model_name='warehouseservice',
            name='default_markup',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Скрытая наценка, которая будет автоматически добавлена при создании услуги для авто', max_digits=10, verbose_name='Наценка по умолчанию'),
        ),
    ]
