# Generated by Django 5.1.7 on 2026-01-23 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0097_add_unloaded_status_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='unloaded_status_at',
            field=models.DateTimeField(blank=True, help_text="Когда контейнер получил статус 'Разгружен' (для задержки синхронизации фото)", null=True, verbose_name="Статус 'Разгружен' с"),
        ),
    ]
