# Generated by Django 5.1.7 on 2026-01-24 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0100_add_company_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carservice',
            name='service_type',
            field=models.CharField(choices=[('LINE', 'Линия'), ('CARRIER', 'Перевозчик'), ('WAREHOUSE', 'Склад'), ('COMPANY', 'Компания')], max_length=20, verbose_name='Тип поставщика'),
        ),
        migrations.AlterField(
            model_name='companyservice',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='deletedcarservice',
            name='service_type',
            field=models.CharField(choices=[('LINE', 'Линия'), ('CARRIER', 'Перевозчик'), ('WAREHOUSE', 'Склад'), ('COMPANY', 'Компания')], max_length=20, verbose_name='Тип поставщика'),
        ),
    ]
