# Generated by ChatGPT
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0101_alter_carservice_service_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aichat",
            name="context_snapshot",
            field=models.JSONField(blank=True, null=True, verbose_name="Контекст"),
        ),
    ]
