# Generated by Django 5.1.7 on 2026-02-04 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0102_add_aichat_context_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrier',
            name='eori_code',
            field=models.CharField(blank=True, help_text='Код EORI перевозчика для таможенного оформления', max_length=50, null=True, verbose_name='EORI код'),
        ),
        migrations.CreateModel(
            name='AutoTransport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='Уникальный номер рейса', max_length=50, unique=True, verbose_name='Номер автовоза')),
                ('status', models.CharField(choices=[('DRAFT', 'Черновик'), ('FORMED', 'Сформирован'), ('LOADED', 'Загружен'), ('IN_TRANSIT', 'В пути'), ('DELIVERED', 'Доставлен'), ('CANCELLED', 'Отменен')], default='DRAFT', max_length=20, verbose_name='Статус')),
                ('eori_code', models.CharField(blank=True, help_text='Автоматически подтягивается из перевозчика', max_length=50, verbose_name='EORI код')),
                ('truck_number_manual', models.CharField(blank=True, help_text='Если автовоза нет в списке', max_length=20, verbose_name='Номер тягача (вручную)')),
                ('trailer_number_manual', models.CharField(blank=True, help_text='Если автовоза нет в списке', max_length=20, verbose_name='Номер прицепа (вручную)')),
                ('driver_name_manual', models.CharField(blank=True, help_text='Если водителя нет в списке', max_length=100, verbose_name='ФИО водителя (вручную)')),
                ('driver_phone', models.CharField(blank=True, help_text='Автоматически подтягивается из водителя или вводится вручную', max_length=20, verbose_name='Телефон водителя')),
                ('border_crossing', models.CharField(blank=True, help_text='Название пункта пересечения границы', max_length=100, verbose_name='Граница пересечения')),
                ('loading_date', models.DateField(blank=True, null=True, verbose_name='Дата загрузки')),
                ('departure_date', models.DateField(blank=True, null=True, verbose_name='Дата отправления')),
                ('estimated_delivery_date', models.DateField(blank=True, null=True, verbose_name='Планируемая дата доставки')),
                ('actual_delivery_date', models.DateField(blank=True, null=True, verbose_name='Фактическая дата доставки')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('created_by', models.CharField(blank=True, max_length=100, verbose_name='Создал')),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auto_transports', to='core.carrier', verbose_name='Перевозчик')),
                ('cars', models.ManyToManyField(blank=True, related_name='auto_transports', to='core.car', verbose_name='Автомобили')),
            ],
            options={
                'verbose_name': 'Автовоз на загрузку',
                'verbose_name_plural': 'Автовозы на загрузку',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='newinvoice',
            name='auto_transport',
            field=models.ForeignKey(blank=True, help_text='Автовоз, для которого создан этот инвойс', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='core.autotransport', verbose_name='Автовоз'),
        ),
        migrations.CreateModel(
            name='CarrierDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='core.carrier', verbose_name='Перевозчик')),
            ],
            options={
                'verbose_name': 'Водитель перевозчика',
                'verbose_name_plural': 'Водители перевозчиков',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.AddField(
            model_name='autotransport',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transports', to='core.carrierdriver', verbose_name='Водитель'),
        ),
        migrations.CreateModel(
            name='CarrierTruck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_number', models.CharField(help_text='Номер головы автовоза', max_length=20, verbose_name='Номер тягача')),
                ('trailer_number', models.CharField(blank=True, help_text='Номер прицепа (опционально)', max_length=20, verbose_name='Номер прицепа')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trucks', to='core.carrier', verbose_name='Перевозчик')),
            ],
            options={
                'verbose_name': 'Автовоз перевозчика',
                'verbose_name_plural': 'Автовозы перевозчиков',
                'ordering': ['-created_at'],
                'unique_together': {('carrier', 'truck_number', 'trailer_number')},
            },
        ),
        migrations.AddField(
            model_name='autotransport',
            name='truck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transports', to='core.carriertruck', verbose_name='Автовоз'),
        ),
    ]
