# Generated by Django 5.1.7 on 2026-02-06 17:04

from django.db import migrations, models


def set_default_short_names(apps, schema_editor):
    """Set default abbreviations for existing services based on name patterns"""
    RULES = {
        'ths': 'THS',
        'хранение': 'Хран',
        'разгрузка': 'Порт',
        'погрузка': 'Порт',
        'декларация': 'Порт',
        'документ': 'Док',
        'доставка': 'Дост',
        'транспорт': 'Трансп',
        'комиссия': 'Комис',
        'страхов': 'Страх',
    }
    
    for model_name in ['WarehouseService', 'LineService', 'CarrierService', 'CompanyService']:
        Model = apps.get_model('core', model_name)
        for service in Model.objects.filter(short_name=''):
            name_lower = service.name.lower()
            matched = False
            for pattern, short in RULES.items():
                if pattern in name_lower:
                    service.short_name = short
                    matched = True
                    break
            if not matched:
                service.short_name = service.name[:10]
            service.save(update_fields=['short_name'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0103_carrier_eori_code_autotransport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrierservice',
            name='short_name',
            field=models.CharField(blank=True, default='', help_text='Короткое название для инвойсов и таблиц (напр. THS, Порт, Хран)', max_length=20, verbose_name='Сокращённо'),
        ),
        migrations.AddField(
            model_name='companyservice',
            name='short_name',
            field=models.CharField(blank=True, default='', help_text='Короткое название для инвойсов и таблиц (напр. THS, Порт, Хран)', max_length=20, verbose_name='Сокращённо'),
        ),
        migrations.AddField(
            model_name='lineservice',
            name='short_name',
            field=models.CharField(blank=True, default='', help_text='Короткое название для инвойсов и таблиц (напр. THS, Порт, Хран)', max_length=20, verbose_name='Сокращённо'),
        ),
        migrations.AddField(
            model_name='warehouseservice',
            name='short_name',
            field=models.CharField(blank=True, default='', help_text='Короткое название для инвойсов и таблиц (напр. THS, Порт, Хран)', max_length=20, verbose_name='Сокращённо'),
        ),
        migrations.RunPython(set_default_short_names, migrations.RunPython.noop),
    ]
