# Generated by Django 5.1.7 on 2026-02-06 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0104_add_service_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='tariff_type',
            field=models.CharField(choices=[('NONE', 'Без тарифа'), ('FIXED', 'Фиксированная цена THS'), ('FLEXIBLE', 'Гибкая цена THS (множитель)')], default='NONE', help_text='NONE=обычные наценки, FIXED=фикс.цена THS, FLEXIBLE=факт.THS×множитель', max_length=10, verbose_name='Тип тарифа THS'),
        ),
        migrations.CreateModel(
            name='ClientTariffRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('SEDAN', 'Легковой'), ('CROSSOVER', 'Кроссовер'), ('SUV', 'Джип'), ('PICKUP', 'Пикап'), ('NEW_CAR', 'Новая машина'), ('MOTO', 'Мотоцикл'), ('BIG_MOTO', 'Большой мотоцикл'), ('ATV', 'Квадроцикл/Багги'), ('BOAT', 'Лодка'), ('RV', 'Автодом (RV)'), ('CONSTRUCTION', 'Стр. техника')], max_length=20, verbose_name='Тип ТС')),
                ('fixed_ths_price', models.DecimalField(blank=True, decimal_places=2, help_text='Для фиксированного тарифа: цена THS за авто этого типа', max_digits=10, null=True, verbose_name='Фикс. цена THS')),
                ('ths_multiplier', models.DecimalField(blank=True, decimal_places=3, default=1.0, help_text='Для гибкого тарифа: факт.THS × множитель = цена клиенту', max_digits=6, null=True, verbose_name='Множитель THS')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tariff_rates', to='core.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Ставка THS',
                'verbose_name_plural': 'Ставки THS по типам ТС',
                'ordering': ['vehicle_type'],
                'unique_together': {('client', 'vehicle_type')},
            },
        ),
    ]
