# Generated by Django 5.1.7 on 2026-02-06 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0104_add_service_short_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientTariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tariff_type', models.CharField(choices=[('FIXED', 'Фиксированная цена за авто'), ('VOLUME', 'Зависит от кол-ва ТС в контейнере')], max_length=10, verbose_name='Тип тарифа')),
                ('fixed_price', models.DecimalField(blank=True, decimal_places=2, help_text="Используется при типе 'Фиксированная цена'", max_digits=10, null=True, verbose_name='Фикс. цена за авто (без хранения)')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tariff', to='core.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Тариф клиента',
                'verbose_name_plural': 'Тарифы клиентов',
            },
        ),
        migrations.CreateModel(
            name='ClientTariffTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_cars', models.PositiveIntegerField(verbose_name='От (всего ТС в контейнере)')),
                ('max_cars', models.PositiveIntegerField(blank=True, null=True, verbose_name='До (всего ТС, пусто = и более)')),
                ('price_per_car', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за авто (без хранения)')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='core.clienttariff', verbose_name='Тариф')),
            ],
            options={
                'verbose_name': 'Ступень тарифа',
                'verbose_name_plural': 'Ступени тарифа',
                'ordering': ['min_cars'],
            },
        ),
    ]
