# Generated by Django 5.1.7 on 2026-02-06 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0105_add_client_tariff_rates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienttariffrate',
            name='ths_multiplier',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Для гибкого тарифа: коэфф.линии × это значение = цена THS клиенту. Пример: коэфф.линии 1.0 × 115 = 115€', max_digits=10, null=True, verbose_name='Коэффициент THS (€)'),
        ),
    ]
