# Generated by Django 5.1.7 on 2026-02-06 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0106_update_ths_multiplier_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clienttariffrate',
            options={'ordering': ['vehicle_type', 'min_cars'], 'verbose_name': 'Ставка THS', 'verbose_name_plural': 'Ставки THS по типам ТС'},
        ),
        migrations.AlterUniqueTogether(
            name='clienttariffrate',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='clienttariffrate',
            name='agreed_ths_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Согласованная цена THS для клиента', max_digits=10, verbose_name='Цена THS за авто (€)'),
        ),
        migrations.AddField(
            model_name='clienttariffrate',
            name='max_cars',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='До (пусто = и более)'),
        ),
        migrations.AddField(
            model_name='clienttariffrate',
            name='min_cars',
            field=models.PositiveIntegerField(default=1, verbose_name='От (ТС в контейнере)'),
        ),
        migrations.AlterField(
            model_name='client',
            name='tariff_type',
            field=models.CharField(choices=[('NONE', 'Без тарифа'), ('FIXED', 'Фиксированная цена THS'), ('FLEXIBLE', 'Гибкая цена THS (по кол-ву авто)')], default='NONE', help_text='NONE=обычные наценки, FIXED=фикс.цена THS (не зависит от кол-ва), FLEXIBLE=цена THS зависит от кол-ва авто в контейнере', max_length=10, verbose_name='Тип тарифа THS'),
        ),
        migrations.RemoveField(
            model_name='clienttariffrate',
            name='fixed_ths_price',
        ),
        migrations.RemoveField(
            model_name='clienttariffrate',
            name='ths_multiplier',
        ),
    ]
