# Generated by Django 5.1.7 on 2026-02-07 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0107_add_volume_tiers_to_tariff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clienttariffrate',
            options={'ordering': ['vehicle_type', 'min_cars'], 'verbose_name': 'Тариф', 'verbose_name_plural': 'Тарифы по типам ТС'},
        ),
        migrations.RenameField(
            model_name='clienttariffrate',
            old_name='agreed_ths_price',
            new_name='agreed_total_price',
        ),
        migrations.AlterField(
            model_name='clienttariffrate',
            name='agreed_total_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Общая согласованная цена за все услуги (кроме хранения) для этого типа ТС', max_digits=10, verbose_name='Цена за авто (€)'),
        ),
        migrations.AlterField(
            model_name='client',
            name='tariff_type',
            field=models.CharField(choices=[('NONE', 'Без тарифа'), ('FIXED', 'Фикс. цена (не зависит от кол-ва)'), ('FLEXIBLE', 'Гибкая цена (зависит от кол-ва авто)')], default='NONE', help_text='NONE=обычные наценки, FIXED=фикс.цена (не зависит от кол-ва), FLEXIBLE=цена зависит от кол-ва авто в контейнере', max_length=10, verbose_name='Тип тарифа'),
        ),
    ]
