# Generated by Django 5.1.7 on 2026-02-08 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0108_rename_agreed_price_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_type', models.CharField(choices=[('REVOLUT', 'Revolut Business'), ('OTHER', 'Другой банк')], default='REVOLUT', max_length=20, verbose_name='Тип банка')),
                ('name', models.CharField(help_text='Например: Revolut Business EUR', max_length=100, verbose_name='Название подключения')),
                ('_client_id', models.TextField(blank=True, db_column='client_id', default='', verbose_name='Client ID (encrypted)')),
                ('_refresh_token', models.TextField(blank=True, db_column='refresh_token', default='', verbose_name='Refresh Token (encrypted)')),
                ('_access_token', models.TextField(blank=True, db_column='access_token', default='', verbose_name='Access Token (encrypted)')),
                ('access_token_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Access Token истекает')),
                ('_jwt_assertion', models.TextField(blank=True, db_column='jwt_assertion', default='', verbose_name='JWT Assertion (encrypted)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('use_sandbox', models.BooleanField(default=False, verbose_name='Sandbox-режим')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Последняя синхронизация')),
                ('last_error', models.TextField(blank=True, default='', verbose_name='Последняя ошибка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_connections', to='core.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Банковское подключение',
                'verbose_name_plural': 'Банковские подключения',
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(help_text='UUID счёта в Revolut', max_length=100, verbose_name='ID в банке')),
                ('name', models.CharField(blank=True, default='', max_length=200, verbose_name='Название счёта')),
                ('currency', models.CharField(max_length=10, verbose_name='Валюта')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Баланс')),
                ('state', models.CharField(default='active', help_text='active / inactive', max_length=20, verbose_name='Статус')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='core.bankconnection', verbose_name='Подключение')),
            ],
            options={
                'verbose_name': 'Банковский счёт',
                'verbose_name_plural': 'Банковские счета',
                'unique_together': {('connection', 'external_id')},
            },
        ),
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=100, verbose_name='ID транзакции в банке')),
                ('transaction_type', models.CharField(choices=[('card_payment', 'Оплата картой'), ('card_refund', 'Возврат по карте'), ('transfer', 'Перевод'), ('exchange', 'Обмен валют'), ('topup', 'Пополнение'), ('fee', 'Комиссия'), ('atm', 'Снятие в банкомате'), ('refund', 'Возврат'), ('tax', 'Налог'), ('other', 'Другое')], default='other', max_length=30, verbose_name='Тип')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Сумма')),
                ('currency', models.CharField(max_length=10, verbose_name='Валюта')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('counterparty_name', models.CharField(blank=True, default='', max_length=200, verbose_name='Контрагент')),
                ('state', models.CharField(default='completed', help_text='pending / completed / declined / failed / reverted', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(verbose_name='Дата транзакции')),
                ('fetched_at', models.DateTimeField(auto_now=True, verbose_name='Загружено')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.bankconnection', verbose_name='Подключение')),
            ],
            options={
                'verbose_name': 'Банковская транзакция',
                'verbose_name_plural': 'Банковские транзакции',
                'ordering': ['-created_at'],
                'unique_together': {('connection', 'external_id')},
            },
        ),
    ]
