# Generated by Django 5.1.7 on 2026-02-09 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0109_add_banking_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteProConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: Site.pro Caromoto Lithuania', max_length=100, verbose_name='Название подключения')),
                ('_username', models.TextField(blank=True, db_column='sp_username', default='', verbose_name='Username (encrypted)')),
                ('_password', models.TextField(blank=True, db_column='sp_password', default='', verbose_name='Password (encrypted)')),
                ('_access_token', models.TextField(blank=True, db_column='sp_access_token', default='', verbose_name='Access Token (encrypted)')),
                ('access_token_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Access Token истекает')),
                ('sitepro_user_id', models.CharField(blank=True, default='', help_text='ID пользователя в site.pro (из ответа /token)', max_length=50, verbose_name='SitePro User ID')),
                ('sitepro_company_id', models.CharField(blank=True, default='', help_text='ID компании в site.pro (spcoid из ответа /token)', max_length=50, verbose_name='SitePro Company ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('auto_push_on_issue', models.BooleanField(default=False, help_text='Автоматически отправлять инвойс в site.pro при смене статуса на ISSUED', verbose_name='Авто-отправка при выставлении')),
                ('default_vat_rate', models.DecimalField(decimal_places=2, default=0, help_text='Ставка НДС для позиций инвойса (0 = без НДС)', max_digits=5, verbose_name='Ставка НДС по умолчанию (%)')),
                ('default_currency', models.CharField(default='EUR', max_length=3, verbose_name='Валюта по умолчанию')),
                ('invoice_series', models.CharField(blank=True, default='', help_text='Серия нумерации инвойсов (например: CAR)', max_length=20, verbose_name='Серия инвойсов в site.pro')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Последняя синхронизация')),
                ('last_error', models.TextField(blank=True, default='', verbose_name='Последняя ошибка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sitepro_connections', to='core.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Подключение site.pro',
                'verbose_name_plural': 'Подключения site.pro',
            },
        ),
        migrations.CreateModel(
            name='SiteProInvoiceSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, default='', help_text='ID инвойса/продажи в site.pro', max_length=100, verbose_name='ID в site.pro')),
                ('external_number', models.CharField(blank=True, default='', help_text='Номер инвойса в site.pro', max_length=100, verbose_name='Номер в site.pro')),
                ('pdf_url', models.URLField(blank=True, default='', help_text='Ссылка на PDF инвойса в site.pro', verbose_name='PDF URL')),
                ('sync_status', models.CharField(choices=[('PENDING', 'Ожидает отправки'), ('SENT', 'Отправлен'), ('FAILED', 'Ошибка'), ('PDF_READY', 'PDF готов')], default='PENDING', max_length=20, verbose_name='Статус синхронизации')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='Ошибка')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Последняя синхронизация')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_syncs', to='core.siteproconnection', verbose_name='Подключение')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sitepro_syncs', to='core.newinvoice', verbose_name='Инвойс')),
            ],
            options={
                'verbose_name': 'Синхронизация инвойса (site.pro)',
                'verbose_name_plural': 'Синхронизация инвойсов (site.pro)',
                'ordering': ['-created_at'],
                'unique_together': {('connection', 'invoice')},
            },
        ),
    ]
