# Generated by Django 5.1.7 on 2026-02-09 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0110_sitepro_integration'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteproconnection',
            name='_api_key',
            field=models.TextField(blank=True, db_column='sp_api_key', default='', help_text='API raktas из настроек site.pro', verbose_name='API Key (encrypted)'),
        ),
        migrations.AddField(
            model_name='siteproconnection',
            name='_private_key',
            field=models.TextField(blank=True, db_column='sp_private_key', default='', help_text='Privatus raktas из настроек site.pro', verbose_name='Private Key (encrypted)'),
        ),
    ]
