# Generated by Django 5.1.7 on 2026-02-09 12:50

import django.db.models.deletion
from django.db import migrations, models


def create_default_categories(apps, schema_editor):
    """Создать базовые категории расходов/доходов"""
    ExpenseCategory = apps.get_model('core', 'ExpenseCategory')
    categories = [
        {'name': 'Логистика', 'short_name': 'Лог', 'category_type': 'OPERATIONAL', 'order': 1},
        {'name': 'Аренда', 'short_name': 'Аренда', 'category_type': 'ADMINISTRATIVE', 'order': 2},
        {'name': 'Коммунальные', 'short_name': 'Комм', 'category_type': 'ADMINISTRATIVE', 'order': 3},
        {'name': 'Зарплаты', 'short_name': 'ЗП', 'category_type': 'SALARY', 'order': 4},
        {'name': 'Маркетинг', 'short_name': 'Марк', 'category_type': 'MARKETING', 'order': 5},
        {'name': 'Налоги и сборы', 'short_name': 'Налог', 'category_type': 'TAX', 'order': 6},
        {'name': 'Прочие', 'short_name': 'Проч', 'category_type': 'OTHER', 'order': 7},
    ]
    for cat in categories:
        ExpenseCategory.objects.get_or_create(name=cat['name'], defaults=cat)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0111_add_sitepro_api_keys'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название категории (напр. Аренда, Логистика)', max_length=100, unique=True, verbose_name='Название')),
                ('short_name', models.CharField(blank=True, help_text='Короткое название для отчётов', max_length=20, verbose_name='Сокращение')),
                ('category_type', models.CharField(choices=[('OPERATIONAL', 'Операционные'), ('ADMINISTRATIVE', 'Административные'), ('SALARY', 'Зарплаты'), ('MARKETING', 'Маркетинг'), ('TAX', 'Налоги и сборы'), ('OTHER', 'Прочие')], default='OTHER', max_length=20, verbose_name='Тип категории')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('order', models.PositiveIntegerField(default=0, help_text='Порядок отображения в списке (меньше = выше)', verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Категория расходов',
                'verbose_name_plural': 'Категории расходов',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='newinvoice',
            name='attachment',
            field=models.FileField(blank=True, help_text='PDF или фото счёта/инвойса', null=True, upload_to='invoices/attachments/%Y/%m/', verbose_name='Вложение'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='attachment',
            field=models.FileField(blank=True, help_text='Чек, квитанция или подтверждение оплаты', null=True, upload_to='transactions/attachments/%Y/%m/', verbose_name='Вложение'),
        ),
        migrations.AddField(
            model_name='newinvoice',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Категория для учёта доходов/расходов (напр. Логистика, Аренда)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='core.expensecategory', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Категория расхода/дохода. При привязке к инвойсу берётся автоматически.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='core.expensecategory', verbose_name='Категория'),
        ),
        migrations.RunPython(create_default_categories, migrations.RunPython.noop),
    ]
