# Generated by Django 5.1.7 on 2026-02-09 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0112_expense_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransaction',
            name='matched_invoice',
            field=models.ForeignKey(blank=True, help_text='Инвойс, к которому относится эта банковская операция', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_transactions', to='core.newinvoice', verbose_name='Связанный инвойс'),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='matched_transaction',
            field=models.ForeignKey(blank=True, help_text='Внутренняя транзакция (оплата), соответствующая этой банковской операции', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_transactions', to='core.transaction', verbose_name='Связанная транзакция'),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='reconciliation_note',
            field=models.CharField(blank=True, default='', help_text='Комментарий при ручном сопоставлении', max_length=255, verbose_name='Заметка сопоставления'),
        ),
        migrations.AddField(
            model_name='newinvoice',
            name='external_number',
            field=models.CharField(blank=True, default='', help_text='Номер с бумажного/PDF счёта от поставщика (для входящих инвойсов)', max_length=100, verbose_name='Номер счёта контрагента'),
        ),
    ]
