# Generated by Django 5.1.7 on 2026-02-09 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0113_invoice_bank_reconciliation'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransaction',
            name='reconciliation_skipped',
            field=models.BooleanField(default=False, help_text='Отметьте для операций, не связанных с инвойсами (комиссии, обмены валют и т.д.)', verbose_name='Не требует привязки'),
        ),
    ]
