# Generated by Django 5.1.7 on 2026-02-10 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0114_add_reconciliation_skipped'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='container',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'UNLOADED'), _negated=True), models.Q(('warehouse__isnull', False), ('unload_date__isnull', False)), _connector='OR'), name='container_unloaded_requires_warehouse_and_date'),
        ),
    ]
