# Generated by Django 5.1.7 on 2026-02-19 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0116_fix_carservice_service_type_check'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationlog',
            name='car',
            field=models.ForeignKey(blank=True, help_text='Для уведомлений о разгрузке ТС без контейнера', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.car', verbose_name='ТС'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='container',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.container', verbose_name='Контейнер'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='notification_type',
            field=models.CharField(choices=[('PLANNED', 'Планируемая разгрузка'), ('UNLOADED', 'Разгрузка выполнена'), ('CAR_UNLOADED', 'Разгрузка ТС (без контейнера)')], max_length=20, verbose_name='Тип уведомления'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['car', 'notification_type'], name='core_notifi_car_id_4d02a7_idx'),
        ),
    ]
