# Generated by Django 5.1.7 on 2026-02-19 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0117_standalone_car_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='unload_site',
            field=models.SmallIntegerField(choices=[(1, 'Площадка 1'), (2, 'Площадка 2'), (3, 'Площадка 3')], default=1, verbose_name='Площадка'),
        ),
        migrations.AddField(
            model_name='container',
            name='unload_site',
            field=models.SmallIntegerField(choices=[(1, 'Площадка 1'), (2, 'Площадка 2'), (3, 'Площадка 3')], default=1, verbose_name='Площадка'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='address2',
            field=models.CharField(blank=True, max_length=300, verbose_name='Адрес площадки 2'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='address2_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название площадки 2'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='address3',
            field=models.CharField(blank=True, max_length=300, verbose_name='Адрес площадки 3'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='address3_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название площадки 3'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='address_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название площадки 1'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='address',
            field=models.CharField(blank=True, max_length=300, verbose_name='Адрес площадки 1'),
        ),
    ]
