# Generated by Django 5.1.7 on 2026-02-19 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0119_set_default_address_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='unload_site',
            field=models.SmallIntegerField(choices=[(1, 'Площадка 1'), (2, 'Площадка 2'), (3, 'Площадка 3')], default=1, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='container',
            name='unload_site',
            field=models.SmallIntegerField(choices=[(1, 'Площадка 1'), (2, 'Площадка 2'), (3, 'Площадка 3')], default=1, verbose_name='Адрес'),
        ),
    ]
