# Generated by Django 5.1.7 on 2026-03-08 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0120_unload_site_verbose_name'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='car',
            name='core_car_vin_60390e_idx',
        ),
        migrations.AddField(
            model_name='newinvoice',
            name='currency',
            field=models.CharField(choices=[('EUR', 'EUR'), ('USD', 'USD'), ('GBP', 'GBP')], default='EUR', max_length=3, verbose_name='Валюта'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='currency',
            field=models.CharField(choices=[('EUR', 'EUR'), ('USD', 'USD'), ('GBP', 'GBP')], default='EUR', max_length=3, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='containerphoto',
            name='photo_type',
            field=models.CharField(choices=[('LOADING', 'Погрузка'), ('UNLOADING', 'Разгрузка'), ('IN_CONTAINER', 'В контейнере'), ('SEAL', 'Пломба'), ('GENERAL', 'Общее')], default='GENERAL', max_length=20, verbose_name='Тип фото'),
        ),
    ]
