# Generated by Django 5.1.7 on 2026-03-10 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0121_add_currency_and_transaction_validation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(upload_to='invoice_audits/', verbose_name='PDF файл')),
                ('original_filename', models.CharField(blank=True, max_length=255, verbose_name='Имя файла')),
                ('counterparty_detected', models.CharField(blank=True, max_length=200, verbose_name='Контрагент')),
                ('invoice_number', models.CharField(blank=True, max_length=100, verbose_name='Номер счёта')),
                ('invoice_date', models.DateField(blank=True, null=True, verbose_name='Дата счёта')),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Сумма счёта')),
                ('currency', models.CharField(default='EUR', max_length=3, verbose_name='Валюта')),
                ('raw_extracted', models.JSONField(blank=True, default=dict, verbose_name='Извлечённые данные (LLM)')),
                ('discrepancies', models.JSONField(blank=True, default=list, verbose_name='Расхождения')),
                ('status', models.CharField(choices=[('PENDING', 'Ожидает обработки'), ('PROCESSING', 'Обрабатывается'), ('OK', 'Всё совпадает'), ('HAS_ISSUES', 'Есть расхождения'), ('ERROR', 'Ошибка обработки')], default='PENDING', max_length=20, verbose_name='Статус')),
                ('error_message', models.TextField(blank=True, verbose_name='Сообщение об ошибке')),
                ('cars_found', models.IntegerField(default=0, verbose_name='Машин найдено в системе')),
                ('cars_missing', models.IntegerField(default=0, verbose_name='Машин нет в системе')),
                ('issues_count', models.IntegerField(default=0, verbose_name='Расхождений')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружен')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Обработан')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Загрузил')),
            ],
            options={
                'verbose_name': 'Проверка счёта',
                'verbose_name_plural': 'Проверки счетов',
                'ordering': ['-created_at'],
            },
        ),
    ]
