# Generated by Django 5.1.7 on 2026-03-10 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0122_invoice_audit'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counterparty', models.CharField(max_length=200, verbose_name='Контрагент')),
                ('service_type', models.CharField(choices=[('UNLOADING', 'Разгрузка/Погрузка'), ('THS', 'THS (портовые сборы)'), ('STORAGE', 'Хранение'), ('TRANSPORT', 'Транспорт'), ('DECLARATION', 'Декларация'), ('BDK', 'BDK'), ('DOCS', 'Документы'), ('COMPENSATION', 'Компенсация'), ('OTHER', 'Прочее')], max_length=20, verbose_name='Тип услуги')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('storage_days', models.IntegerField(default=0, verbose_name='Платных дней (хранение)')),
                ('vin', models.CharField(blank=True, max_length=20, verbose_name='VIN')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Описание из счёта')),
                ('reviewed', models.BooleanField(default=False, verbose_name='Проверено')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата проверки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_costs', to='core.invoiceaudit', verbose_name='Счёт')),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_costs', to='core.car', verbose_name='Машина')),
            ],
            options={
                'verbose_name': 'Затрата от поставщика',
                'verbose_name_plural': 'Затраты от поставщиков',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['car', 'service_type'], name='core_suppli_car_id_73585e_idx'), models.Index(fields=['vin'], name='core_suppli_vin_c7632a_idx'), models.Index(fields=['audit'], name='core_suppli_audit_i_0cb0db_idx')],
            },
        ),
    ]
