# Generated by Django 5.1.7 on 2026-03-10 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0123_supplier_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliercost',
            name='car_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_costs', to='core.carservice', verbose_name='Услуга в карточке'),
        ),
        migrations.AddField(
            model_name='suppliercost',
            name='source',
            field=models.CharField(choices=[('INVOICE', 'Из инвойса (PDF)'), ('MANUAL', 'Ручной ввод')], default='INVOICE', max_length=10, verbose_name='Источник'),
        ),
        migrations.AlterField(
            model_name='suppliercost',
            name='audit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_costs', to='core.invoiceaudit', verbose_name='Счёт'),
        ),
        migrations.AddIndex(
            model_name='suppliercost',
            index=models.Index(fields=['car_service'], name='core_suppli_car_ser_c48473_idx'),
        ),
    ]
