# Generated by Django 5.1.7 on 2026-03-10 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0124_supplier_cost_link_carservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceaudit',
            name='invoice',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit', to='core.newinvoice', verbose_name='Инвойс'),
        ),
    ]
