# Generated by Django 5.1.7 on 2026-03-10 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0125_invoice_audit_link_newinvoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='client_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Цена из CarService (для сравнения во входящих инвойсах)', max_digits=15, null=True, verbose_name='Цена для клиента'),
        ),
    ]
