# Generated by Django 5.1.7 on 2026-03-10 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0126_add_client_price_to_invoiceitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, help_text='Автоматически рассчитывается: количество × цена', max_digits=15, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Цена за единицу'),
        ),
    ]
