# Generated by Django 5.1.7 on 2026-03-15 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0127_allow_negative_invoice_item_prices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrier',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Название перевозчика'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Имя клиента'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(db_index=True, default='Caromoto Lithuania', max_length=100, verbose_name='Название компании'),
        ),
        migrations.AlterField(
            model_name='line',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Название линии'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Название склада'),
        ),
    ]
