# Generated by Django 5.1.7 on 2026-04-01 20:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0128_add_name_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='newinvoice',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('issuer_carrier__isnull', True), ('issuer_company__isnull', False), ('issuer_line__isnull', True), ('issuer_warehouse__isnull', True)), models.Q(('issuer_carrier__isnull', True), ('issuer_company__isnull', True), ('issuer_line__isnull', True), ('issuer_warehouse__isnull', False)), models.Q(('issuer_carrier__isnull', True), ('issuer_company__isnull', True), ('issuer_line__isnull', False), ('issuer_warehouse__isnull', True)), models.Q(('issuer_carrier__isnull', False), ('issuer_company__isnull', True), ('issuer_line__isnull', True), ('issuer_warehouse__isnull', True)), _connector='OR'), name='invoice_exactly_one_issuer'),
        ),
        migrations.AddConstraint(
            model_name='newinvoice',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('recipient_carrier__isnull', True), ('recipient_client__isnull', False), ('recipient_company__isnull', True), ('recipient_line__isnull', True), ('recipient_warehouse__isnull', True)), models.Q(('recipient_carrier__isnull', True), ('recipient_client__isnull', True), ('recipient_company__isnull', True), ('recipient_line__isnull', True), ('recipient_warehouse__isnull', False)), models.Q(('recipient_carrier__isnull', True), ('recipient_client__isnull', True), ('recipient_company__isnull', True), ('recipient_line__isnull', False), ('recipient_warehouse__isnull', True)), models.Q(('recipient_carrier__isnull', False), ('recipient_client__isnull', True), ('recipient_company__isnull', True), ('recipient_line__isnull', True), ('recipient_warehouse__isnull', True)), models.Q(('recipient_carrier__isnull', True), ('recipient_client__isnull', True), ('recipient_company__isnull', False), ('recipient_line__isnull', True), ('recipient_warehouse__isnull', True)), _connector='OR'), name='invoice_exactly_one_recipient'),
        ),
    ]
