# Generated by Django 5.1.7 on 2026-04-03
# Manually adjusted: CarService unique_together never existed in DB

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0129_add_invoice_integrity_constraints'),
    ]

    operations = [
        # --- CarService: constraint never existed in DB, only update Django state ---
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterUniqueTogether(
                    name='carservice',
                    unique_together=set(),
                ),
            ],
            database_operations=[],
        ),

        # --- All other models: constraint exists in DB, drop normally ---
        migrations.AlterUniqueTogether(
            name='bankaccount',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='banktransaction',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='carriertruck',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='deletedcarservice',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='linethscoefficient',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='siteproinvoicesync',
            unique_together=set(),
        ),

        # --- Add code field to all service models ---
        migrations.AddField(
            model_name='carrierservice',
            name='code',
            field=models.SlugField(blank=True, default='', help_text='Машинный идентификатор услуги (напр. unloading, storage, ths). Используется для программной привязки.', verbose_name='Код'),
        ),
        migrations.AddField(
            model_name='companyservice',
            name='code',
            field=models.SlugField(blank=True, default='', help_text='Машинный идентификатор услуги (напр. unloading, storage, ths). Используется для программной привязки.', verbose_name='Код'),
        ),
        migrations.AddField(
            model_name='lineservice',
            name='code',
            field=models.SlugField(blank=True, default='', help_text='Машинный идентификатор услуги (напр. unloading, storage, ths). Используется для программной привязки.', verbose_name='Код'),
        ),
        migrations.AddField(
            model_name='warehouseservice',
            name='code',
            field=models.SlugField(blank=True, default='', help_text='Машинный идентификатор услуги (напр. unloading, storage, ths). Используется для программной привязки.', verbose_name='Код'),
        ),

        # --- Alter help_text on add_by_default (from abstract base) ---
        migrations.AlterField(
            model_name='carrierservice',
            name='add_by_default',
            field=models.BooleanField(default=False, help_text='Автоматически добавлять эту услугу при создании автомобиля', verbose_name='Добавлять по умолчанию'),
        ),
        migrations.AlterField(
            model_name='companyservice',
            name='add_by_default',
            field=models.BooleanField(default=False, help_text='Автоматически добавлять эту услугу при создании автомобиля', verbose_name='Добавлять по умолчанию'),
        ),
        migrations.AlterField(
            model_name='lineservice',
            name='add_by_default',
            field=models.BooleanField(default=False, help_text='Автоматически добавлять эту услугу при создании автомобиля', verbose_name='Добавлять по умолчанию'),
        ),
        migrations.AlterField(
            model_name='warehouseservice',
            name='add_by_default',
            field=models.BooleanField(default=False, help_text='Автоматически добавлять эту услугу при создании автомобиля', verbose_name='Добавлять по умолчанию'),
        ),

        # --- Create new UniqueConstraint for all models ---
        migrations.AddConstraint(
            model_name='bankaccount',
            constraint=models.UniqueConstraint(fields=('connection', 'external_id'), name='unique_bank_account'),
        ),
        migrations.AddConstraint(
            model_name='banktransaction',
            constraint=models.UniqueConstraint(fields=('connection', 'external_id'), name='unique_bank_transaction'),
        ),
        migrations.AddConstraint(
            model_name='carriertruck',
            constraint=models.UniqueConstraint(fields=('carrier', 'truck_number', 'trailer_number'), name='unique_carrier_truck_trailer'),
        ),
        migrations.AddConstraint(
            model_name='carservice',
            constraint=models.UniqueConstraint(fields=('car', 'service_type', 'service_id'), name='unique_car_service'),
        ),
        migrations.AddConstraint(
            model_name='deletedcarservice',
            constraint=models.UniqueConstraint(fields=('car', 'service_type', 'service_id'), name='unique_deleted_car_service'),
        ),
        migrations.AddConstraint(
            model_name='linethscoefficient',
            constraint=models.UniqueConstraint(fields=('line', 'vehicle_type'), name='unique_line_vehicle_type'),
        ),
        migrations.AddConstraint(
            model_name='siteproinvoicesync',
            constraint=models.UniqueConstraint(fields=('connection', 'invoice'), name='unique_sitepro_invoice_sync'),
        ),
    ]
