# Generated by Django 5.1.7 on 2026-04-06 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0132_warehousesite_clientemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankconnection',
            name='bank_type',
            field=models.CharField(choices=[('REVOLUT', 'Revolut Business'), ('PAYSERA', 'Paysera'), ('OTHER', 'Другой банк')], default='REVOLUT', max_length=20, verbose_name='Тип банка'),
        ),
    ]
