# Generated by Django 5.1.7 on 2026-04-06 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0133_add_paysera_bank_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='newinvoice',
            name='document_type',
            field=models.CharField(choices=[('INVOICE', 'Счёт-фактура (PARDP)'), ('PROFORMA', 'Коммерческое предложение (AV)')], default='PROFORMA', help_text='INVOICE (PARDP) — бухгалтерский инвойс, синхронизируется с site.pro. PROFORMA (AV) — коммерческое предложение, не экспортируется.', max_length=10, verbose_name='Тип документа'),
        ),
        migrations.AlterField(
            model_name='newinvoice',
            name='number',
            field=models.CharField(help_text='Уникальный номер (генерируется автоматически: PARDP-NNNNNN или AV-NNNNNNNN)', max_length=50, unique=True, verbose_name='Номер документа'),
        ),
    ]
