# Generated by Django 5.1.7 on 2026-04-07 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0136_fix_av_padding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newinvoice',
            name='document_type',
            field=models.CharField(choices=[('INVOICE', 'Счёт-фактура (PARDP)'), ('PROFORMA', 'Коммерческое предложение (AV)'), ('INVOICE_BLC', 'Неофициальный счёт (PARBLC)'), ('PROFORMA_BLC', 'Неофициальное предложение (AVBLC)')], default='PROFORMA', help_text='PARDP — официальный счёт (site.pro). AV — коммерческое предложение. PARBLC — неофициальный счёт (нал). AVBLC — неофициальное предложение.', max_length=15, verbose_name='Тип документа'),
        ),
        migrations.AlterField(
            model_name='newinvoice',
            name='number',
            field=models.CharField(help_text='Уникальный номер (генерируется автоматически по серии)', max_length=50, unique=True, verbose_name='Номер документа'),
        ),
    ]
