# Generated by Django 5.1.7 on 2026-04-07 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0137_expand_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='newinvoice',
            name='linked_invoice',
            field=models.OneToOneField(blank=True, help_text='Пара: реальный BLC-счёт ↔ официальный счёт на ту же сумму', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_from', to='core.newinvoice', verbose_name='Связанный счёт'),
        ),
    ]
