# Generated by Django 5.1.7 on 2026-04-07 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0138_add_linked_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newinvoice',
            name='document_type',
            field=models.CharField(choices=[('INVOICE', 'Счёт-фактура (PARDP)'), ('PROFORMA', 'Коммерческое предложение (AV)'), ('INVOICE_BLC', 'Неофициальный счёт (PARBLC)'), ('PROFORMA_BLC', 'Неофициальное предложение (AVBLC)'), ('INVOICE_FACT', 'Входящий счёт от контрагента (FACT)')], default='PROFORMA', help_text='PARDP — официальный счёт (site.pro). AV — коммерческое предложение. PARBLC — неофициальный счёт (нал). AVBLC — неофициальное предложение. FACT — входящий счёт от контрагента к оплате.', max_length=15, verbose_name='Тип документа'),
        ),
    ]
