# Generated by Django 5.1.7 on 2026-04-08 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0139_add_invoice_fact_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='newinvoice',
            name='skip_ai_comparison',
            field=models.BooleanField(default=False, help_text='AI извлечёт данные из PDF, но не будет сверять с расходами в системе', verbose_name='Без сверки с базой'),
        ),
    ]
