# Generated by Django 5.1.7 on 2026-04-12 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0141_add_personal_expense_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='receipt_data',
            field=models.JSONField(blank=True, help_text='AI-распарсенные данные из фото чека (магазин, товары, суммы)', null=True, verbose_name='Данные чека'),
        ),
    ]
