# Generated by Django 5.1.7 on 2026-04-15 10:27

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0142_add_receipt_data_to_transaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: Revolut, SEB, Swedbank', max_length=100, verbose_name='Название')),
                ('last_four', models.CharField(blank=True, default='', max_length=4, verbose_name='Последние 4 цифры')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Баланс')),
                ('color', models.CharField(default='#6366f1', help_text='HEX-цвет для отображения на дашборде', max_length=7, verbose_name='Цвет')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
            ],
            options={
                'verbose_name': 'Личная карта',
                'verbose_name_plural': 'Личные карты',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PersonalTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_type', models.CharField(choices=[('CASH_TO_CARD', 'Наличные → Карта'), ('CARD_TO_CASH', 'Карта → Наличные'), ('CARD_TO_CARD', 'Карта → Карта'), ('CARD_INCOME', 'Поступление на карту'), ('CARD_EXPENSE', 'Расход с карты')], max_length=20, verbose_name='Тип операции')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Сумма')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('category', models.ForeignKey(blank=True, help_text='Для расходов с карты', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_transfers', to='core.expensecategory', verbose_name='Категория')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_transfers', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('from_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='core.personalcard', verbose_name='Карта-источник')),
                ('linked_transaction', models.ForeignKey(blank=True, help_text='Транзакция в кассе (для переводов нал↔карта)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_transfers', to='core.transaction', verbose_name='Связанная транзакция')),
                ('to_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='core.personalcard', verbose_name='Карта-получатель')),
            ],
            options={
                'verbose_name': 'Личный перевод',
                'verbose_name_plural': 'Личные переводы',
                'ordering': ['-date'],
            },
        ),
    ]
