# Generated by Django 5.1.7 on 2026-04-16 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0143_personalcard_personaltransfer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newinvoice',
            name='document_type',
            field=models.CharField(choices=[('INVOICE', 'Счёт-фактура (PARDP)'), ('PROFORMA', 'Коммерческое предложение (AV)'), ('INVOICE_BLC', 'Неофициальный счёт (PARBLC)'), ('PROFORMA_BLC', 'Неофициальное предложение (AVBLC)'), ('INVOICE_FACT', 'Входящий счёт от контрагента (FACT)'), ('INVOICE_INCBLC', 'Входящий неофициальный счёт (INCBLC)')], default='PROFORMA', help_text='PARDP — официальный счёт (site.pro). AV — коммерческое предложение. PARBLC — исходящий неофициальный счёт (нал). AVBLC — неофиц. предложение. FACT — входящий официальный счёт от контрагента. INCBLC — входящий неофициальный счёт (нал, не в site.pro).', max_length=15, verbose_name='Тип документа'),
        ),
    ]
