# Generated by Django 5.1.7 on 2026-04-16 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0144_add_invoice_incblc_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransaction',
            name='expense_id',
            field=models.CharField(blank=True, default='', help_text='ID связанного expense в Revolut Business (для подгрузки чеков)', max_length=100, verbose_name='Revolut Expense ID'),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='receipt_fetched_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Чек загружен'),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='receipt_file',
            field=models.FileField(blank=True, help_text='Файл чека, автоматически скачанный из Revolut Expenses API', null=True, upload_to='bank_receipts/%Y/%m/', verbose_name='Чек из Revolut'),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='revolut_category',
            field=models.CharField(blank=True, default='', help_text='Категория, назначенная в приложении Revolut (labels/category)', max_length=100, verbose_name='Категория Revolut'),
        ),
    ]
