# Generated by Django 5.1.7 on 2026-04-16 20:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0145_add_revolut_receipt_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='newinvoice',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Черновик'), ('ISSUED', 'Выставлен'), ('PARTIALLY_PAID', 'Частично оплачен'), ('PAID', 'Оплачен'), ('LINKED_PAID', 'Оплачен косвенно (связанный)'), ('OVERDUE', 'Просрочен'), ('CANCELLED', 'Отменен')], default='DRAFT', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['matched_invoice'], name='bt_matched_invoice_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['matched_transaction'], name='bt_matched_tx_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['reconciliation_skipped', 'created_at'], name='bt_skipped_created_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['currency', 'created_at'], name='bt_ccy_created_idx'),
        ),
        migrations.AddIndex(
            model_name='newinvoice',
            index=models.Index(fields=['document_type', 'date'], name='core_newinv_documen_53d434_idx'),
        ),
        migrations.AddIndex(
            model_name='newinvoice',
            index=models.Index(fields=['document_type', 'status'], name='core_newinv_documen_f22529_idx'),
        ),
        migrations.AddIndex(
            model_name='newinvoice',
            index=models.Index(fields=['linked_invoice'], name='core_newinv_linked__119edd_idx'),
        ),
    ]
