# Generated by Django 5.1.7 on 2026-04-18 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0148_sitepro_item_calc_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteproconnection',
            name='invoice_series',
            field=models.CharField(blank=True, default='', help_text='Серия нумерации инвойсов (например: PARDP). Шлётся текстовым полем series в sales/create.', max_length=20, verbose_name='Серия инвойсов в site.pro'),
        ),
    ]
