# Generated by Django 5.1.7 on 2026-04-18 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0149_alter_siteproconnection_invoice_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='labels_printed_at',
            field=models.DateTimeField(blank=True, help_text='Дата последней печати наклеек для этого контейнера. Автоматически проставляется при открытии листа печати.', null=True, verbose_name='Наклейки напечатаны'),
        ),
    ]
