# Generated by Django 5.1.7 on 2026-04-18 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0151_add_container_booking_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='GmailSyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(help_text='Gmail-адрес ящика, к которому выдан refresh_token.', max_length=254, unique=True)),
                ('last_history_id', models.BigIntegerField(blank=True, help_text='Максимальный обработанный historyId. NULL → первый прогон.', null=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Состояние Gmail-синка',
                'verbose_name_plural': 'Состояние Gmail-синка',
            },
        ),
        migrations.CreateModel(
            name='ContainerEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(db_index=True, help_text='RFC 5322 Message-ID из заголовков письма.', max_length=500, unique=True, verbose_name='Message-ID')),
                ('thread_id', models.CharField(db_index=True, help_text='Gmail threadId (или первый Message-ID в треде, если threadId нет).', max_length=500, verbose_name='Thread ID')),
                ('in_reply_to', models.CharField(blank=True, default='', max_length=500)),
                ('references', models.TextField(blank=True, default='', help_text='Пробел-разделённый список Message-ID из заголовка References.')),
                ('direction', models.CharField(choices=[('INCOMING', 'Входящее'), ('OUTGOING', 'Исходящее')], default='INCOMING', max_length=10, verbose_name='Направление')),
                ('from_addr', models.CharField(max_length=500, verbose_name='От')),
                ('to_addrs', models.TextField(blank=True, default='', verbose_name='Кому')),
                ('cc_addrs', models.TextField(blank=True, default='', verbose_name='Копия')),
                ('subject', models.CharField(blank=True, default='', max_length=1000, verbose_name='Тема')),
                ('body_text', models.TextField(blank=True, default='', verbose_name='Тело (text)')),
                ('body_html', models.TextField(blank=True, default='', verbose_name='Тело (HTML)')),
                ('snippet', models.CharField(blank=True, default='', help_text='Короткое превью от Gmail API.', max_length=500)),
                ('received_at', models.DateTimeField(db_index=True, verbose_name='Получено')),
                ('gmail_id', models.CharField(blank=True, db_index=True, default='', help_text='Внутренний id Gmail API (messages.get → id).', max_length=64)),
                ('gmail_history_id', models.BigIntegerField(blank=True, help_text='historyId на момент получения письма — нужен для incremental sync.', null=True)),
                ('labels_json', models.JSONField(blank=True, default=list, help_text='Массив Gmail labels (INBOX, SENT, STARRED и т.д.).')),
                ('attachments_json', models.JSONField(blank=True, default=list, help_text='[{filename, size, content_type, storage_path, attachment_id}]. storage_path пуст, если вложение пропущено из-за размера.')),
                ('matched_by', models.CharField(choices=[('CONTAINER_NUMBER', 'По номеру контейнера'), ('BOOKING_NUMBER', 'По номеру букинга'), ('THREAD', 'По треду'), ('MANUAL', 'Привязано вручную'), ('UNMATCHED', 'Не привязано')], default='UNMATCHED', max_length=20, verbose_name='Как сопоставлено')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано в UI')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('container', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails', to='core.container', verbose_name='Контейнер')),
            ],
            options={
                'verbose_name': 'Письмо контейнера',
                'verbose_name_plural': 'Письма контейнеров',
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['container', '-received_at'], name='core_contai_contain_6add97_idx'), models.Index(fields=['thread_id', 'received_at'], name='core_contai_thread__ce463f_idx'), models.Index(fields=['matched_by', '-received_at'], name='core_contai_matched_09c246_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('gmail_id', ''), _negated=True), fields=('gmail_id',), name='containeremail_unique_gmail_id_nonempty')],
            },
        ),
    ]
