# Generated by Django 5.1.7 on 2026-04-19 07:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0153_add_container_email_sender'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например "Таможня Klaipeda" или "MSC Agents".', max_length=120, unique=True, verbose_name='Название')),
                ('description', models.CharField(blank=True, default='', help_text='Опционально — контекст, когда использовать группу.', max_length=255, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
            ],
            options={
                'verbose_name': 'Email-группа',
                'verbose_name_plural': 'Email-группы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmailGroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('display_name', models.CharField(blank=True, default='', help_text='Если заполнено, в поле «Кому» подставится как "Имя <email@...>". Иначе — только email.', max_length=120, verbose_name='Имя (опционально)')),
                ('position', models.PositiveIntegerField(default=0, help_text='Меньше → выше в списке. При равных — по email.', verbose_name='Порядок')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core.emailgroup', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Участник email-группы',
                'verbose_name_plural': 'Участники email-группы',
                'ordering': ['group', 'position', 'email'],
                'constraints': [models.UniqueConstraint(fields=('group', 'email'), name='emailgroupmember_unique_email_per_group')],
            },
        ),
    ]
