# Generated by Django 5.1.7 on 2026-04-19 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0154_add_email_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID контрагента')),
                ('name', models.CharField(help_text='ФИО или имя контактного лица.', max_length=200, verbose_name='Имя')),
                ('position', models.CharField(blank=True, default='', help_text='Например "Import Manager", "Таможенный брокер", "Водитель".', max_length=200, verbose_name='Должность')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Комментарий')),
                ('is_primary', models.BooleanField(default=False, help_text='Если у контрагента несколько контактов — используйте для главного.', verbose_name='Основной')),
                ('is_orphan', models.BooleanField(default=False, help_text='Создан автоматически при отправке email — не привязан к контрагенту. Привяжите вручную через админку.', verbose_name='Осиротевший')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(blank=True, help_text='Модель контрагента (Линия / Перевозчик / Клиент / Склад / Компания).', null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Тип контрагента')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ContactEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='Email')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Основной')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='core.contact', verbose_name='Контакт')),
            ],
            options={
                'verbose_name': 'Email контакта',
                'verbose_name_plural': 'Emails контактов',
                'ordering': ['contact', '-is_primary', 'position', 'email'],
            },
        ),
        migrations.CreateModel(
            name='ContactPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Основной')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='core.contact', verbose_name='Контакт')),
            ],
            options={
                'verbose_name': 'Телефон контакта',
                'verbose_name_plural': 'Телефоны контактов',
                'ordering': ['contact', '-is_primary', 'position', 'phone'],
            },
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['content_type', 'object_id'], name='core_contac_content_92c564_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['is_orphan'], name='core_contac_is_orph_0bec8b_idx'),
        ),
        migrations.AddConstraint(
            model_name='contactemail',
            constraint=models.UniqueConstraint(fields=('contact', 'email'), name='contactemail_unique_email_per_contact'),
        ),
    ]
