# Generated by Django 5.1.7 on 2026-04-20 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0157_containeremaillink_is_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='containeremail',
            name='matched_by',
            field=models.CharField(choices=[('CONTAINER_NUMBER', 'По номеру контейнера'), ('BOOKING_NUMBER', 'По номеру букинга'), ('THREAD', 'По треду'), ('MANUAL', 'Привязано вручную'), ('UNMATCHED', 'Не привязано'), ('VIN', 'По VIN машины')], default='UNMATCHED', max_length=20, verbose_name='Как сопоставлено'),
        ),
        migrations.AlterField(
            model_name='containeremaillink',
            name='matched_by',
            field=models.CharField(choices=[('CONTAINER_NUMBER', 'По номеру контейнера'), ('BOOKING_NUMBER', 'По номеру букинга'), ('THREAD', 'По треду'), ('MANUAL', 'Привязано вручную'), ('UNMATCHED', 'Не привязано'), ('VIN', 'По VIN машины')], default='UNMATCHED', help_text='Причина связи именно с этим контейнером. Может отличаться от ContainerEmail.matched_by (первичная причина).', max_length=20, verbose_name='Как сопоставлено'),
        ),
        migrations.CreateModel(
            name='CarEmailLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matched_by', models.CharField(choices=[('CONTAINER_NUMBER', 'По номеру контейнера'), ('BOOKING_NUMBER', 'По номеру букинга'), ('THREAD', 'По треду'), ('MANUAL', 'Привязано вручную'), ('UNMATCHED', 'Не привязано'), ('VIN', 'По VIN машины')], default='UNMATCHED', help_text='Обычно VIN; MANUAL — если пришло из карточки Car.', max_length=20, verbose_name='Как сопоставлено')),
                ('is_read', models.BooleanField(default=False, help_text='Per-ссылка: в разных карточках авто флаг независим.', verbose_name='Прочитано в этой карточке авто')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_links', to='core.car')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_links', to='core.containeremail')),
            ],
            options={
                'verbose_name': 'Связь письма с машиной',
                'verbose_name_plural': 'Связи писем с машинами',
            },
        ),
        migrations.AddField(
            model_name='containeremail',
            name='cars',
            field=models.ManyToManyField(blank=True, related_name='emails', through='core.CarEmailLink', to='core.car', verbose_name='Машины (по VIN)'),
        ),
        migrations.AddIndex(
            model_name='caremaillink',
            index=models.Index(fields=['car', 'is_read'], name='core_carema_car_id_3f4250_idx'),
        ),
        migrations.AddConstraint(
            model_name='caremaillink',
            constraint=models.UniqueConstraint(fields=('email', 'car'), name='caremaillink_unique_email_car'),
        ),
    ]
