# Generated by Django 5.1.7 on 2026-04-20 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0158_car_email_link'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='containeremail',
            name='needs_reply',
            field=models.BooleanField(db_index=True, default=False, help_text='Помечено вручную: письмо, на которое нужно вернуться и ответить.', verbose_name='Требует ответа'),
        ),
        migrations.AddField(
            model_name='containeremail',
            name='needs_reply_set_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Флаг установлен'),
        ),
        migrations.AddField(
            model_name='containeremail',
            name='needs_reply_set_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Установил флаг'),
        ),
    ]
