# Generated by Django 5.1.7 on 2026-04-21 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0159_add_email_needs_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='related_client',
            field=models.ForeignKey(blank=True, help_text='Оптовик или посредник, от имени которого фактически шёл платеж (например, Caromoto Moldova, если физлицо платит от её имени).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_transactions', to='core.client', verbose_name='Связанный клиент'),
        ),
    ]
