# Generated by Django 5.1.7 on 2026-04-24 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0162_emailingestfilter'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='emailingestfilter',
            new_name='core_emaili_is_acti_925a72_idx',
            old_name='core_emaili_is_acti_6f7a1b_idx',
        ),
        migrations.AlterField(
            model_name='emailingestfilter',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
