# Generated by Django 5.1.7 on 2026-05-06 10:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0163_rename_core_emaili_is_acti_6f7a1b_idx_core_emaili_is_acti_925a72_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='newinvoice',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'CANCELLED'), _negated=True), fields=('auto_transport', 'recipient_client'), name='unique_autotransport_invoice_per_client'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('from_carrier__isnull', True), ('from_client__isnull', True), ('from_company__isnull', True), ('from_line__isnull', True), ('from_warehouse__isnull', True)), models.Q(('from_carrier__isnull', True), ('from_client__isnull', False), ('from_company__isnull', True), ('from_line__isnull', True), ('from_warehouse__isnull', True)), models.Q(('from_carrier__isnull', True), ('from_client__isnull', True), ('from_company__isnull', True), ('from_line__isnull', True), ('from_warehouse__isnull', False)), models.Q(('from_carrier__isnull', True), ('from_client__isnull', True), ('from_company__isnull', True), ('from_line__isnull', False), ('from_warehouse__isnull', True)), models.Q(('from_carrier__isnull', False), ('from_client__isnull', True), ('from_company__isnull', True), ('from_line__isnull', True), ('from_warehouse__isnull', True)), models.Q(('from_carrier__isnull', True), ('from_client__isnull', True), ('from_company__isnull', False), ('from_line__isnull', True), ('from_warehouse__isnull', True)), _connector='OR'), name='transaction_at_most_one_sender'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('to_carrier__isnull', True), ('to_client__isnull', True), ('to_company__isnull', True), ('to_line__isnull', True), ('to_warehouse__isnull', True)), models.Q(('to_carrier__isnull', True), ('to_client__isnull', False), ('to_company__isnull', True), ('to_line__isnull', True), ('to_warehouse__isnull', True)), models.Q(('to_carrier__isnull', True), ('to_client__isnull', True), ('to_company__isnull', True), ('to_line__isnull', True), ('to_warehouse__isnull', False)), models.Q(('to_carrier__isnull', True), ('to_client__isnull', True), ('to_company__isnull', True), ('to_line__isnull', False), ('to_warehouse__isnull', True)), models.Q(('to_carrier__isnull', False), ('to_client__isnull', True), ('to_company__isnull', True), ('to_line__isnull', True), ('to_warehouse__isnull', True)), models.Q(('to_carrier__isnull', True), ('to_client__isnull', True), ('to_company__isnull', False), ('to_line__isnull', True), ('to_warehouse__isnull', True)), _connector='OR'), name='transaction_at_most_one_recipient'),
        ),
    ]
