# Generated by Django 5.1.7 on 2026-05-07 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0164_newinvoice_unique_autotransport_invoice_per_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='НАЛИЧНЫЙ баланс контрагента. Положительный = нам должны, отрицательный = мы должны. Это техническое поле — для UI и расчётов используйте свойство ``total_balance``, которое учитывает безналичные транзакции и связанные инвойсы.', max_digits=15, verbose_name='Баланс (наличный)'),
        ),
    ]
