# Generated by Django 5.1.7 on 2026-05-07 18:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0165_alter_line_balance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='title_scan',
            field=models.FileField(blank=True, help_text='Сканированная копия физического титула. Привязывается автоматически при обработке скана через AI или вручную.', null=True, upload_to='title_scans/%Y/%m/', verbose_name='Скан тайтла (PDF)'),
        ),
        migrations.AddField(
            model_name='car',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Масса автомобиля в килограммах. При импорте из Dock Receipt (US) значение в lbs конвертируется автоматически (1 lb = 0.4535924 kg).', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Масса (кг)'),
        ),
        migrations.AddField(
            model_name='container',
            name='dock_receipt_scan',
            field=models.FileField(blank=True, help_text='Сканированная копия Dock Receipt. AI извлекает container_number, booking_number, VIN-ы машин и их массу.', null=True, upload_to='dock_receipts/%Y/%m/', verbose_name='Скан Dock Receipt (PDF)'),
        ),
        migrations.CreateModel(
            name='ScanProcessingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_type', models.CharField(choices=[('TITLE', 'Title (титул авто)'), ('DOCK_RECEIPT', 'Dock Receipt')], db_index=True, max_length=20, verbose_name='Тип скана')),
                ('status', models.CharField(choices=[('PENDING', 'Ожидает обработки'), ('PROCESSING', 'Обрабатывается AI'), ('NEEDS_REVIEW', 'Ожидает проверки'), ('APPLIED', 'Применено'), ('ERROR', 'Ошибка'), ('IGNORED', 'Проигнорировано')], db_index=True, default='PENDING', max_length=20, verbose_name='Статус')),
                ('original_file', models.FileField(help_text='PDF, загруженный пользователем (один документ = одна задача).', upload_to='scan_jobs/%Y/%m/', verbose_name='Исходный PDF')),
                ('extracted_data', models.JSONField(blank=True, help_text='JSON, полученный от Claude Vision API.', null=True, verbose_name='Извлечённые данные (AI)')),
                ('applied_changes', models.JSONField(blank=True, help_text="Что именно изменилось в Car/Container после нажатия 'Применить'.", null=True, verbose_name='Применённые изменения')),
                ('created_new_car', models.BooleanField(default=False, verbose_name='Создан новый Car')),
                ('created_new_container', models.BooleanField(default=False, verbose_name='Создан новый Container')),
                ('error_message', models.TextField(blank=True, verbose_name='Сообщение об ошибке')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Обработано AI')),
                ('applied_at', models.DateTimeField(blank=True, null=True, verbose_name='Применено')),
                ('applied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_jobs_applied', to=settings.AUTH_USER_MODEL, verbose_name='Применил')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_jobs_created', to=settings.AUTH_USER_MODEL, verbose_name='Загрузил')),
                ('linked_car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_jobs', to='core.car', verbose_name='Связанный автомобиль')),
                ('linked_container', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_jobs', to='core.container', verbose_name='Связанный контейнер')),
            ],
            options={
                'verbose_name': 'AI-обработка скана',
                'verbose_name_plural': 'AI-обработка сканов',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['status', '-created_at'], name='core_scanpr_status_14bc56_idx'), models.Index(fields=['scan_type', 'status'], name='core_scanpr_scan_ty_4cdd1a_idx')],
            },
        ),
    ]
