# Generated by Django 5.1.7 on 2026-05-11 21:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0167_rename_vin_mismatch_keys'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='container',
            index=models.Index(fields=['planned_unload_date'], name='core_contai_planned_6b3f41_idx'),
        ),
        migrations.AddIndex(
            model_name='container',
            index=models.Index(fields=['unloaded_status_at'], name='core_contai_unloade_e59815_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['method', 'date'], name='core_transa_method_6de39e_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['type', 'method', 'status'], name='core_transa_type_90e888_idx'),
        ),
    ]
