# Generated by Django 5.1.7 on 2026-05-13 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0168_perf_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='is_important',
            field=models.BooleanField(default=False, help_text='Пометить авто как требующее внимания. Пока галочка стоит — нельзя менять статус и нельзя добавлять авто в автовоз. Авто с этой пометкой автоматически попадает в раздел «Дела».', verbose_name='Важное'),
        ),
        migrations.AddField(
            model_name='car',
            name='notes',
            field=models.TextField(blank=True, help_text='Свободные примечания к авто. Видны во всплывающей подсказке у красного значка в списке авто.', verbose_name='Примечания'),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('deadline', models.DateTimeField(blank=True, help_text='Опционально. Без дедлайна — обычное напоминание.', null=True, verbose_name='Дедлайн')),
                ('priority', models.CharField(choices=[('LOW', 'Низкий'), ('MEDIUM', 'Средний'), ('HIGH', 'Высокий')], default='MEDIUM', max_length=10, verbose_name='Приоритет')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Выполнено')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Выполнено в')),
                ('completed_by', models.CharField(blank=True, max_length=100, verbose_name='Выполнил')),
                ('auto_created', models.BooleanField(default=False, help_text='True — дело создано из чекбокса «Важное» в карточке авто.', verbose_name='Создано автоматически')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('created_by', models.CharField(blank=True, max_length=100, verbose_name='Создал')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='core.car', verbose_name='Авто')),
                ('container', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='core.container', verbose_name='Контейнер')),
            ],
            options={
                'verbose_name': 'Дело',
                'verbose_name_plural': 'Дела',
                'ordering': ['is_completed', 'deadline', '-created_at'],
                'indexes': [models.Index(fields=['is_completed'], name='core_task_is_comp_b4edd9_idx'), models.Index(fields=['deadline'], name='core_task_deadlin_aa9504_idx'), models.Index(fields=['car'], name='core_task_car_id_7e2408_idx'), models.Index(fields=['container'], name='core_task_contain_9a2e5e_idx')],
            },
        ),
    ]
