# Generated by Django 5.1.7 on 2026-05-19 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0169_add_important_flag_and_tasks'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('cpu_percent', models.FloatField(help_text='Загрузка CPU в %, 0-100')),
                ('load_avg_1', models.FloatField(blank=True, help_text='Linux loadavg 1m', null=True)),
                ('mem_total_mb', models.IntegerField()),
                ('mem_used_mb', models.IntegerField()),
                ('mem_available_mb', models.IntegerField()),
                ('mem_percent', models.FloatField()),
                ('swap_total_mb', models.IntegerField(default=0)),
                ('swap_used_mb', models.IntegerField(default=0)),
                ('swap_percent', models.FloatField(default=0.0)),
                ('disk_total_gb', models.FloatField()),
                ('disk_used_gb', models.FloatField()),
                ('disk_percent', models.FloatField()),
                ('gunicorn_rss_mb', models.IntegerField(default=0, help_text='Sum RSS gunicorn workers')),
                ('celery_rss_mb', models.IntegerField(default=0)),
                ('daphne_rss_mb', models.IntegerField(default=0)),
                ('postgres_rss_mb', models.IntegerField(default=0)),
                ('redis_rss_mb', models.IntegerField(default=0)),
                ('mysql_rss_mb', models.IntegerField(default=0)),
                ('postgres_connections', models.IntegerField(default=0)),
                ('postgres_db_size_mb', models.FloatField(default=0.0)),
                ('postgres_cache_hit_ratio', models.FloatField(default=0.0, help_text='0-1')),
                ('redis_memory_mb', models.FloatField(default=0.0)),
                ('redis_clients', models.IntegerField(default=0)),
                ('data', models.JSONField(blank=True, default=dict, help_text='Сырой расширенный снимок')),
            ],
            options={
                'db_table': 'core_system_metric',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='sm_created_at_desc_idx')],
            },
        ),
        migrations.CreateModel(
            name='UptimeCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ok', models.BooleanField()),
                ('response_ms', models.FloatField(blank=True, null=True)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('error', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'core_uptime_check',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='uc_created_at_desc_idx'), models.Index(fields=['ok', '-created_at'], name='uc_ok_created_idx')],
            },
        ),
    ]
