# Generated by Django 5.2.14 on 2026-05-23 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0170_add_system_monitoring'),
    ]

    operations = [
        migrations.AlterField(
            model_name='containeremail',
            name='cars',
            field=models.ManyToManyField(blank=True, related_name='emails', through='core.CarEmailLink', through_fields=('email', 'car'), to='core.car', verbose_name='Машины (по VIN)'),
        ),
    ]
