# Generated by Django 5.2.14 on 2026-05-23 21:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0171_alter_containeremail_cars'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='autotransport',
            index=models.Index(fields=['status'], name='autotransport_status_idx'),
        ),
        migrations.AddIndex(
            model_name='autotransport',
            index=models.Index(fields=['carrier', 'status'], name='autotransport_carr_st_idx'),
        ),
        migrations.AddIndex(
            model_name='bankconnection',
            index=models.Index(fields=['bank_type', 'is_active'], name='bank_conn_type_active_idx'),
        ),
        migrations.AddIndex(
            model_name='carrierservice',
            index=models.Index(fields=['carrier', 'is_active', 'add_by_default'], name='carrier_svc_active_default_idx'),
        ),
        migrations.AddIndex(
            model_name='invoiceaudit',
            index=models.Index(fields=['status', '-created_at'], name='inv_audit_status_idx'),
        ),
        migrations.AddIndex(
            model_name='invoiceaudit',
            index=models.Index(fields=['counterparty_detected'], name='inv_audit_cparty_idx'),
        ),
        migrations.AddIndex(
            model_name='lineservice',
            index=models.Index(fields=['line', 'is_active', 'add_by_default'], name='line_svc_active_default_idx'),
        ),
        migrations.AddIndex(
            model_name='newspost',
            index=models.Index(condition=models.Q(('published', True)), fields=['-published_at'], name='news_published_at_idx'),
        ),
        migrations.AddIndex(
            model_name='trackingrequest',
            index=models.Index(fields=['-created_at'], name='tracking_req_created_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouseservice',
            index=models.Index(fields=['warehouse', 'is_active', 'add_by_default'], name='wh_svc_active_default_idx'),
        ),
    ]
