# Generated by Django 5.2.14 on 2026-06-06 10:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0172_add_performance_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='notificationlog',
            name='core_notifi_contain_39d5fd_idx',
        ),
        migrations.RemoveIndex(
            model_name='notificationlog',
            name='core_notifi_car_id_4d02a7_idx',
        ),
        migrations.AddField(
            model_name='client',
            name='telegram_chat_id',
            field=models.CharField(blank=True, help_text='ID чата клиента в Telegram для уведомлений о разгрузке. Клиент должен написать боту /start, после чего chat_id можно получить командой manage.py telegram_updates.', max_length=64, null=True, verbose_name='Telegram Chat ID'),
        ),
        migrations.AddField(
            model_name='client',
            name='telegram_enabled',
            field=models.BooleanField(default=True, help_text='Дублировать уведомления о разгрузке в Telegram (если указан Chat ID)', verbose_name='Уведомления в Telegram'),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='channel',
            field=models.CharField(choices=[('EMAIL', 'Email'), ('TELEGRAM', 'Telegram')], db_index=True, default='EMAIL', max_length=10, verbose_name='Канал'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='email_to',
            field=models.CharField(blank=True, help_text='Email-адрес или Telegram chat_id получателя', max_length=255, verbose_name='Получатель'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['container', 'notification_type', 'channel'], name='core_notifi_contain_9f9eff_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['car', 'notification_type', 'channel'], name='core_notifi_car_id_03ab06_idx'),
        ),
    ]
