# Generated by Django 5.2.14 on 2026-06-06 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0173_remove_notificationlog_core_notifi_contain_39d5fd_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='telegram_chat_id',
            field=models.TextField(blank=True, help_text='Один или несколько chat_id в Telegram для уведомлений о разгрузке (через запятую или с новой строки). Клиент должен написать боту /start, после чего chat_id можно получить командой manage.py telegram_updates.', null=True, verbose_name='Telegram Chat ID'),
        ),
    ]
