# Generated by Django 5.2.14 on 2026-06-06 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0174_alter_client_telegram_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='telegram_chat_id2',
            field=models.CharField(blank=True, help_text='Дополнительный chat_id для уведомлений', max_length=64, null=True, verbose_name='Telegram Chat ID 2'),
        ),
        migrations.AddField(
            model_name='client',
            name='telegram_chat_id3',
            field=models.CharField(blank=True, help_text='Дополнительный chat_id для уведомлений', max_length=64, null=True, verbose_name='Telegram Chat ID 3'),
        ),
        migrations.AddField(
            model_name='client',
            name='telegram_chat_id4',
            field=models.CharField(blank=True, help_text='Дополнительный chat_id для уведомлений', max_length=64, null=True, verbose_name='Telegram Chat ID 4'),
        ),
        migrations.AlterField(
            model_name='client',
            name='telegram_chat_id',
            field=models.CharField(blank=True, help_text='Основной chat_id в Telegram для уведомлений о разгрузке. Клиент должен написать боту /start, после чего chat_id можно получить командой manage.py telegram_updates.', max_length=64, null=True, verbose_name='Telegram Chat ID 1'),
        ),
    ]
