# Generated by Django 5.2.14 on 2026-06-06 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0175_client_telegram_chat_id2_client_telegram_chat_id3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email 1'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email2',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email 2'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email3',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email 3'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email4',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email 4'),
        ),
        migrations.AlterField(
            model_name='client',
            name='notification_enabled',
            field=models.BooleanField(default=True, verbose_name='Получать уведомления'),
        ),
        migrations.AlterField(
            model_name='client',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Telegram Chat ID 1'),
        ),
        migrations.AlterField(
            model_name='client',
            name='telegram_chat_id2',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Telegram Chat ID 2'),
        ),
        migrations.AlterField(
            model_name='client',
            name='telegram_chat_id3',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Telegram Chat ID 3'),
        ),
        migrations.AlterField(
            model_name='client',
            name='telegram_chat_id4',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Telegram Chat ID 4'),
        ),
        migrations.AlterField(
            model_name='client',
            name='telegram_enabled',
            field=models.BooleanField(default=True, verbose_name='Уведомления в Telegram'),
        ),
    ]
