# Generated by Django 5.2.14 on 2026-06-06 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0176_alter_client_email_alter_client_email2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='notification_enabled',
            field=models.BooleanField(default=True, verbose_name='E-mail уведомления'),
        ),
        migrations.AlterField(
            model_name='client',
            name='telegram_enabled',
            field=models.BooleanField(default=True, verbose_name='Telegram уведомления'),
        ),
    ]
