# Generated by Django 5.2.14 on 2026-06-06 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0177_alter_client_notification_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='telegram_link_token',
            field=models.CharField(blank=True, editable=False, max_length=32, null=True, unique=True, verbose_name='Токен Telegram-привязки'),
        ),
    ]
