# Generated by Django 5.2.14 on 2026-06-06 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0178_client_telegram_link_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarModelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(db_index=True, help_text='Как в карточке авто, напр. «BMW 430I» или просто «BMW».', max_length=100, verbose_name='Марка/модель')),
                ('year', models.PositiveIntegerField(blank=True, help_text='Год выпуска. Пусто = подходит для любого года этой модели.', null=True, verbose_name='Год')),
                ('image', models.ImageField(help_text='Любой формат/размер — приведётся к единому виду автоматически.', upload_to='car_model_images/', verbose_name='Изображение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
            ],
            options={
                'verbose_name': 'Картинка модели авто',
                'verbose_name_plural': 'Картинки моделей авто',
                'ordering': ['brand', '-year'],
                'constraints': [models.UniqueConstraint(fields=('brand', 'year'), name='uniq_carmodelimage_brand_year')],
            },
        ),
    ]
