# Generated by Django 5.2.14 on 2026-06-07 13:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0179_carmodelimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['connection', 'created_at'], name='bt_conn_created_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['state', 'created_at'], name='bt_state_created_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['container', 'status'], name='car_container_status_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['is_important'], name='car_is_important_idx'),
        ),
        migrations.AddIndex(
            model_name='carphoto',
            index=models.Index(fields=['car', 'is_public'], name='carphoto_car_public_idx'),
        ),
        migrations.AddIndex(
            model_name='carphoto',
            index=models.Index(fields=['car', '-uploaded_at'], name='carphoto_car_uploaded_idx'),
        ),
        migrations.AddIndex(
            model_name='container',
            index=models.Index(fields=['status', 'unload_date'], name='ctr_status_unload_idx'),
        ),
        migrations.AddIndex(
            model_name='container',
            index=models.Index(fields=['labels_printed_at'], name='ctr_labels_printed_idx'),
        ),
        migrations.AddIndex(
            model_name='containerphoto',
            index=models.Index(fields=['container', 'is_public'], name='ctrphoto_container_public_idx'),
        ),
    ]
