# Generated by Django 5.2.14 on 2026-06-11 18:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0180_banktransaction_bt_conn_created_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='banktransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('matched_transaction__isnull', False)), fields=('matched_transaction',), name='unique_bt_per_matched_transaction'),
        ),
        migrations.AddConstraint(
            model_name='invoiceitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='invoiceitem_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='invoiceitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='invoiceitem_unit_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='invoiceitem',
            constraint=models.CheckConstraint(condition=models.Q(('total_price__gte', 0)), name='invoiceitem_total_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='newinvoice',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal__gte', 0)), name='invoice_subtotal_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='newinvoice',
            constraint=models.CheckConstraint(condition=models.Q(('total__gte', 0)), name='invoice_total_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='newinvoice',
            constraint=models.CheckConstraint(condition=models.Q(('paid_amount__gte', 0)), name='invoice_paid_amount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='newinvoice',
            constraint=models.CheckConstraint(condition=models.Q(('discount__gte', 0)), name='invoice_discount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='newinvoice',
            constraint=models.CheckConstraint(condition=models.Q(('due_date__isnull', True), ('due_date__gte', models.F('date')), _connector='OR'), name='invoice_due_date_gte_date'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='transaction_amount_non_negative'),
        ),
    ]
