# Generated by Django 5.2.14 on 2026-06-11 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0181_banktransaction_unique_bt_per_matched_transaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newinvoice',
            name='external_number',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Номер с бумажного/PDF счёта от поставщика (для входящих инвойсов)', max_length=100, verbose_name='Номер счёта контрагента'),
        ),
        migrations.AddIndex(
            model_name='containeremaillink',
            index=models.Index(fields=['container', 'is_read'], name='core_contai_contain_b9dc24_idx'),
        ),
    ]
