# Generated by Django 5.2.14 on 2026-06-11 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0182_alter_newinvoice_external_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='container',
            name='days',
        ),
        migrations.RemoveField(
            model_name='container',
            name='free_days',
        ),
        migrations.RemoveField(
            model_name='container',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='container',
            name='storage_cost',
        ),
    ]
