# Generated by Django 5.2.14 on 2026-06-11 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0183_remove_container_days_remove_container_free_days_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeriesCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=64, unique=True, verbose_name='Префикс серии')),
                ('last_value', models.BigIntegerField(default=0, verbose_name='Последний номер')),
            ],
            options={
                'verbose_name': 'Счётчик серии',
                'verbose_name_plural': 'Счётчики серий',
            },
        ),
    ]
