# Generated by Django 5.2.14 on 2026-06-11 19:45
"""B2 (AUDIT_ROUND3): валютный инвариант балансов.

Балансы (`expected_entity_balance`/`recalculate_entity_balance`) суммируют
``amount`` без разреза валюты, поэтому в системе допустим только EUR.

В БД есть исторические USD-строки (6 инвойсов PARDP + 10 транзакций,
импорт из site.pro за 2024–2025). Их не фальсифицируем: констрейнт
добавляется как ``NOT VALID`` — PostgreSQL проверяет только новые/изменяемые
строки, существующие не трогаются. Состояние Django-миграций при этом
содержит обычный AddConstraint (для SQLite-тестов схема строится из моделей,
там легаси-строк нет).
"""

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0184_series_counter'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddConstraint(
                    model_name='newinvoice',
                    constraint=models.CheckConstraint(condition=models.Q(('currency', 'EUR')), name='invoice_currency_eur'),
                ),
                migrations.AddConstraint(
                    model_name='transaction',
                    constraint=models.CheckConstraint(condition=models.Q(('currency', 'EUR')), name='transaction_currency_eur'),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE core_newinvoice ADD CONSTRAINT invoice_currency_eur "
                        "CHECK (currency = 'EUR') NOT VALID"
                    ),
                    reverse_sql="ALTER TABLE core_newinvoice DROP CONSTRAINT invoice_currency_eur",
                ),
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE core_transaction ADD CONSTRAINT transaction_currency_eur "
                        "CHECK (currency = 'EUR') NOT VALID"
                    ),
                    reverse_sql="ALTER TABLE core_transaction DROP CONSTRAINT transaction_currency_eur",
                ),
            ],
        ),
    ]
